### ISSUE TITLE
Food Types can able to set icon same like menu icon

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#100]
Food Types can able to set icon same like menu icon.

<img width="1728" alt="Screenshot 2022-10-14 at 00 00 04" src="https://user-images.githubusercontent.com/15089059/195718875-ae075941-085f-4a23-95d1-7f86a7f34ece.png">

**Comment by mistry-jignesh** [comment]
Verified this issue. Here I am add image for food type but it not set on any food .

![image](https://user-images.githubusercontent.com/75515088/196608411-ce37f9b1-4dbe-4744-b76e-f0290fc7cfb1.png)

Bydefault icon is display on the food.

**Comment by mistry-jignesh** [comment]
Verified this issue . When I have added new food type **(Mixed food)** then food is added.

![image](https://user-images.githubusercontent.com/75515088/196948272-4cb7f0ff-84d7-489f-a552-1a1b22407b4e.png)

Here food dashboard page, food listing page . Food label is display **Veg** .

Which tooltip is need to show here ?

![image](https://user-images.githubusercontent.com/75515088/196948154-8387db09-e212-487a-b5eb-0dd473bc1955.png)

**Comment by mistry-jignesh** [comment]
Verified this issue.  Now according food type name display the tooltip name.

This issue is working proproperly.

So I closed the issue.
