### ISSUE TITLE
Field editor - Term checklist - Food_manager_unit is display on the details page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#108]
Field editor - Term checklist - Food_manager_unit is display on the details page.

Performed below setting from the backend.

![image](https://user-images.githubusercontent.com/75515088/195835590-dac99436-3ec6-4518-8d0a-f2d03200f67b.png)

Food detail page display the Unit values as below image.

![image](https://user-images.githubusercontent.com/75515088/195835879-70ecdbdd-e721-4f2f-a5ce-271aeed33fa8.png)

Additional information section unit details is not display.

![image](https://user-images.githubusercontent.com/75515088/195836642-db0989c2-4920-4ab2-b265-455c4b842047.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

Please edit the specific food post and select the checklist as you want to display, Finally save it. It will appear on frontend.

**Comment by mistry-jignesh** [comment]
Verfiied this issue. As per @kushang-tailor -Edit specific food post and select the checklist as you want to display, Finally save it. It will appear on frontend.This issue is working fine.

So I closed the issue.
