### ISSUE TITLE
Food Menu

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#11]
Each Menu has icon : 

<img width="1516" alt="Screenshot 2022-09-07 at 14 09 46" src="https://user-images.githubusercontent.com/15089059/188874857-efff859e-4d22-44d0-b6d4-110e71fff9af.png">

General Settings :

- Allow multiple category assign to food menu.

Based on settings, user can select single or multiple category on menus. 

Once user will select category then it will load all food item which associated to this categories.

each category has possibility to assign image.

<img width="1524" alt="Screenshot 2022-09-07 at 14 10 22" src="https://user-images.githubusercontent.com/15089059/188874965-9724ec00-c974-48f4-b764-05d6a6d86066.png">

 

**Backend**

Food Menu - I have select Food category but selected category is not display on the view page.

![image](https://user-images.githubusercontent.com/75515088/182526065-063677d4-15ef-4fdd-b50a-d83cd0170653.png)

![image](https://user-images.githubusercontent.com/75515088/182526125-dd38c201-412d-4487-95b9-704651e8321c.png)

**Comment by KushangDarji** [comment]
Can you please explain this, What is the front-end view of this food menu?

**Comment by krinaydhanani** [comment]
From the front side, people can purchase food. If we are not going to list the food-fronted side then from where people can purchase it and how restaurant owners can sell it so we are going to list the food on the fronted side.

**Comment by ashokdudhat** [comment]
![Uploading Screenshot 2022-09-07 at 14.03.33.png…]()

**Comment by ashokdudhat** [comment]
<img width="1673" alt="Screenshot 2022-09-07 at 14 03 33" src="https://user-images.githubusercontent.com/15089059/188874120-f11bbac0-9757-4c3b-824f-eca93630b570.png">

**Comment by ashokdudhat** [comment]
if user have selected two categories and two categories has same food item and it will show two times in menu but user can able to delete from menu.

<img width="748" alt="Screenshot 2022-09-07 at 14 08 17" src="https://user-images.githubusercontent.com/15089059/188874626-5dbdfb29-e47c-475b-9485-18309b5482a2.png">

**Comment by mistry-jignesh** [comment]
Verified this issue . Now Menu icon is added in the food menu.

When I have select any icon for food menu then this icon show the menu in frontend side.

So I closed the issue.
