### ISSUE TITLE
Field editor - Field type - WP Editor is not working in the backend

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#110]
Field editor - Field type - WP Editor is not working in the backend.

![image](https://user-images.githubusercontent.com/75515088/195844938-e2f25cc4-ab0c-4953-b5f4-c810bc0d95ce.png)

In the backend it should be display like as below.

![image](https://user-images.githubusercontent.com/75515088/195845218-23d7c33f-972d-44c4-821b-39f26b546eb6.png)

**Comment by mistry-jignesh** [comment]
This issue is verified . I have added content in the WP editor from the backend .

Save content. 

Observed that food details page this content is display .

Now edit this food from the frontend - Here this content is display but click on the save change button.

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

It is occurred due to Extra fields under field editor. Please reset the Extra fields and check again.

**Comment by mistry-jignesh** [comment]
I have reset extra form field and save it.

Now this issue is fixed and working fine.

Observed that food details page this content is display .

So I closed the issue.
