### ISSUE TITLE
Notice label issue in food manager.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#112]
I can see **No categories found.** Notice in food type.
 

<br class="Apple-interchange-newline">

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/35419531/196153311-61aed0f0-e1dd-48ed-b811-e2943337f935.png">

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Now correct notice is availabel.

![image](https://user-images.githubusercontent.com/75515088/196429350-6ac62a48-ee98-4968-bd31-be72df6117b0.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now notice message is display proper.

From **Types** word first letter should be in the small letter. Need to correct  it 

![image](https://user-images.githubusercontent.com/75515088/196430420-94289b93-9ba2-4e06-b8d7-80ee8812df91.png)

**Comment by mistry-jignesh** [comment]
Now this issue is fixed . From **Types** word first letter is display in the small letter.

So I closed the issue.

![image](https://user-images.githubusercontent.com/75515088/196436115-0d2d6b28-aaab-49f8-a3ad-06dc7512dbd4.png)
