### ISSUE TITLE
Permalink setting is not working.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#113]
Please fix this issue because the food manager should work with all the permalink settings.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/35419531/196156229-6a6c25b3-e38e-4393-ab9f-9a24abb7b042.png">

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now this issue is fixed & working .

Food manager is working with permalink settings .

So I closed the issue

**Comment by patel-nimesh** [comment]
Right now When do a fresh setup and add a food then on frontside on food listing page the food will not load and it will display just loader. After change the permalink to post name the food will be load.

**Comment by patel-nimesh** [comment]
@krinaydhanani I have again verified this and check in fresh setup. Still the issue arise please refer the below video

https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/d4d2ce45-680c-49fa-a07e-d0b277741018

**Comment by patel-nimesh** [comment]
Now the permalink setting is working and foods are loading
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/46d699e3-797a-4e6d-946d-bc1e5f5fa305)
