### ISSUE TITLE
Remove Food Symbol / Tag field.

### ISSUE THREAD

**Issue by kushang-tailor** [wpfoodmanager/wp-food-manager#114]
1.Please remove **Food Symbol / Tag** field and Use **Food type taxonomy** to identify the Food type.
2.Please use the Regular **Veg and Non-Veg Food Icon**.

![image](https://user-images.githubusercontent.com/25924876/196335145-a8feed08-886b-4039-aa17-38e15a7999a8.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed .

Now removed Food Symbol / Tag field and  Use Food type taxonomy to identify the Food type.

Availabel regular icon for the foo type.

So I closed the issue.
