### ISSUE TITLE
Food banner label name should be similar

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#117]
Food banner label name should be similar.

Right now frontend form label name is display -  Food Banner.

![image](https://user-images.githubusercontent.com/75515088/196615928-aab6bd6d-a74d-40ad-b702-e346d20881e7.png)

In the backend side label name is display - Food thumbnail .

![image](https://user-images.githubusercontent.com/75515088/196616600-53d358f8-14e5-4022-9ceb-7801b612b3d8.png)

So need to suggest which label is proper at both side.

**Comment by krinaydhanani** [comment]
In this bug, we are going to implement a food image the same as the Event Manager concept.

When the user adds the food it will become a food thumbnail by default and we are showing it on the food listing page.

If the user wants to add a different image for food then the user can add the banner the same as the event manger and they can change the thumbnail and banner.

**Comment by mistry-jignesh** [comment]
Here in the backend : Image field need to show food banner image. 

Currently thumbnail image is display. 
Here need to correct it.

![image](https://user-images.githubusercontent.com/75515088/197116367-1c7acfcd-d557-4269-94f9-6bb8c29f0408.png)

Should be display below image .

![image](https://user-images.githubusercontent.com/75515088/197116516-006083d2-ffb0-447f-9d01-726b2d2dc2b8.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

At the backend in the image field. Image as display food banner.

![image](https://user-images.githubusercontent.com/75515088/197123241-8b25095a-6c3d-41f6-a4c1-890b375edde5.png)

![image](https://user-images.githubusercontent.com/75515088/197123297-21c4b389-45b8-4533-a56a-dd10d797a7c9.png)

This issue is working fine. So I closed it.
