### ISSUE TITLE
Extra option form field - URL Type issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#120]
If I have created URL type in the Food form field

Add value in the URL field .

Now in the extra form Field add URL type filed .

Here in the URL field text box should be display blank. Text box taking values as food form URL type value.

![image](https://user-images.githubusercontent.com/75515088/196652202-55849e54-547f-4a8d-9490-74540a338d24.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

Here you set both fields URL name is same. Because of that the Text box taking values as food form URL type value. So I request to you, Whenever created new field please set the name of fields as unique. Because under same name, it's conflict with each other.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

If I have taken field name as uniqure or same .This issue is not facing.

It is working fine.

So I closed the issue.
