### ISSUE TITLE
Extra form field-  Term Checklist, Term Multiselect and Term Select fields type not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#145]
For refrence issue #126 

Extra form field-  Term Checklist, Term Multiselect and Term Select fields type not working.

![image](https://user-images.githubusercontent.com/75515088/199720422-4ad325f6-d699-46cb-8ffb-84dca84d21f4.png)

**Comment by kushang-tailor** [comment]
@mistry-jignesh ,

When you use this 3 field types under Extra topping forms, Please choose the taxonomy as an unique instead of twice.

**Comment by mistry-jignesh** [comment]
As per @kushang-tailor -When you use this 3 field types under Extra topping forms, Please choose the taxonomy as an unique instead of twice. Now this issue is fixed . During testing found other issue . For that open new bugs.

So I closed the issue.
