### ISSUE TITLE
Food Dashboard - Pagination option is not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#149]
Food Dashboard - Pagination option is not working .

![image](https://user-images.githubusercontent.com/75515088/199899073-1ef2c84f-0311-4444-a5c2-72de9a2d6f11.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working .

Not able move on second or other page.

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have verified this issue twice from my end and it is already working fine. So, I request to you please check with fresh WordPress installation wizard.

**Comment by mistry-jignesh** [comment]
Verified this issue.Now pagination option is working fine.

This issue is fixed .So I closed the issue.
