### ISSUE TITLE
Foods are missing in the list/Grid view section

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#150]
Loign as organizer .

There are three food are availabel in the dashboard .

![image](https://user-images.githubusercontent.com/75515088/199907051-bfe0b6e9-c696-4d39-b926-bfea08636166.png)

Foods are missing in the list/Grid view section.

![FoodsIss1](https://user-images.githubusercontent.com/75515088/199908280-14b19869-db86-4005-80f9-03e8b9e35957.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have checked and verified this issue from my end and it is working fine.

**Comment by mistry-jignesh** [comment]
Created new organizer .

Added new food . Food listing page still face same issue.
Foods are missing in the list/Grid view section.

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have verified this issue twice and it is working fine. So, I request you please check this issue in fresh WordPress installation wizard.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is not facing in the setup.

All Foods list are availabel in the list/Grid view section.

So I closed the issue.
This issue is working fine . 

So I closed the issue.
