### ISSUE TITLE
Field Type Select -  Selected value is display small letter

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#153]
Field Type Select -Selected value is display small letter. 

First letter should be in capital letter.

![image](https://user-images.githubusercontent.com/75515088/201325684-b51b3369-0550-4b90-aea3-d892aac9f23e.png)

**Comment by mistry-jignesh** [comment]
**First letter should be in the capital letter** and other letter should be small letter.

![image](https://user-images.githubusercontent.com/75515088/201338104-a8056440-9e91-447b-b766-4f85fa8f4c14.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

This issue is already fixed, I can't regenerate it. I have checked and verified from my end twice and it is working fine. Can you please check on your end and do let me know?

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed & working.

First letter is in the capital letter.

![image](https://user-images.githubusercontent.com/75515088/202081597-122c7878-4059-4ad6-934a-e03838a98f93.png)


So I closed the issue
