### ISSUE TITLE
 New extra tropping filed is unable to add

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#155]
New extra tropping filed is unable to add .

![image](https://user-images.githubusercontent.com/75515088/202087218-b72d5017-d3a1-4a81-b194-40fee6db1c65.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have checked and verified this issue from my end and it is working fine.

**Comment by mistry-jignesh** [comment]
Now this issue is not able to reproduced. This issue is working fine.

![image](https://user-images.githubusercontent.com/75515088/202435441-add9dcb7-baef-43f3-ac85-2ee4f363255b.png)

Add option button is availabel and It is working properly.

So I closed the issue.
