### ISSUE TITLE
Extra form field - File type - Multiple File- PDF file,text file

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#157]
From backend select below option .

![image](https://user-images.githubusercontent.com/75515088/202177790-24984685-e5e8-4a28-9542-040d5408c4c1.png)

Add other file also like PDF and other file.

![image](https://user-images.githubusercontent.com/75515088/202178008-92d628b6-1b8a-4a56-8685-66f714f0d385.png)

Details page PDF file is display simple text. It should be download and in working mode.

![image](https://user-images.githubusercontent.com/75515088/202178304-a6269f89-a0f2-4067-ada6-7d2469a3d97e.png)

**Comment by mistry-jignesh** [comment]
Verified this issue .This issue is not fixed.

Selected multiple file not save. Agian edit food then only one file is display as selected.

![image](https://user-images.githubusercontent.com/75515088/202376453-baaa5ac9-0490-4321-8582-c0ac6873b21d.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is not fixed.

At front end select multiple file but edit again then no file is selected display.

![image](https://user-images.githubusercontent.com/75515088/202425680-566d0091-894d-4e34-b971-d8452f1d2425.png)

Backend selected file is display one .

![image](https://user-images.githubusercontent.com/75515088/202425843-14a06ed8-f303-49a7-8d57-4f1e021f4765.png)

Details page select file is not display.

![image](https://user-images.githubusercontent.com/75515088/202426002-f14a7d4e-6c1f-450f-8745-d5c3589a6342.png)

**Comment by kushang-tailor** [comment]
Issue fixed with same as issue #158.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Selected image is display on the details page .

So I closed the issue.
