### ISSUE TITLE
Need Banner and logo and Icons for Org

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#16]
Need Banner and logo and Icons for Org

https://wordpress.org/plugins/wp-food-manager/

**Comment by kaushikpokal** [comment]
Logo
![food manager](https://user-images.githubusercontent.com/83581741/193260879-88de8578-478f-4cb9-9984-8bca2d47d7c2.png)

**Comment by kaushikpokal** [comment]
Banner
![food manager banner](https://user-images.githubusercontent.com/83581741/193514038-132bfe60-682f-44e5-b62a-f60552ab7e76.png)

**Comment by kaushikpokal** [comment]
@krinaydhanani  Please check it

**Comment by krinaydhanani** [comment]
[screenshot.zip](https://github.com/wpfoodmanager/wp-food-manager/files/9725136/screenshot.zip)

**Comment by mistry-jignesh** [comment]
After discussed issue with krinaybhi. Informed that now banner & logo designed is aprroved.

So I closed the issue.
