### ISSUE TITLE
Backend - Food/Extra form field - Term Checklist, Term Multiselect and Term Select fields are missing

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#160]
Backend - **Food/Extra form field** - Term Checklist, Term Multiselect and Term Select fields are missing.

![image](https://user-images.githubusercontent.com/75515088/202362990-95e02ef6-e3bb-4ac3-8b58-ca2840ced222.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

This 3 fields are manage and available from the Frontend only. For more clarification, Please check the WPEM plugin's Field editor options for the same.

**Comment by mistry-jignesh** [comment]
As per @kushang-tailor : This 3 fields are manage and available from the Frontend only. **For more clarification**, Please check the WPEM plugin's Field editor options for the same.
Here I closed the issue.
