### ISSUE TITLE
Need to fix Food title length

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#163]
Need to fix Food title length.

![image](https://user-images.githubusercontent.com/75515088/202416055-c695bca2-1806-47e1-b079-f29124212bac.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

This title is arriving from the **Event Listing Theme**. So, When we make theme for our Food manager plugin then this issue will be resolved.

**Comment by mistry-jignesh** [comment]
As per @kushang-tailor  :  This title is arriving from the Event Listing Theme. So, When we make theme for our Food manager plugin then this issue will be resolved.

So I closed the issue.
