### ISSUE TITLE
Food Dashboard - Add all category in the food issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#166]
Before adding all category in the food .Dashboard is display as below image.

![image](https://user-images.githubusercontent.com/75515088/202668004-c804fdfc-16ec-4660-9fca-71896afd8782.png)

After adding adding all category in the food .Dashboard is display as below image. Here "Pending Approval"  text "Approval" text is display next line.

![image](https://user-images.githubusercontent.com/75515088/202668893-c82a2457-925e-423f-ad70-085e4e480e46.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Not uanble to select all Food category right now.

Need to check it.

![image](https://user-images.githubusercontent.com/75515088/203715521-247558c7-96b5-4262-8754-c858f690b0f8.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have checked and verified this issue as twice. And it is working fine. So, Can you please check again and please make sure that you have only 1 dropdown taxonomy option is available per form.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now able to select all food category .

Here "Pending Approval" text " is display the same horizontal line.

![image](https://user-images.githubusercontent.com/75515088/203720366-a84c2bc0-d450-4267-848c-abf76adf9d3c.png)

So I closed the issue.
