### ISSUE TITLE
Backend - Field editor - When change field type then box should be clear automatically

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#167]
When change field type then box should be clear automatically.

![image](https://user-images.githubusercontent.com/75515088/202675297-e54974da-7d3a-4878-b45b-0f83d3d5c0e5.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

As per my discussion with @krinaydhanani Sir, Currently we don't need this type of functionality, In future we will see it regarding this. And also this is not right if we empty the field values changing upon field type as a developer perspective.

**Comment by krinaydhanani** [comment]
In the next version if we require then we will enhance this feature. I am going to move this issue to the next milestone.

**Comment by mistry-jignesh** [comment]
As per @krinaydhanani - In the next version if we require then we will enhance this feature. I am going to move this issue to the next milestone.

So  I am added label for this issue as enhancement.

**Comment by vry-kvl** [comment]
@mistry-jignesh - In this bug, there is nothing to change, This is not the right way Because If I change the field type from the backend but the meta key does not change then it will fetch that meta_key value, This field will empty if you change the meta_key.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please can you verify that, On my point of view it is right or not.

**Comment by patel-nimesh** [comment]
@vry-kvl I checked the above flow. That value is not changing when we switch the field type. For this get confirmation from the @krinaydhanani

**Comment by dhruvikathrotiya** [comment]
As per @vry-kvl  - In this bug, there is nothing to change, This is not the right way Because If I change the field type from the backend but the meta key does not change then it will fetch that meta_key value, This field will empty if you change the meta_key.
Soo, I am resolving this issue.

**Comment by patel-nimesh** [comment]
According to the developer's comment this issue is not possible. So I am closing this issue
