### ISSUE TITLE
Cursor Click not show in below link

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#17]
Cursor Click not show in below link

<img width="1481" alt="Screenshot 2022-08-16 at 23 29 31" src="https://user-images.githubusercontent.com/15089059/184988671-ba299755-8414-404e-97fa-e47709424d1b.png">

**Comment by KushangDarji** [comment]
@krinaydhanani,

This notice is arriving from the **'Event listing'** theme.

**Comment by KushangDarji** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/25924876/187369492-05b927f0-99bd-499a-bc2c-711e9abcf92c.png)

**Comment by mistry-jignesh** [comment]
Verified this issues . Now setup page is looking properly.

Cursor click show on the link.

![image](https://user-images.githubusercontent.com/75515088/191956183-91317859-2eee-47d8-a8f3-4bb2b4e2e996.png)
