### ISSUE TITLE
Edit food :  "X" icon in the file type field 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#171]
Food form field :  

First form field as select WPeditor field.

![image](https://user-images.githubusercontent.com/75515088/203299549-41eac42c-2060-4eb5-8815-433066cfc737.png)

Added content at frontend section.

Now change type from wp editor field to file type.

![image](https://user-images.githubusercontent.com/75515088/203298096-17d96dbd-7462-4450-9e89-504e0e860614.png)

Edit food from frontend . Here WPeditor field "X" icon is display.

![image](https://user-images.githubusercontent.com/75515088/203299282-d60804c1-da30-42ee-91b9-5c7f1c5cc551.png)

**Comment by mistry-jignesh** [comment]
Display the Image local URL . When agian select Wpeditor field type.

First form field as select WPeditor field.
Added content at frontend section.
Now change type from wp editor field to file type.
Added image at frontend section.
Display image at details page.
When agian select Wpeditor field type then bydefault in the editor display the Image local URL.

![image](https://user-images.githubusercontent.com/75515088/203758273-6ba96db6-17ae-4243-b60c-02e290f7cb44.png)

![image](https://user-images.githubusercontent.com/75515088/203757204-ad75751e-0945-4fea-bbbc-f23ee4052dd5.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . At frontend sectio working fine. _**I am facing issue in the backend section.**_

In the file type field is display the **_specail symbol and  Download button_** as you can see in the below image.

![image](https://user-images.githubusercontent.com/75515088/203920411-fb4d3b91-5ca4-41ca-8258-7d6c69a9e596.png)

Need to check it.

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

Can you please download the latest version of the plugin. Because I can't reproduce this issue. And from my end I have checked this scenario and it s working fine.

**Comment by mistry-jignesh** [comment]
I have taken new version and facing old issue agian. 

When agian select Wpeditor field type then bydefault in  the backend  editor display the Image local URL.

![image](https://user-images.githubusercontent.com/75515088/203925339-2c33e5e4-9005-4a4a-aadd-77df1da20288.png)

Need to check at your end.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now "X" icon issue and  in the backend  editor bydefault display the Image local URL issue is are fixed.

Now both issues are working fine. So I closed the issue .
