### ISSUE TITLE
Extra form field - WP editor- Change field type from Wpeditor to File type

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#176]
First add wpeditor field from the backend.

At frontend side add text in the WPeditor field.

Details page added text is display properly.

Now from backend change field type from Wpeditor to File type.

At frontend/Backend side : In the file type field display  "X" Icon .

![image](https://user-images.githubusercontent.com/75515088/203911731-8e7290e0-b895-42d2-9f24-db02e1d8cf6a.png)

**_Also details page is display special symbol._**

![image](https://user-images.githubusercontent.com/75515088/203913988-f5cfdb58-21c2-4e8f-ae67-b1455e609e70.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

Can you please download the latest version of the plugin. Because I can't reproduce this issue. And from my end I have checked this scenario and it s working fine.

**Comment by mistry-jignesh** [comment]
Verified this issue with new version. 

In the file type field display **_"X" Icon is working properly_**  with frontend/backend section.

This issue is working fine. So I closed the issue.
