### ISSUE TITLE
Extra Toppings - Display warning: Undefined property error message

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#177]
Extra Toppings - Display warning: Undefined property error message.

This error messgae is display in the extra toppings section.

Right now for this issue steps not able to find but facing this issue in the Extra Toppings section.

![image](https://user-images.githubusercontent.com/75515088/203917768-bcd2c0e7-195b-4604-b2bb-d8525b8df46b.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

Here I wanted to suggest you that, Please reset all fields from the backend in field editor and after you can check with fresh adding new fields. Because I have checked and verified this scenario from my end and I didn't face any issue.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this error message is not availabel at extra topping section.

This issue is working fine .  So I am closed the issue.
