### ISSUE TITLE
Text label is wrong and need to correct it

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#18]
Text label is wrong and need to correct it.

<img width="1558" alt="Screenshot 2022-08-16 at 23 27 57" src="https://user-images.githubusercontent.com/15089059/184988819-906ae943-fefd-4fa8-8016-d33a46b7561a.png">

**Comment by krinaydhanani** [comment]
@KushangDarji Please rename  **Post an Food --> add Food**

**Comment by mistry-jignesh** [comment]
Verified this issue. Now text label is correct.

So I closed the issue.
