### ISSUE TITLE
Food detail page - In PDF file download button is not display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#182]
I have uploaded multiple file.

Example - I have uploaded 4 files .

Here First 3 files are image & last file is PDF file.

In the detaila page 3 images are display properly. In the last option PDF file - Download button is missing.

It is display blank screen .

![image](https://user-images.githubusercontent.com/75515088/204980827-677f7d9b-08a2-40da-b4ba-c4d7434cb021.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please double check this issue and verify again.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/119648390/211516180-17db03bd-6215-48a7-8843-2c862efce746.png">

I had checked but download button is properly display here.

**Comment by patel-nimesh** [comment]
If use this scenario then on front side Download button is getting cut

![image](https://user-images.githubusercontent.com/121149500/211720933-e69d6d9c-f814-409d-a408-8be74a0433ee.png)

**Comment by vry-kvl** [comment]
This is related to design.

@kaushikpokal - please fix it.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/212235911-17484267-7f10-4ef1-8847-a5264334fea5.png)
![image](https://user-images.githubusercontent.com/121149500/212235963-33ba2228-63e2-4f8c-9b54-bd55be629257.png)

Now it is displaying properly
