### ISSUE TITLE
Do not show slug in the repeated field.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#183]
We do not need to show the slug at admin and fronted side to the user because it's not necessary to show them. We have to do it the same as the Sell Ticket addon.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/35419531/206671814-90697223-acee-4b71-88de-ec684804f7d5.png">

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/211545276-fa61623d-ba47-4ef4-aa45-05b35372d05f.png)

yes the field is removed ... No slug will display in admin side or front side
