### ISSUE TITLE
Users should add ingredients & Nutrition from the Add Food at the fronted side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#184]
Users should add ingredients & Nutrition from the Add Food at the fronted side because right now users can not add the ingredients & Nutrition forms.

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
I have checked this functionality and raised some issues regarding this. Functionality is working fine so I am closing this issue
