### ISSUE TITLE
Food Type remove heading bg banner

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#185]
Food Type single page remove heading bg banner and make simple
![image](https://user-images.githubusercontent.com/83581741/208039927-c6c9e27f-02c0-44f4-b4e4-42010f9753e5.png)

**Comment by vry-kvl** [comment]
Currently, this type of UI doesn't exist.

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by vry-kvl** [comment]
This image is looks like a blur and drainy, but this is depend on user which size of image he/she upload in the media.

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/221095976-7d71a987-f107-4dd3-810d-8fade4d23c5e.png)

Now its look like this

@patel-nimesh - please verify, This image resolution is proper or not.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/221097307-1e6f4417-c610-4b4f-b342-fea5fd1c687e.png)

Now the image looks proper
