### ISSUE TITLE
We need to remove Category dependency from the food menu.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#187]
The reason is we are going to use food menu for the table reservation and restaurant manager separately so we have to give fredome to user they can add any items in menu.

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/213096388-d2cf88ab-6aee-4c4e-a1dc-74d2349c8510.png)

Filter is not working and also if we select food type then selected option is not displaying

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/213145648-f0e272e2-5b05-446e-925f-3b8e8c8ec59b.png)

Now it is working proper
