### ISSUE TITLE
If their is no food item then on frontside it is displaying the loader 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#188]
If there is no food item then on frontside it is displaying the loader 

![image](https://user-images.githubusercontent.com/121149500/210197696-54be9f39-a2e6-4f79-8f85-78e50c38e8c5.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - This is already working but after changing the file to resolve #198 issue, therefore this functionality is breaking.
Currently there is no food then error throws like : 
![image](https://user-images.githubusercontent.com/119648390/211287435-d2f22a34-066d-41db-86b3-9a96978b5518.png)

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/211720178-6cfab01a-d479-4f5a-9648-2f70aef08b6c.png)

yes now message is displaying.. This issue resolved
