### ISSUE TITLE
Not able to add / edit food from frontside

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#189]
From front side not able to add or edit food

![image](https://user-images.githubusercontent.com/121149500/210210818-79fdc518-d401-4a00-a781-fc3499a677f1.png)

At bottom, no submit button is their

**Comment by vry-kvl** [comment]
@kaushikpokal - This issue will be fixed by our plugin because whenever I use our food-listing theme, there is no issue, but on Twenty-Three and other WordPress default themes, the plugin should be compatible with the design.

Please review.

**Comment by patel-nimesh** [comment]
When edit food then it is not able to update and also topping field UI is not proper
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/2831e855-5cc6-401e-b520-d5385870889e)

**Comment by patel-nimesh** [comment]
Still facing the issue at edit food time.
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/575e3b79-dee3-4d44-9d0b-ddb6ee4fc018)

**Comment by patel-nimesh** [comment]
Now this issue is fixed
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/90a8900a-89c8-40f5-8949-98c3b1aab2d0)
