### ISSUE TITLE
Video and Text link need to correct it

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#19]
Video and Text link need to correct it

<img width="1643" alt="Screenshot 2022-08-16 at 23 32 43" src="https://user-images.githubusercontent.com/15089059/184989054-b9a6f678-bb14-4bc7-b4a4-2c067171228f.png">

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Video URL link is remove and text is updated.

So I closed the issue.
