### ISSUE TITLE
Food category image is not displaying

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#191]
food category image is not displaying properly if we set a both image and use into menu

![image](https://user-images.githubusercontent.com/121149500/210215452-7798a5e3-89ec-4909-aee7-29b69310573a.png)
![image](https://user-images.githubusercontent.com/121149500/210215504-1a1fdb28-91a9-437b-84f5-9afb3b85b8f0.png)

frontside
![image](https://user-images.githubusercontent.com/121149500/210215556-142524d5-5c07-473b-a583-e1c715849451.png)

**Comment by patel-nimesh** [comment]
Done 

This issue is caused due to older version...Now using latest plugin issue is not arise

**Comment by vry-kvl** [comment]
@kaushikpokal - This issue will be fixed by our plugin because whenever I use our food-listing theme, there is no issue, but on Twenty-Three and other WordPress default themes, the plugin should be compatible with the design.

 Please review.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/212234676-43fc5017-542b-47dc-9766-934b84c71e6c.png)

Now it is proper
