### ISSUE TITLE
Food Ingredient ,nutrition's and unit count is not increasing in admin side

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#193]
![image](https://user-images.githubusercontent.com/121149500/210215914-12ef1c60-826c-4902-b942-2d853bdafda3.png)

if we use Ingredient , nutrition and unit in food then it should increase the count on the admin side on the ingredient listing , nutrition and unit count listing

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/211463564-736ad750-b504-464f-bf85-57b401b4300a.png)

Now all three (Nutrition , Ingredients and Units ) number (count) is increasing
Also Edit/remove/update working fine it will increasing/decreasing the count based on the action.

All working good so I am closing this issue

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/213638999-59622f59-9394-463f-8d6c-1a885ad71a19.png)
![image](https://user-images.githubusercontent.com/121149500/213639073-780d7629-0287-48bd-83d0-f5a9051e8e39.png)

Please refer the above screenshots.. It will shows the count of after and before updating. Indicates the count increase
Now it is working properly. So I am closing the issue
