### ISSUE TITLE
food unit should not display on frontside if we disable from setting

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#194]
if we enable food ingredients & nutritions and disable the unit then on frontside it is displaying the unit. it should also hide the unit on front side

![image](https://user-images.githubusercontent.com/121149500/210217824-aa92037e-63ce-4fb4-a756-7668e9e1fdb8.png)
![image](https://user-images.githubusercontent.com/121149500/210217864-81bf8031-8fd6-4a92-a76f-d8d6abbb3e9c.png)

**Comment by vry-kvl** [comment]
The Food ingredients, nutrition, and units are interconnected & dependable on each other. So, I have removed these 3 settings from the Global settings menu.
For now, you can Enable & Disable these settings from the Single Food listing page at the backend under the Advanced tab.
![image](https://user-images.githubusercontent.com/119648390/211247624-f38c85d0-63b8-47e8-94ed-4afc4a44d5a8.png)

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/211462622-cd4ac507-c091-432b-aa20-64c2852b66dc.png)

The global setting is removed from the WPFM plugin inside the General tab...Now this setting can be manage from the food adding from admin side
