### ISSUE TITLE
Wp Food manager conflict with wpem-yoga theme

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#198]
First I have activated wpem-yoga theme.
Activated wp food manager .
Open post an event page.
Here in the Organizer Details & Venue Details section.
"Here" button is not working .

If I am deactivated Wp Food Manager plugin then it is working fine.

![image](https://user-images.githubusercontent.com/75515088/210706826-6b799db2-b411-4b6e-8e78-c71e4f0f546a.png)

**Here I have added wpem-yoga theme as below.**

[wp-food-manager-1.0.4 (11).zip](https://github.com/wpfoodmanager/wp-food-manager/files/10349528/wp-food-manager-1.0.4.11.zip)

**Comment by vry-kvl** [comment]
@mistry-jignesh - please verify.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed and working fine.
Here in the Organizer Details & Venue Details section.
"Here" button is  working . So I closed the issue.
