### ISSUE TITLE
Coding improvement.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#199]
Improve code, class, functions and folder structure.

**Comment by patel-nimesh** [comment]
I have done with the testing after the code cleanup

**Comment by patel-nimesh** [comment]
Due to Code Improvement, it is conflicting with other things, So I am open this bug again

**Comment by vry-kvl** [comment]
Now, there is no confliction code remain related to this bug, Soo @patel-nimesh you can close this bug.

**Comment by patel-nimesh** [comment]
I have retested all issues... So I am closing this issue
