### ISSUE TITLE
If use twenty twenty three theme then file upload section design is not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#200]
If use twenty twenty-three theme then the file upload section design is not proper

An extra download button is displayed and also pagination design is not proper

![image](https://user-images.githubusercontent.com/121149500/211721370-7eedbebc-05a4-44a7-b59c-4721a27dbb3a.png)
![image](https://user-images.githubusercontent.com/121149500/211721423-8ee20310-bb6f-4c02-821c-a0d4fb1ce8d3.png)

**Comment by vry-kvl** [comment]
@kaushikpokal - This is related to design and please let me know when you start this issue to solve. Need to talk.

Actually last sliders design is totally messed-up and it is cover-up behind the section.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/212235471-17c83da8-16b1-4b75-ad7c-0aba1c061aab.png)
![image](https://user-images.githubusercontent.com/121149500/212235477-cf4950df-1276-4f68-994b-4e29c5ce5a20.png)

The design is proper...But the extra Download button is still displaying
![image](https://user-images.githubusercontent.com/121149500/212235775-dce563e4-68fd-4ead-b41d-4d3fc654c03d.png)

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/212249692-9e84b648-5177-40f9-aae8-76e9571e97de.png)

Now it is proper... No extra Download button is displaying
