### ISSUE TITLE
Currency setting position is not working on frontside

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#201]
![image](https://user-images.githubusercontent.com/121149500/211737464-eaa09618-1f84-4384-89df-3b5203d499d8.png)
![image](https://user-images.githubusercontent.com/121149500/211737531-93be8b6f-22a3-4172-aa5d-abc9dacffe48.png)

WPFM plugin currency setting the currency position is not working.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please can you install the latest version : https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2

And then check this issue.

This is working properly.

**Comment by patel-nimesh** [comment]
@vry-kvl I have checked and still it is not working

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/212660594-de9f132e-9f35-45d1-baba-22e56483ad80.png)

Now it is working
