### ISSUE TITLE
License tab should be their

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#202]
License tab should be their for licensing. same like WPEM

**Comment by vry-kvl** [comment]
@kushang-tailor - The license tab code should be in paid version of addon not in free addon.

**Comment by patel-nimesh** [comment]
yes now the license tab is displaying

![image](https://user-images.githubusercontent.com/121149500/213085791-d6e4b8ee-3198-4d6a-9dd5-83490ba592d1.png)
