### ISSUE TITLE
Ingredients and Nutrition's getting blank once we add value and add another 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#207]
Ingredients and Nutrition's getting blank once we add value and add another 

![image](https://user-images.githubusercontent.com/121149500/212868482-d44b7d9f-fd82-4ce7-a6fd-48b12adfae81.png)
![image](https://user-images.githubusercontent.com/121149500/212868525-af70f604-bc1c-43c4-9004-3cf948f4aa77.png)

please refer the steps:
1.From front side add food page add any nutrition's or Ingredients and add value
2.Now any other nutrition's or Ingredients and check the given previous value is removed. It should not remove

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify again.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/213126774-acf35bbc-c6e6-4601-b55a-a7d466995068.png)

Now it is working properly
