### ISSUE TITLE
If delete Ingredient& nutrition's then it should be deleted from front side 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#208]
![image](https://user-images.githubusercontent.com/121149500/212880073-d4e76112-42d2-4293-8501-3e90a5255983.png)
![image](https://user-images.githubusercontent.com/121149500/212880226-8f57d58b-3fc1-45b8-b66e-6ee923ccd6eb.png)
![image](https://user-images.githubusercontent.com/121149500/212880338-3943b375-d440-4fd8-a589-a306cf9c5fbe.png)

If delete Ingredient& nutrition's then it should be deleted from front side . Right now we have to again update the product then and then it will remove from the product detail page

Also in this case calcium the first nutrition is added in backend and frontside
![image](https://user-images.githubusercontent.com/121149500/212881041-8765e20b-5f59-4473-9bc6-97f462ea6669.png)
![image](https://user-images.githubusercontent.com/121149500/212881083-c4163830-8fd3-491b-b0a6-705fc7a9a403.png)

**Comment by patel-nimesh** [comment]
If we delete this then now on the front side all data for nutrition or Ingredients is deleted

**Comment by vry-kvl** [comment]
Go to the food manager settings and checked the checkbox under settings tab label name as : Delete Data On Uninstall
And re-install the plugin.
@patel-nimesh - Please verify again.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/213128832-fdbb0f59-f775-4d2a-bca1-a14be526e2c3.png)

Now it is working proper
