### ISSUE TITLE
Field Editor 

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#21]
We need Field Editor same like WP Event Manager has. It  allow to add field in Food, Ingredients, Neutritions, Units ..

**Comment by mistry-jignesh** [comment]
Verified this issue . Now Food form field are working fine .

Currently facing issue in the Extra options form fields.

For that created new issue in the version 1.0.3. 

Issue number is - https://github.com/wpfoodmanager/wp-food-manager/issues/126 

So I closed the issue here.
