### ISSUE TITLE
Edit time nutrition and ingredients should be display

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#210]
![image](https://user-images.githubusercontent.com/121149500/213374131-20c95ee3-1606-4bc4-9cee-660afe32ef2a.png)

From food dashboard if we edit nutrition and ingredients then it should be display all data respectively.

**Comment by vry-kvl** [comment]
![Uploading image.png…]()

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220250586-74f640ab-35d1-4050-a41a-8516d9ab564c.png)

The flow is not proper.. In selection field the previous added should be display.

Right now what happens that the previous added data is not displaying and if we try to add new then it will remove the older one

**Comment by vry-kvl** [comment]
@patel-nimesh - please can you re-verify by adding new food

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220584412-369ac40c-3c36-4e2e-90f0-4406f5091d61.png)

This is working fine
