### ISSUE TITLE
Delete food message design should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#212]
![image](https://user-images.githubusercontent.com/121149500/215939884-2f43e486-ed99-465c-a42a-b3227b576545.png)

From the food dashboard if we delete any food then the message design should be proper

**Comment by kaushikpokal** [comment]
@vry-kvl  Add class **wpfm-alert wpfm-alert-danger**

**Comment by vry-kvl** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/119648390/218049181-09a7be43-f468-4cf1-aed7-a6c0309e73a5.png">

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218058941-6419522e-e4c7-41c2-9ee1-f8ae0bbbc9be.png)

Now delete message displaying properly
