### ISSUE TITLE
Food dashboard duplicate is not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#214]
![image](https://user-images.githubusercontent.com/121149500/215965240-25bf9b3d-88f6-40fb-af80-2b53b4a03cf4.png)

From the food dashboard if we duplicate food then it is not creating any duplicate food and will display a message like " Missing submission page."

**Comment by vry-kvl** [comment]
@patel-nimesh - please can you verify again.
I am checking to duplicate food, it is working properly.

**Comment by patel-nimesh** [comment]
This is working fine so I am closing this issue
