### ISSUE TITLE
Plugin setup steps link should be redirecting to proper page

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#218]
![image](https://user-images.githubusercontent.com/121149500/216036154-b82f9da4-e7b1-4fb1-b3b7-03f040d01d2a.png)
![image](https://user-images.githubusercontent.com/121149500/216036214-c8b45e7e-cbc3-434a-8ee0-677e3069524f.png)

![image](https://user-images.githubusercontent.com/121149500/216036365-59725269-468d-4af8-b4a3-7e2a3aefb0e7.png)
![image](https://user-images.githubusercontent.com/121149500/216036540-6fef044c-257f-4bcf-babc-51a874f34b85.png)

![image](https://user-images.githubusercontent.com/121149500/216036745-22d81fbf-5113-40c0-a0b9-3b37c605bb1e.png)
![image](https://user-images.githubusercontent.com/121149500/218025475-22f5f7dd-7bfd-42ee-a476-0c4c62db407a.png)

Please change the appropriate link to the keywords in setup steps (all 3 steps)

**Comment by vry-kvl** [comment]
@patel-nimesh - This changes allready make by me.

Can you please confirm it, by checking again.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218641557-5cbdc1ed-bdc1-4c5f-a2a9-4520076e2691.png)
![image](https://user-images.githubusercontent.com/121149500/218641584-1bbcbac2-fd9f-4c29-89d0-f53284f888f6.png)
![image](https://user-images.githubusercontent.com/121149500/218641697-dfccbddf-a4bf-4c65-a701-a04c3a059981.png)

Setup steps all links are updated
