### ISSUE TITLE
Adding food displaying error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#219]
Warning: Undefined array key "_option_required_1" in D:\wamp64\www\food\wp-content\plugins\wp-food-manager\admin\wpfm-writepanels.php on line 1460

![image](https://user-images.githubusercontent.com/121149500/216229750-e14a9df6-012c-4975-89b0-67b6a471c0cd.png)

Warning: Cannot modify header information - headers already sent by (output started at D:\wamp64\www\food\wp-content\plugins\wp-food-manager\admin\wpfm-writepanels.php:1460) in D:\wamp64\www\food\wp-admin\post.php on line 231

![image](https://user-images.githubusercontent.com/121149500/216229873-acaab4ab-025c-4218-b1aa-5ff02d119c85.png)

**Comment by vry-kvl** [comment]
@kushang-tailor - Please can you check this error? Because this happens when an online order is active.

**Comment by kushang-tailor** [comment]
Hello @vry-kvl ,

I have fixed this issue from my end. So, Now please check on your end and mark as resolved this issue.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
I have checked from the both side front and backend side by adding foods . And also updating the foods now no error is displaying

This issue is solved
