### ISSUE TITLE
Food dashboard In mobile view design should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#220]
![image](https://user-images.githubusercontent.com/121149500/216519667-5ed4f6ea-c342-4887-88de-10dc12a62f09.png)

In responsive mode on food dashboard page message and filter click fields design is not proper

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217999172-c17986a7-6b4c-48d9-bccd-5377a70f53be.png)
Still Message is not looks proper

**Comment by patel-nimesh** [comment]
@vry-kvl as per the designer this is developer issues. So Please check this issue

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/218464576-51f45aa2-b1df-48fe-9fa1-c923acdf7d4a.png)
![image](https://user-images.githubusercontent.com/119648390/218464610-a5f0a66f-e45d-4bf4-a8d7-92866b55d968.png)
![image](https://user-images.githubusercontent.com/119648390/218464661-3695ba1c-789c-48c4-a2e6-d906395a289b.png)

@patel-nimesh - please check, I have checked in all devices, can you please confirm it?

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218642171-fba8952e-5429-4d91-b182-0ace8d361d60.png)
![image](https://user-images.githubusercontent.com/121149500/218642185-d0b49482-7343-4f8c-affc-13533ef1e779.png)

Now the message is looks proper
