### ISSUE TITLE
Installation process not working correctly.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#221]
Reproduce bug stapes.

1. First of all install the fresh WordPress.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/35419531/216795493-52bf6564-2627-4772-88ec-46ec5bf9dcf8.png">

2. Click on Activate button of WP Food Manager

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/35419531/216795562-934a4c12-5dfb-4865-8da0-2b3aba070d7f.png">

3. Now you can see WP Food Manager Setup. ( Don't do anything here )

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/35419531/216795593-25e4c5eb-d43a-46ea-b2f8-bd32bdfe1f93.png">

4. Click on back button of browser or you just need to come back of the browser. 
5. You can see the plugin was activated and there is no any page was created.

If any user come back directly without completing the stapes plugin should not be activate.

**Comment by vry-kvl** [comment]
@krinaydhanani - This is not the appropriate restriction, because this will be more complicated for us to move further.
Soo many issues will occur on activation of the plugin. and also I checked plugins like woocommerce,elementor, etc.
This type of restriction is not a proper way to implement it.

**Comment by krinaydhanani** [comment]
If WooCommerce and other addons provide same installation stapes method then we have to follow this wordpress by default method.

**Comment by patel-nimesh** [comment]
This is default process.
