### ISSUE TITLE
Wrong documentation redirection link in Introduction setup step. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#222]
**Wrong documentation redirection link in Introduction setup step.** 

When I click on documentation it will redirect me to food manager site home page but it should redirect me to correct documentation page in food manager site.

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/35419531/216795826-d5b4d747-1544-4e1f-9b60-7f07675d1577.png">

**Comment by vry-kvl** [comment]
Currently we don't have the documentation link and also in second step there is shortcode keyword which is redirected to knowledge-base page. I made changes that.

Soo I have set url of knowledge-base.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220891584-fff64a7c-7ea8-4156-adf2-9c62812bd607.png)

URL is redirecting to Knowledge base
