### ISSUE TITLE
Wrong information text showing in second line at Introduction page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#223]
We are not creating food type, food management, Ingredients and Nutritions pages.

Current notice text : - This setup wizard will help you get started by creating various pages for food type, food management, and listing your foods, along with setting up Ingredients and Nutritions pages.

Please write correct notice we are creating only 3 pages.

- Food Listing
- Add Food
- Food Dashboard

**Comment by vry-kvl** [comment]
I have replace to 'This setup wizard will help you get started by creating various pages for listing your foods, food dashboard and add food along with setting up Ingredients and Nutritions.'

@patel-nimesh - please verify, This line is proper or not.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220250201-7b028c91-c022-4430-9a6a-e3f17fcb35c5.png)

First step content is proper but need to make proper in step2 

![image](https://user-images.githubusercontent.com/121149500/220250285-ee698f77-b328-4783-a63d-a4c1767f5dc7.png)

**Comment by patel-nimesh** [comment]
This issue is done the another will be cover in #224 

So I am closing this issue
