### ISSUE TITLE
Wrong information text showing in second line at Setup page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#224]
Add Food page description text should be **add foods** not **post foods**.

Current information text : - This page allows peoples to post foods to your website from the front-end.

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/35419531/216796298-336d235e-0f92-4c02-84ed-ba68a13b279e.png">

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218058311-751e77b8-076b-42e6-86eb-0884100045c8.png)

The Page title should be: Add Food
The text should be changed in description:- post foods to Add Foods

**Comment by vry-kvl** [comment]
As per discussion with @krinaydhanani, the post title is 'add foods' and the description sentence is 'This page allows people to add foods to your website from the front-end.'

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220550351-0571d3dc-3fa7-4c0f-931c-d670495fbd83.png)

Now the add food is displaying
