### ISSUE TITLE
Wrong redirection link in Page Setup page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#225]
**Wrong redirection link in Page Setup page.**

Shortcode URL redirect me to the home page of the site rather then correct documentation shortcode page.

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/35419531/216796037-61e47056-2706-4d73-8e29-fd18b4ab6bdb.png">

**Comment by vry-kvl** [comment]
@krinaydhanani - We don't have the shortcode documentation page soo,I have change redirection to knowledge-base page.

**Comment by krinaydhanani** [comment]
We need Short page for the Knowledge base.  

@patel-nimesh Please prepare below short code description with @Prachetshi1991  

1. Food Listing 
2. Food Dashboard 
3. Add Food 
4. Single Food Listing

**Comment by patel-nimesh** [comment]
I have done Three KB
1.Food Listing https://wpfoodmanager.com/knowledge-base/the-food-listings/
2.Food Dashboard https://wpfoodmanager.com/knowledge-base/the-food-dashboard/
3.Add Food https://wpfoodmanager.com/knowledge-base/the-food-submission-form/

For the Single Food Listing the shortcode is not working and for that need to develop this thing
