### ISSUE TITLE
Wrong redirection link in Setup Done page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#226]
In the 3rd step of the page it will redirect me to home page of the site rather then correct targeted page.

Redirect Knowledge Base page to the https://wpfoodmanager.com/knowledge-base/ page.
Redirect FAQs Base page to the https://wpfoodmanager.com/faqs/ page.
Redirect Support page to the https://wpfoodmanager.com/help-center/ page.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/35419531/216796497-128e5085-32f6-4869-ba00-8aac50dcb201.png">

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218058005-32860f3f-28bb-4ed9-b9f8-17cae55fe34f.png)

Step3 all link are changed
