### ISSUE TITLE
Wrong notice text showing in food listing page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#227]
Right now there is no any food was added in my food manager addon and I can see notice like **There are no foods matching your search.**.

Show this notice when user search something using filter but there is no any result found.

When there is no food in the food listing please show like "There is no food added in food manager add some food for the listing" like that. Please take correct notice word from the @Prachetshi1991 then put it here.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/35419531/216797326-518f6a92-baf7-44a7-b215-d3f0a7893ee9.png">

**Comment by Prachetshi1991** [comment]
There is no food item listed in your food manager.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220249938-85e5a761-1e01-4025-91dc-accd76d208e0.png)

The text is changed when no food item is listed
