### ISSUE TITLE
Admin : Validation field missing in the Filed editor. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#228]
I can see so many fields without validation option.

For example if I want to make Food Category option not required then how can I do it ?

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/35419531/216817895-58d2917c-60c7-4b3e-b037-e0cad7a83d16.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220249459-60e8cdcd-53a5-459b-ac9b-024431536e31.png)

Now the validation field is display for all fields in field editor
