### ISSUE TITLE
Admin : Settings UI should similar like Event Manager.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#229]
I can see all the option in grey colour.

Upper option in Gray color and below option should be in Wight color.

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/35419531/216818097-129028f2-3bb1-4518-b95c-fafe2702d676.png">

Reference WP Event Manager 

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/35419531/216818119-84f27ea3-c89b-46a5-bf0b-20f3361fb4d9.png">

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217999310-31ccfd43-12e0-438f-abb9-e382b4e1695b.png)

UI Issue fixed but need to set helpful resource section

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/219274669-8b8910b1-d1d6-4b36-b9e2-393cae5a19c7.png)

@patel-nimesh - The resource section is there, it just needs to be designed.

**Comment by vry-kvl** [comment]
@kaushikpokal - Please design this section.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220246135-fc698508-0304-418c-a631-f310224c8078.png)

Now the design is proper and same as WPEM
