### ISSUE TITLE
Menu Name corrections

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#23]
Menu Name corrections

Add New -->. Add Food
Food Categories --> Categories
Food Types  --> Types
Food Ingredients  --> Ingredients
Food Nutritions --> Nutritions
Food Menus --> Menus

<img width="173" alt="Screenshot 2022-08-19 at 10 18 42" src="https://user-images.githubusercontent.com/15089059/185576055-7e081dc7-6bdd-4a6a-bb21-f89c49f730de.png">

**Comment by mistry-jignesh** [comment]
Verified this issue. Now menu name is changed.

![image](https://user-images.githubusercontent.com/75515088/191957144-3206ca29-b776-48b5-aaaa-c393f97474d5.png)

So I closed the issue
