### ISSUE TITLE
Admin : Settings Helpful Resources section was missing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#230]
I can not see Helpful Resources section at admins side.

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/35419531/216818177-36be58b0-120a-4bbf-a6e3-76a84ed6ab7d.png">

Reference : -

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/35419531/216818190-4d468084-2231-4117-a1d6-8926b009bf4a.png">

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/218463833-d4fded52-4578-4bf0-a99b-ba461b9be0aa.png)

I have added Helpful Resources section. @kaushikpokal - please can you review this and fix it by your end.

**Comment by kaushikpokal** [comment]
![image](https://user-images.githubusercontent.com/83581741/220085014-e0f1744d-3056-4517-9b40-fd2d845aa751.png)
Logo is a not showing.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220245068-e85a233f-ccaf-4069-961b-b5b22ed610b8.png)

Now section is displaying with proper design
