### ISSUE TITLE
Fronted : Food menu filter missing in food listing page 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#231]
I can not see food menu filter in food listing page.

In the food listing page add one food menu filter from where user can filter out foods. 

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/35419531/216818621-ae0ae2d0-92f4-440f-b9e3-f5100ff04e0e.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
This is not a proper way... By default one menu is selected so Default the foods are displayed as a menu not all foods are displayed.
The filter should be like food category and food menu.
![image](https://user-images.githubusercontent.com/121149500/235051051-e60908cf-5e93-417b-ab93-31e4df33174e.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now this is proper. On front side menu filter is working
![image](https://user-images.githubusercontent.com/121149500/235080435-e6b6561f-0583-4323-bf5b-399cd764e47b.png)
![image](https://user-images.githubusercontent.com/121149500/235080716-185f4558-9b1b-4eaa-be62-39e54a52ec78.png)
