### ISSUE TITLE
Fronted : UI issues in Add food form short code page. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#232]
Please put some space between **box** and **Preview:** button.

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/35419531/216818979-314d3a7c-cd23-49bc-9638-c38715db4fa5.png">

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217999580-cd66a96b-c97b-458d-9f07-f04799551399.png)

Space is given between box and Preview keyword
