### ISSUE TITLE
Fronted : Give correct label in Extra Toppings section in Add Food form.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#233]
1. Option 1 --> Topping Option 1
2. Name --> Topping Name
3. Option type --> Topping selection type. 
( Put **i** symbole and Show the information about this option like how it work and what is the use of this option)
4. Required --> Topping Required 
( Put the **i** symbole and show the description what is the user of this option and field )
5. Description --> Topping Description

<img width="946" alt="image" src="https://user-images.githubusercontent.com/35419531/216819372-e9285437-ac36-439b-8d55-ae5eee700486.png">

**Comment by vry-kvl** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/119648390/218052160-14922af3-b9c2-48fd-9f37-6848b013b86d.png">

I have changed all of the label

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218057139-8a3f29bf-b1d7-45fa-a17a-b7a6ec2e1c7d.png)


All field titles are changed
