### ISSUE TITLE
Fronted : Warning while adding food into the food manager.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#234]
Please fix below warning in Preview page.

Warning: exif_imagetype(http://localhost/wpfm/wp-content/uploads/wpfm-uploads/food_banner/2023/02/pizza.jpeg): Failed to open stream: Connection refused in /Applications/MAMP/htdocs/wpfm/wp-includes/functions.php on line 3263

Warning: file_get_contents(http://localhost/wpfm/wp-content/uploads/wpfm-uploads/food_banner/2023/02/pizza.jpeg): Failed to open stream: Connection refused in /Applications/MAMP/htdocs/wpfm/wp-includes/functions.php on line 3286

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/35419531/216829909-1b34972f-a7bc-4f30-b911-43a5afead5b7.png">

**Comment by ashokdudhat** [comment]
@patel-nimesh  pls test it and if it is working fine then you can close it.

**Comment by patel-nimesh** [comment]
I have checked by both admin and User side food creation and no error or warning occur on add food page

![image](https://user-images.githubusercontent.com/121149500/221751230-d0e45458-e12f-457f-8c63-db4414c7fc5e.png)

Food is creating successfully and after approval by admin it is display properly on food listing
![image](https://user-images.githubusercontent.com/121149500/221751293-6a294207-0513-4abb-a74a-e1bfdd1b106a.png)
![image](https://user-images.githubusercontent.com/121149500/221751381-538e10c4-88f8-4740-8636-6b346cb3c962.png)
