### ISSUE TITLE
Fronted : User can add toping sub options without adding Toping. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#235]
1. Do not allow user to add sub option without entering food option.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/35419531/216830337-58c34750-956d-4984-9ad0-f8e28624229f.png">

2. When user add the food without adding Name and Description and click on Preview button after coming back on Add Food form again it was showing **Option Key**.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/35419531/216830394-60b4a109-3318-4217-8b30-33c501dcb595.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
This issue still occur.

**Comment by vry-kvl** [comment]
As per discussion with @krinaydhanani. for this process topping name & topping description should be required. Soo I make them required.

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220585525-6a20db18-5c5c-455e-94e3-01a5b107f3da.png)
![image](https://user-images.githubusercontent.com/121149500/220585586-bf9e6122-c867-4225-b503-506eb6094d94.png)
![image](https://user-images.githubusercontent.com/121149500/220587084-0d349657-8278-4fa1-9491-14a59e087d53.png)

Now it is displaying validation... Admin side topping name and description is required
