### ISSUE TITLE
Admin : UI issue in pending for approve food count number in Food Manager,

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#237]
Please show **1** number in same line of Food Manager Label text.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/35419531/216832761-0e389bfa-52c4-4e20-9567-943a156e73e7.png">

**Comment by kaushikpokal** [comment]
this is admin style
so we are not fixed it
and this issue also coming our wp event manager

**Comment by patel-nimesh** [comment]
As per the designer they are not able to fix this issue. So I am closing this issue
