### ISSUE TITLE
Fronted : Edit action option missing in dashboard.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#238]
I can not see any edit option on dashboard when Food in under approval.

If any user want to edit food while it's under approval by admin so they can not able to edit.

Provide Edit option in Action.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/35419531/216833323-d529eb43-a12d-4f29-8600-54385978975b.png">

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/217480677-c84f0895-ef4d-4877-9c47-7b2f0d293a5d.png)

I have placed ingredients & nutrition below the description.

@kaushikpokal - please make the section properly.

**Comment by kaushikpokal** [comment]
@vry-kvl  please check this bug and also check what is you update

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220248775-596dff3b-806c-4189-a0aa-eb8a6b8bb1df.png)

Now the edit option will display when food is in under approval
