### ISSUE TITLE
Fronted : Food view count number missing in single food listing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#239]
Food view count number missing in single food listing.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/35419531/216837550-d4e2ed2e-1850-4744-aead-6490da0e1dc5.png">

**Comment by vry-kvl** [comment]
@krinaydhanani - In this case, if food views are more than 1, it will appear in a single food listing. and if admin created the food and then admin opened the food then it will not count as views. other will open that then it will count as a view and then views appear in a single food listing.

**Comment by vry-kvl** [comment]
I have open food in incognito as a user and it will count as a view and then, It will appear like this

![image](https://user-images.githubusercontent.com/119648390/217462402-43ae82a1-f79b-41f1-82be-9f52faff45d3.png)

soo, this is working properly.

**Comment by patel-nimesh** [comment]
First if zero view then not displaying count
![image](https://user-images.githubusercontent.com/121149500/217502638-78c513fb-1af7-4d97-b7b8-596933a776d8.png)

Now I have opened this food in private mode
![image](https://user-images.githubusercontent.com/121149500/217502771-86324ae6-411e-465b-b5b3-d7d091395481.png)

Now check in logged in user the count will display
![image](https://user-images.githubusercontent.com/121149500/217502918-4d23b4fa-42bc-4d20-8386-1438ada00652.png)
