### ISSUE TITLE
General Settings

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#24]
### 2. Data Delete

Delete Data On Uninstall  :  Delete WP Food Manager data when the plugin is deleted. Once removed, this data cannot be restored.

References   : 
https://www.radiustheme.com/docs/food-menu/plugin-settings/general-settings/
https://wordpress.org/plugins/tlp-food-menu/ (Currency)

**Comment by ashokdudhat** [comment]
Hide Food Items. :  Two radio button

Radio 1 :   Completely hide Food Item which has stock status out of stock 
Radio 2 :   Display Out of Stock label for the food item which has stock status out of stock.

**Comment by mistry-jignesh** [comment]
1. Verified Delete Data On Uninstall WP Food Manager functionlaity. This featured is functionality is working fine.
    When I completed  WPFM plugin then data are completed removed. So this follow is working fine.

2.  **Completely hide Food Item which has stock status out of stock**
      ![image](https://user-images.githubusercontent.com/75515088/192207523-b0e9667b-f16d-432a-8a44-8107dda97e78.png)
      Verified above option but this option is not working .Food item are still display backend/frontend. After enable this option.
      So need to fixed this issue.
     ![image](https://user-images.githubusercontent.com/75515088/192207585-db7cc04b-9dc4-4dd4-bb33-86c818d5dd77.png)

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

This 2 options are only worked on frontend food listing page. This options are not for backend. But It is managed from the backend.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now issue is working fine.

As per @KushangDarji - This 2 options are only worked on frontend food listing page.This options are not for backend. But It is managed from the backend.

So I closed the issue.
