### ISSUE TITLE
Fronted : Do not show Category in food dashboard.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#240]
Please remove food category from dashboard. 

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/35419531/216837667-e5bb0792-92d0-444c-ba89-f30d5c20d80c.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217718167-8501a11c-7ec3-4f52-847a-4ffbc2ee6a1c.png)

Category field is removed from food dashboard
