### ISSUE TITLE
Fronted : Food Ingredients & Food Nutritions Show in description.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#241]
Right now **Food Ingredients & Food Nutritions** showing in left column.

Please show it in after food description.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/35419531/216838545-1fcec4a1-90ec-44b2-b38c-337c9858b985.png">

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/220536093-dff1c38c-4d62-4191-afc3-b19d74a92357.png)

@kaushikpokal - please designed this section, I had place nutritions and ingredients below description.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220835480-3d92c715-7af2-441b-b13e-73bff8ae4268.png)
![image](https://user-images.githubusercontent.com/121149500/220835514-a0a3561a-093c-4ff5-b6f8-8e5ec47ea344.png)

Now the Ingredients and Nutrition's are displaying after description and design is looks proper
