### ISSUE TITLE
Extra toping required field not working properly on front side

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#242]
![image](https://user-images.githubusercontent.com/121149500/216895500-4ee7078a-8144-4cbc-affa-f6e07d167290.png)

In extra topping if the field is required and we add all content then also it is displaying validation message

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify again, this is allready fixed when this functionality updated.

**Comment by patel-nimesh** [comment]
It is working proper
