### ISSUE TITLE
Parent option should not be their for category,types,Ingredients,Nutritions and Unit 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#245]
![image](https://user-images.githubusercontent.com/121149500/217143976-a2305713-6961-4723-bfc9-8e8ce6b62631.png)

Parent option should not be their for Category, Types, Ingredients, Nutrition and Unit

**Comment by vry-kvl** [comment]
@patel-nimesh and @krinaydhanani - If we will remove parent items on our taxonomy. It is critical to handle it after. Soo these one will as now as.

**Comment by patel-nimesh** [comment]
As per developer it will keep as it is because it is difficult to handle if we remove
