### ISSUE TITLE
Menu adding shortcode use is not clear

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#247]
![image](https://user-images.githubusercontent.com/121149500/217145619-542267c7-212b-44a9-9e19-9274c8fd5d00.png)
![image](https://user-images.githubusercontent.com/121149500/217145691-356d7dde-ed82-4085-9eb6-d63f3c64b102.png)

If we add menu then in admin side it is displaying shortcode.. Now If we enter that shortcode in page then it is not working, So here use of shortcode is not clear

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
It is working . Please copy the shortcode and create a page and use that shortcode in page content. It will display the menu food items on front side page

![image](https://user-images.githubusercontent.com/121149500/220247275-13c97d55-0719-42ad-990a-49211ebb7a5c.png)
![image](https://user-images.githubusercontent.com/121149500/220247298-2370807f-e788-4556-88e6-6241ee3eeb1f.png)
