### ISSUE TITLE
Menu detail page icon tooltip UI is not displaying properly

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#249]
![image](https://user-images.githubusercontent.com/121149500/217146334-caade6e6-86a5-463b-9536-1911b2fd04ef.png)

On menu detail page icon tooltip UI is not proper

**Comment by vry-kvl** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/119648390/218054401-7b97b347-b400-4e2e-a72f-fc1c55970ecf.png">

@patel-nimesh - please verify.
