### ISSUE TITLE
In menu create need some space in category and type dropdown

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#254]
![image](https://user-images.githubusercontent.com/121149500/217149177-4ac0b8d3-2a40-4144-acb0-31b0ffbe3869.png)

In menu create the title should be proper.. right now it is All food ex:- Select the food items from Food category and Food types 

Need some space between category and type selection dropdown

**Comment by vry-kvl** [comment]
@kaushikpokal - please check from your end.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220245819-8889e697-818e-4fb2-b084-ff3a891e3003.png)

Now title and space is proper
