### ISSUE TITLE
All food section in menu should display in 2 column

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#255]
![image](https://user-images.githubusercontent.com/121149500/217150327-3a126adc-4cf8-45e9-9e42-961cd45f71d2.png)

In menu all food section the resulted food should be display in 2 column , Their is more space besides. If resulting food items are more then it will creates ease of use

**Comment by vry-kvl** [comment]
@kaushikpokal - please check it from your end.

**Comment by kaushikpokal** [comment]
If i set 2 column then draggable functionality it's not proper working.

**Comment by patel-nimesh** [comment]
According to designer it will create issue in drag functionality and ordering of the food so it will display in one column as it is
