### ISSUE TITLE
If we do not have active widgets then page should display properly

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#258]
If we have no active widgets in sidebar or not any content then  the page should display as full width

![image](https://user-images.githubusercontent.com/121149500/217154663-e06099f6-9857-44d3-8783-788590d972b0.png)

**Comment by kaushikpokal** [comment]
![image](https://user-images.githubusercontent.com/83581741/217802483-8b5fd1f0-ca73-483a-ac6d-37c83a71933d.png)
 @patel-nimesh Please remove sidebar on customizer check screenshot

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217804118-ad383a50-e7c5-4f02-a123-b1414f0a235a.png)

Need to hide the sidebar from customize.. Now the UI is proper
