### ISSUE TITLE
Food listing search RSS is missing

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#259]
On food listing search RSS is missing while we filter or search any thing.

![image](https://user-images.githubusercontent.com/121149500/217155246-defbd378-9d55-4dfe-8e66-28e82138f299.png)

**Comment by krinaydhanani** [comment]
We need RSS feed because we are going to develop this plugin with Marketplace concept.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
RSS is their but when filter then on RSS it is giving error
![image](https://user-images.githubusercontent.com/121149500/235050502-45b13f9f-ea67-4914-8cd0-6375759f08ae.png)

**Comment by patel-nimesh** [comment]
If search with keyword then it is not working
![image](https://user-images.githubusercontent.com/121149500/235120964-082d9184-eb5d-4a4e-a50f-3078aef0ff4b.png)

**Comment by patel-nimesh** [comment]
Now RSS is working proper

![image](https://user-images.githubusercontent.com/121149500/235151009-d1531442-f3d8-41aa-86eb-f0b684bf123e.png)
![image](https://user-images.githubusercontent.com/121149500/235151069-9bf34a32-bb65-47e2-a5b1-a6ab12ff0ed9.png)
