### ISSUE TITLE
Food Data Section

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#26]
### Custom Taxonomy

- food_manager_ingredient 
- food_manager_neutrition
- food_manager_unit
- food_manager_tag

Food data will contains the following tab

- General
- Options / Add ons / Toppings
- Ingredients
- Neutritions
- Advanced

**General Tab**

- Regular price
- Sale Price

https://www.radiustheme.com/docs/food-menu/add-edit-food-item/
https://www.radiustheme.com/setup-configure-food-menu-pro-wordpress/#sc-fields

<img width="1278" alt="Screenshot 2022-08-21 at 12 56 29" src="https://user-images.githubusercontent.com/15089059/185787859-312f48f7-600f-4c68-b338-5db486047992.png">
<img width="1302" alt="Screenshot 2022-08-21 at 12 57 05" src="https://user-images.githubusercontent.com/15089059/185787862-c7c3f4e7-7a3f-42a3-9392-1236f5c6211d.png">
<img width="1304" alt="Screenshot 2022-08-21 at 12 57 15" src="https://user-images.githubusercontent.com/15089059/185787864-1d3fceda-7987-42d7-a76e-3145ffb9e738.png">

Ref : https://www.youtube.com/watch?v=OPsaBgQyHYA&t=3s
https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/product-addons/

https://wordpress.org/plugins/wp-food/

https://bestellen.dominos.de/menu

**Comment by KushangDarji** [comment]
Hello @krinaydhanani @ashokdudhat Sir,

The Topping section is now Done including frontend and backend view.

Want to discuss with below sheet's plugins and make compatible with WooCommerce.
https://docs.google.com/spreadsheets/d/10g1QwQgDfwfR0FnBuOpjrvk0uRZ_k3_JX_sEZG7rWIY/edit#gid=1344416069

**Comment by mistry-jignesh** [comment]
At backend - 

Food data  : **Ingredient & Nutritions**

![image](https://user-images.githubusercontent.com/75515088/193246680-c06ce9c1-79d3-4772-b207-8a3b4a8492e4.png)

![image](https://user-images.githubusercontent.com/75515088/193246881-d252f11e-a22f-4c9b-a3d6-dc296aa96577.png)

Should not text values in the text box. 

Froent side it is display text value .So need to restrict it.

![image](https://user-images.githubusercontent.com/75515088/193247500-7eb68a4e-d7fa-4659-8501-47484fa16774.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now in the tetx box not allow text values. 

So I closed the issue.
