### ISSUE TITLE
Food listing keyword should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#261]
Food listing category filter keyword should be proper like :- Choose a Category   current text is Select Some Options

Also In food type dropdown the first letter should be capital like Choose a Food Type

![image](https://user-images.githubusercontent.com/121149500/217156876-b244103c-6fba-49e2-bcca-1971f043ce2b.png)
![image](https://user-images.githubusercontent.com/121149500/217156972-82f38bdb-5324-4761-97ca-f938fd74a2a3.png)

**Comment by vry-kvl** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/119648390/218012326-3e688fae-d262-4d5d-8fb4-22d7e88b7286.png">

@patel-nimesh - please verify again.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218648148-281e633d-7f5c-4653-9ab9-1ccdc9e7cd94.png)

Now the keyword is proper
