### ISSUE TITLE
Food detail page food units value click should not display

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#262]
![image](https://user-images.githubusercontent.com/121149500/217160212-9143207e-a699-4428-8bd4-9e7dde990a88.png)

On food detail page in food units on hover link cursor should not display . It should display as normal text not link

**Comment by vry-kvl** [comment]
@kaushikpokal - please make it proper with css, because cursor is come from css.

**Comment by patel-nimesh** [comment]
Now the link cursor is removed from unit
