### ISSUE TITLE
Food category and Type listing design is not proper 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#263]
Food category and type listing page design is not proper. Make it proper like food listing

![image](https://user-images.githubusercontent.com/121149500/217161536-1749a40e-6877-4297-ac9f-468d9663a60b.png)
![image](https://user-images.githubusercontent.com/121149500/217161567-cd7cb596-8d13-493e-93fc-469795b72e17.png)
![image](https://user-images.githubusercontent.com/121149500/217161645-d7d03f85-28e9-458b-a883-dd12714c830e.png)
![image](https://user-images.githubusercontent.com/121149500/217161705-7e6c38a2-6b56-43e5-ad68-bd0108e2f5f8.png)

**Comment by kaushikpokal** [comment]
@patel-nimesh  This is not issue please check our WPEM plugin same

**Comment by patel-nimesh** [comment]
As per the designer it will keep as it is and this is not an issue.
So i am closing this issue
