### ISSUE TITLE
Field Editor remove icon is missing for all fields 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#264]
![image](https://user-images.githubusercontent.com/121149500/217165221-16766083-eefd-4bc1-8303-e8221947ac3f.png)

In field editor remove field button is missing for all fields

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220251659-de4d86b7-f323-4468-91b9-2ed6dd0870e9.png)

Delete icon is displaying for all fields
