### ISSUE TITLE
Field Editor not able to change field Type

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#265]
![image](https://user-images.githubusercontent.com/121149500/217165615-88914838-bba0-4f99-85cc-2670892e4dbf.png)

In field editor not able to change field types in fields... Please check the fields

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220292054-4054a5ec-533e-4e13-b2a4-df2a4e16fbe8.png)

Now fields are editable
