### ISSUE TITLE
Field editor hide banner still displaying dummy placeholder image

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#266]
![image](https://user-images.githubusercontent.com/121149500/217166364-0cca447a-bb2a-4568-9543-50b01987fc9c.png)

If we remove banner from form filed and create food from front side then also food displaying dummy placeholder image

**Comment by vry-kvl** [comment]
@patel-nimesh - Placeholder image means, If there is no image inserted then placeholder image will appear, In any case image

**Comment by patel-nimesh** [comment]
According to the developer @vry-kvl placeholder image will display no need to remove it
