### ISSUE TITLE
Food dashboard filter message UI is not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#267]
![image](https://user-images.githubusercontent.com/121149500/217167072-44c8b221-b926-4ce8-9a75-feaae0d1b4e6.png)
![image](https://user-images.githubusercontent.com/121149500/217167109-b2243a9f-01af-4815-908b-250c3deda0ec.png)

Food dashboard filter if their is no result found then message UI is not proper

**Comment by kaushikpokal** [comment]
@vry-kvl Please add class
**wpfm-alert wpfm-alert-danger wpfm-mb-0**

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/218415963-e2a7e6ff-4fec-49a2-a1af-a073461b8d80.png)

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218646433-4589e1c6-f922-4d2e-9554-078d364fbbea.png)

Now message UI is proper
