### ISSUE TITLE
Food thumbnail can be added from front side

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#268]
If any organizer create a food from front side then not able to add different thumbnail and banner image.. What if organizer want to display two different image same as admin.

From admin can create food thumbnail and banner separately.

![image](https://user-images.githubusercontent.com/121149500/217168816-9d97c6b6-7c64-437f-bff9-e5bdd9af696b.png)
![image](https://user-images.githubusercontent.com/121149500/217168859-bc2b08ac-dd3d-4503-9408-aafa5ddc88df.png)

**Comment by krinaydhanani** [comment]
We have to implement this feature in below way.

Thumbnail : We have to show thumbnail on Food Listing page.
Banner : We have to show banner on Single Food Listing page.

If any user add Food Banner first time then our addon will take it as a Thumbnail as well.
If any user want to change the banner latter then they can edit from the banner latter for the single page listing.

**Comment by vry-kvl** [comment]
Yes @krinaydhanani, This is already working from both ends. If food is submitted from back-end or front-end. Soo thumbnail will take is as food banner. then if admin wants to change the thumbail so he/she can from admin.

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
From the Backend side if we add food and select a thumbnail and banner then it will work accordingly on the front side.

If we add food from the front side then selecting a banner will display as a banner and thumbnail on the front side on the listing and detail page of food.

If users want to display both images differently then they can able to do it from backend side.
