### ISSUE TITLE
Admin Settings menu

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#27]
Admin Settings menus are the following : 

- General Settings

  - Data Delete
  
- Food Listings

  - Listings Per Page
  - Multi-select Categories | Enable category multiselect by default.If enabled, the category select box will default to a multi   
     select on the [foods] shortcode.
   - Multi-select Event Types | Enable event type multiselect by default.If enabled, the event type select box will default to a    
      multi select on the [foods] shortcode.

- Food Submission

(just required settings)
<img width="1185" alt="Screenshot 2022-08-21 at 16 10 55" src="https://user-images.githubusercontent.com/15089059/185795112-3f5a338b-872a-4cf9-98ea-823591855611.png">

- Pages

  - Submit a Food
  - Food Dashboard
  - Foods
  - Food Categories
  - Food Types

- Currency

  - Currency. : Selection Box
  - Currency Position : Selection Box
  - Thousand Separator : Texbox
  - Decimals Separator : Texbox
  - Number of Decimals : Texbox

Need to cover some menu settings from

https://wordpress.org/plugins/food-and-drink-menu/

**Comment by KushangDarji** [comment]
@ashokdudhat and @krinaydhanani Sir,

As per above requirements, I have covered all the required options accordingly. Please check on your end and let me know your thoughts.

**Comment by mistry-jignesh** [comment]
I have verified below tabs.

![image](https://user-images.githubusercontent.com/75515088/192459349-00b89a5b-5de2-4699-982a-8557f5c7e0e4.png)

**Comment by krinaydhanani** [comment]
@KushangDarji You have to setup SMTP in your localhost server environment and verify it new user send pass setting is working or not.

**Comment by KushangDarji** [comment]
Hello @krinaydhanani and @mistry-jignesh ,

I have setup the SMTP on local environment and the Email Functionality is successfully working from my end as per above mentioned points.

**Comment by KushangDarji** [comment]
@mistry-jignesh ,

Regarding below point, **I have created new issue #71 under milestone 1.0.2.**

- Need to cover some menu settings from : https://wordpress.org/plugins/food-and-drink-menu/

**Comment by mistry-jignesh** [comment]
Verified below point using SMTP on the local server.Email Functionality is successfully working fine.

![image](https://user-images.githubusercontent.com/75515088/193198817-9b1e3048-e06e-48ce-b871-8124eea86e9c.png)

As per @KushangDarji - For below pint created new issue. Issue id is #71.

So I closed the issue.
