### ISSUE TITLE
Publish any food should display success message

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#272]
![image](https://user-images.githubusercontent.com/121149500/217174801-e7452444-cb10-4aec-bfac-61589bb65cf7.png)
![image](https://user-images.githubusercontent.com/121149500/217174637-340044e0-4e80-47a1-b463-5ced30b670be.png)

From admin side if we publish or approve any food then it should display success message

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/218394954-76e6d518-5a73-4854-b580-8d2072c47cb8.png)

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218646840-804565f4-af09-4d13-adce-9910e62fdea1.png)

Now the message is displaying
