### ISSUE TITLE
Add food field place holder text should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#273]
![image](https://user-images.githubusercontent.com/121149500/217179850-15fee9f9-0c7c-4e7d-939a-cb1ae2013b0b.png)

From frontside add food fields place holder text should be proper relevant to field title and also make first letter capital

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217716586-584d265a-cfdc-4389-98ce-2b6b4c79b4f3.png)

Make text proper

**Comment by vry-kvl** [comment]
@patel-nimesh - please can you check again.

see the image which I have fixed: 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/119648390/218018179-3886ba1a-afca-438e-b0a5-c4c2d5a30e42.png">

Install the latest plugin please.

**Comment by patel-nimesh** [comment]
Now the text is proper
