### ISSUE TITLE
Food detail page author link should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#275]
![image](https://user-images.githubusercontent.com/121149500/217214232-3fc6f571-6a9a-4aa1-bdf8-3ff8ebe8e797.png)

Food detail page admin link should be proper or remove the link. 

On other user the link is not displaying
![image](https://user-images.githubusercontent.com/121149500/217214593-46e991e1-31a1-4e17-89a5-7e24c7bdcd96.png)

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/217716894-9ccfc70d-33fe-40eb-a668-b31d91167c75.png)

redirecting to blank page...make link proper

**Comment by vry-kvl** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/119648390/218018904-5f39eba3-afee-4ca5-a378-37d811f06917.png">

@patel-nimesh - link is proper but author page is blank, that why you see blank page.

**Comment by patel-nimesh** [comment]
@vry-kvl It is redirecting to shop page. need to make this proper

**Comment by vry-kvl** [comment]
This code is commented as per discussion with @krinaydhanani.
Plugin : /wp-food-manager/templates/content-single-food_manager.php - line no:73 to line no:75

Currently this stuff is not meaningfull like author is not a valid role for food.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220571587-b55d6487-b7d4-48ea-9200-a0b5f4235b04.png)

Now the author will not display
