### ISSUE TITLE
Food listing Multi-select Food Types does not work in any case

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#277]
**Food listing setting their is a option Multi-select Food Types in food listing tab :** 

![image](https://user-images.githubusercontent.com/121149500/217227477-28505edc-279a-4e99-be39-5b7dd9f98fdb.png)

If we enable this option it will allow to select multiple types in filter but their is no result or food will display in that criteria

![image](https://user-images.githubusercontent.com/121149500/217227849-25b0d60b-09a3-4a04-83f1-976c48df671b.png)

Because in food we have provided radio button and allow only one value or food type

![image](https://user-images.githubusercontent.com/121149500/217227993-4ea58efb-88fe-4d30-9247-ad14d8cef704.png)

**Comment by krinaydhanani** [comment]
In multi select term we can not do anything because we are providing flexibility to user they can add food with multi select type and they can list food with multiple selection.

**Comment by patel-nimesh** [comment]
According to the @krinaydhanani sir they give flexibility to user for multi select food category and type so here no need to change anything
