### ISSUE TITLE
Setup steps margin is not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#279]
![image](https://user-images.githubusercontent.com/121149500/217245071-cf73ccc4-e86b-4b4a-8916-1347e0ba9212.png)
![image](https://user-images.githubusercontent.com/121149500/217245203-216625fd-bf25-4729-bfab-d9146ac60f4e.png)

Setup steps margin should be proper from both side

**Comment by kaushikpokal** [comment]
@patel-nimesh issue not reproduce
