### ISSUE TITLE
Admin Settings --> Currency Menu

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#28]
Admin Settings --> Currency Menu

### 1.  Currency

- Currency. :  Selection Box. (default). 
-   Need to set with filter or action hook so it can override with country settings.

**-Conditional Country Box:   It will show when Restaurant add on will install.**

* When user will  install restaurant add on then it will show country mapping options in this section.
* When user will select any country then following all menu will show and user need to select and enter and show. (same like Ingredients box)
* If this option will show then it will override above current option for selected location or set currency for particular location.

- Currency Position : Selection Box
- Thousand Separator :  Texbox
- Decimals Separator :  Texbox
- Number of Decimals :  Texbox

![Food-menu-pro-settings-general-1](https://user-images.githubusercontent.com/15089059/185792670-0a4c803d-8506-46df-ba56-3a9154adfb9f.png)

If there is not any add on installed and using for only own site then above currency will show.

if restaurant add on installed then we have to show currency based on location so restaurant's add on currency setting will override core plugin currency settings or it will act based on location currency settings so we can able create uber eats, zamato etc..

6 columns

- Country : Selection Box. (default Wordpress functional from there pls take it)
- Currency. :  Selection Box  (default Wordpress functional from there pls take it)
- Currency Position : Selection Box
- Thousand Separator :  Texbox
- Decimals Separator :  Texbox
- Number of Decimals :  Textbox

<img width="1647" alt="Screenshot 2022-08-21 at 17 30 09" src="https://user-images.githubusercontent.com/15089059/185798659-fd4aa796-0228-4e19-9953-f16ae256fbd7.png">

**Comment by KushangDarji** [comment]
@krinaydhanani and @ashokdudhat Sir,

I have created and covered this currency options in 5 columns and It is working fine also. Please check and verify it on your end.

**Comment by mistry-jignesh** [comment]
Verified this issue . In the settings >Click on the Currency tab  

Default below option are availabel.

![image](https://user-images.githubusercontent.com/75515088/192507282-833f96f7-8c2d-434c-8692-a951f826775a.png)

This options are working fine.


Currently **Conditional Country Box: It will show when Restaurant add on will install.** functionality may not be coverd .

**Comment by mistry-jignesh** [comment]
As per @KushangDarji - This functionality is working fine. After discussed follow with krinay & implemented it.
Here there is no issue. So now I closed the issue .
