### ISSUE TITLE
How to use or publish the menu on front side?

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#281]
![image](https://user-images.githubusercontent.com/121149500/217430180-c526e019-3989-4308-b48c-2b0ebb682894.png)

How we can publish the menu on the front side? We should mention steps anywhere so can it will be easy to use

**Comment by vry-kvl** [comment]
@patel-nimesh - you can use shortcode highlighted in screenshot below : 
![screenshot-nimbusweb me-2023 02 13-11_49_01](https://user-images.githubusercontent.com/119648390/218385054-b205c05f-fc33-4148-a2de-5fa2769892e7.png)

And you can place anywhere you want.
See the displaying menu screenshot : 
![image](https://user-images.githubusercontent.com/119648390/218385181-5f6dccfa-61a6-4fd3-b841-760dae85bf3d.png)

I have placed shortcode at 'test' name page.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218647856-bc5ead69-9d13-4b8b-b635-13820908e13b.png)
![image](https://user-images.githubusercontent.com/121149500/218647881-9ce9fbb0-8641-44e6-a06c-b35099422bd3.png)

On page using shortcode the menu will display on page
