### ISSUE TITLE
Field editor only for admin missing for fields

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#282]
![image](https://user-images.githubusercontent.com/121149500/217432036-3292c1d1-20ad-447f-b501-eea6c2297aef.png)

In field editor only for admin option (checkbox) missing for some fields

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220252145-8295b567-d184-45a0-90ed-bfeefc8443f1.png)

It is their for all fields
