### ISSUE TITLE
Admin side update any post message text is not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#284]
![image](https://user-images.githubusercontent.com/121149500/217434088-1584c10b-5c71-452d-8c07-38be84bed11b.png)

From the admin side if we update any post type like type, nutrition , tag, unit etc. then the success message displays wrong text as "Go to categories"

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/218378571-888711bf-15da-4f64-ad51-3a1d830c83cd.png)
![image](https://user-images.githubusercontent.com/119648390/218378618-40a2d81b-dff0-4101-92cb-21ffaafb8028.png)
![image](https://user-images.githubusercontent.com/119648390/218378646-7952a356-3d65-45cd-87f3-373b25e8bd72.png)
![image](https://user-images.githubusercontent.com/119648390/218378684-a700f35f-5458-4056-8e8a-53b6c30391b3.png)
![image](https://user-images.githubusercontent.com/119648390/218378712-9cba92f5-bdf1-400b-bc3e-701eb506c24c.png)
![image](https://user-images.githubusercontent.com/119648390/218378729-4ae3321d-6aae-4361-a7ab-d7b74c2a8e6d.png)

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/218647069-af6ae233-b1fe-46db-ab1a-cdd29ed48349.png)
![image](https://user-images.githubusercontent.com/121149500/218647109-0a387ef4-d907-4559-ae04-c6f3f8f373fb.png)
![image](https://user-images.githubusercontent.com/121149500/218647171-5e72335f-e04c-4708-aaec-640f07998576.png)
![image](https://user-images.githubusercontent.com/121149500/218647246-b5296569-58a2-4799-913c-0d125abef811.png)

Now the link and message is proper
