### ISSUE TITLE
Category, Type and Tag page format/UI should be same

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#286]
![image](https://user-images.githubusercontent.com/121149500/217435429-76b3a3eb-b5fe-4a07-9d14-48242cbe5ebf.png)
![image](https://user-images.githubusercontent.com/121149500/217435469-0ac1ea28-7535-4399-99b7-790fefbf229c.png)

![image](https://user-images.githubusercontent.com/121149500/217435493-378c1de7-ccb0-4468-9281-a70b26ee169f.png)
![image](https://user-images.githubusercontent.com/121149500/217435671-58787f0b-58ae-4f81-a386-95fcf4ac8f2b.png)

**Comment by vry-kvl** [comment]
![screenshot-nimbusweb me-2023 02 13-10_52_02](https://user-images.githubusercontent.com/119648390/218377248-c7004b44-1de9-4868-bd8f-675f40e59cd2.png)

Also this is not proper in food category, type, tag lising.

@kaushikpokal - please can you check and fix it.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220248438-f2b51f34-49e4-469d-b8d3-caa98bda024c.png)

As per designer this UI is depend on themes so it will keep as it is
