### ISSUE TITLE
Field editor delete fields not working properly

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#288]
Admin side in field editor if we try to delete the fields then it is deleted but still display in the list and after refresh, it is not displaying

Steps 
1. Create one or two extra fields 
2. Delete any one field from newly added fields
3.You can see that deleted field is still displaying
4. Just refresh the page. You can see the field is deleted and will not display

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
Now the deleting of field is working proper so I am closing this issue
