### ISSUE TITLE
Field editor displaying extra field when we edit or add

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#289]
The field editor is displaying extra fields once we add them.

Steps
1. add a field without entering the name 
![image](https://user-images.githubusercontent.com/121149500/217445833-f55e36a1-d58e-40b8-826f-ab91b153d3f6.png)
2. Enter a name in the title 
![image](https://user-images.githubusercontent.com/121149500/217446053-85d36aac-391d-48ae-a021-268fa12816f6.png)
3. Click on create a field and save changes it will display two fields one is blank and one is with a name with duplicate data like priority, type, etc.
![image](https://user-images.githubusercontent.com/121149500/217446412-addcced2-e503-49ae-a668-8271c6ab54d0.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
Here now without entering field label the field will not create so this issue is not occurring now
