### ISSUE TITLE
Need to set our Food Manager icon

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#29]
Need to set our Food Manager icon

<img width="165" alt="Screenshot 2022-08-28 at 10 37 34" src="https://user-images.githubusercontent.com/15089059/187065379-1483d2ca-4ef4-4356-aeb3-22736ddc8fe1.png">

Something like that related to our logo...

<img width="119" alt="Screenshot 2022-08-28 at 11 21 03" src="https://user-images.githubusercontent.com/15089059/187067018-0a252196-fdd6-4c07-8526-48137f1a87b1.png">

**Comment by kaushikpokal** [comment]
![WPFM - icon](https://user-images.githubusercontent.com/83581741/192531542-c05c199d-bf11-445e-8181-a61b56d2734f.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed .

Now set our Food Manager icon.

![image](https://user-images.githubusercontent.com/75515088/192702084-a63d5e83-376b-470c-afed-2bc56fe2a048.png)
