### ISSUE TITLE
Field editor URL is not changes

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#291]
![image](https://user-images.githubusercontent.com/121149500/217453510-691e2b6c-ca29-4e5c-9458-8e7a918500f5.png)
![image](https://user-images.githubusercontent.com/121149500/217453548-a631a2d0-c9a9-4823-934c-9faf12a3fdea.png)

Field editor URL display the same as Text type

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check again. you can add placeholders like "https://" from admin and URL input is properly in HTML. It would not submit the form without entering the invalid URL.

**Comment by patel-nimesh** [comment]
The validation working fine
![image](https://user-images.githubusercontent.com/121149500/217502039-62ce4776-5902-4a78-bdb6-9a57304adf40.png)
