### ISSUE TITLE
Food Menu : Show food price with currency in food menu.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#295]
We need to show the food price in the food menu so user should know which food they need to select for different restaurant.

**Comment by vry-kvl** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/119648390/234844737-d203b648-270d-4d0a-ab5e-c53ffba09a00.png">

@krinaydhanani - Here already we have shown the food price.
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
The food price is already shown on the food menu with the desired food.
![image](https://user-images.githubusercontent.com/121149500/235050206-a2273ded-baab-4d25-8703-7dc9a5871a90.png)
