### ISSUE TITLE
Default user roles for Food Manager. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#296]
Right now we set **Organiser** role for who add the food in the food manager. 

We have to change it with **Food Owner** who add the food.

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220292909-639e1321-3109-4698-ba5b-ddef0369e270.png)

Role changed to default as "Food Owner"
