### ISSUE TITLE
Organizer info found in code

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#298]
https://github.com/wpfoodmanager/wp-food-manager/blob/master/shortcodes/wpfm-shortcodes.php
<img width="1432" alt="Screenshot 2023-02-17 at 21 07 24" src="https://user-images.githubusercontent.com/15089059/219783132-eb132d94-b560-471b-b89f-6bed8f2930f7.png">

**Comment by vry-kvl** [comment]
@ashokdudhat sir - I have removed the code, and also other removable codes will be clear in the #199 bug.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220523806-775624b3-1f77-4e07-a817-fa175daab16a.png)

In 1.0.2 branch it is solved
