### ISSUE TITLE
After installing WPFM display banner error

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#299]
after installing WPFM display banner error

<img width="1728" alt="Screenshot 2023-02-19 at 11 41 43" src="https://user-images.githubusercontent.com/15089059/219943034-5e69782c-2186-48bf-92c2-459e9decbecf.png">

**Comment by ashokdudhat** [comment]
@patel-nimesh  pls test it and if it is working fine then you can close it.

**Comment by patel-nimesh** [comment]
I have fresh setup and checked this issue and it is display properly, So I am closing this issue

![image](https://user-images.githubusercontent.com/121149500/221749771-008e03cd-d452-453e-8e23-dacdb5841a88.png)
