### ISSUE TITLE
Add options button is not working under Food data meta box.

### ISSUE THREAD

**Issue by KushangDarji** [wpfoodmanager/wp-food-manager#3]
When Creating a new Food post, the 'Add options' button is not working under Food data meta box.

![Screenshot_1](https://user-images.githubusercontent.com/25924876/182295940-076e55b8-ca1c-4575-9f8c-dc20b530f7b1.png)

**When Creating a new Food post, the 'Add options' button is not working under Food data meta box.**

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed & working.

 'Add options' button is working under Food data meta box.

So I closed the issue.
