### ISSUE TITLE
Price Value must be validate and allow only number

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#30]
Price Value must be validate and allow only number.

<img width="799" alt="Screenshot 2022-08-28 at 11 15 03" src="https://user-images.githubusercontent.com/15089059/187066792-e9ad9ecf-23f0-4e06-9bd2-42dfb60c0fc1.png">

**Comment by mistry-jignesh** [comment]
Verified this issue . Now Price value is validate and allow only number. 
Both Front End/back End.

![image](https://user-images.githubusercontent.com/75515088/191959351-bc5dd690-9a66-4092-af36-80fbf997b0fd.png)

So I closed the issue.
