### ISSUE TITLE
Need to use our brand color

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#300]
Need to use our brand color (dark orange as same like logo)  instead of the blue color

<img width="1251" alt="Screenshot 2023-02-19 at 11 43 09" src="https://user-images.githubusercontent.com/15089059/219943111-9a65ee3d-a478-4b55-a766-1bafa403cdf1.png">

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220245296-971ac5c7-a751-4102-a3f1-23c165d793b3.png)

Now the switcher has a brand color
