### ISSUE TITLE
When adding new filed then it show -1 

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#301]
When adding new filed then it show -1 but it should be user friendly there we can display and replace once user will give name of the field right ?

<img width="1728" alt="Screenshot 2023-02-19 at 11 44 59" src="https://user-images.githubusercontent.com/15089059/219943217-16d4c3d8-480c-47b8-b9fc-24db69249383.png">

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/220079005-e58187f3-cb1a-4fa6-9682-dbe0876fa40b.png)

Yes @ashokdudhat, when clicking on Add field button then it should be as above image like -1 which means the slug is null, Once form will be submitted then it should look like the given below the screenshot :
![image](https://user-images.githubusercontent.com/119648390/220080270-c9f09980-a6ee-4159-83af-7f47fd0dda86.png)

**Comment by krinaydhanani** [comment]
@ashokdudhat When ever you will add the field without label our addon will not save the field so there is no issue at all.
