### ISSUE TITLE
Helpful Resource section not designed perfectly

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#302]
Helpful Resource section not designed perfectly. Please research perfectly and do with designer nice way.

<img width="1728" alt="Screenshot 2023-02-19 at 11 46 56" src="https://user-images.githubusercontent.com/15089059/219943289-2516b4ed-4c86-416a-9fc7-9f97ed24d9f8.png">

**Comment by vry-kvl** [comment]
@ashokdudhat - This is already covered in issue no. [#230](https://github.com/wpfoodmanager/wp-food-manager/issues/230).

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220244875-d2f459db-5f9c-4b13-b0d1-118299d0fbd0.png)

Helpful resource section in admin looks proper
