### ISSUE TITLE
Wording is not correct for the General settings

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#303]
Wording is not correct for the General settings

<img width="1101" alt="Screenshot 2023-02-19 at 11 48 24" src="https://user-images.githubusercontent.com/15089059/219943335-72995bc1-1e3d-49b8-963b-719e1b69d2ab.png">

**Current**

**Enable Food Categories** 

Display categories on food.
If enabled, the Food Categories option will display and manage from the both side at frontend and backend.

**It should be**

**Food Categories** 

Display Food Categories.
If enabled, the Food Categories option will display and manage from the both side at frontend and backend.

Something like that or need better way wording.

Also if first letter capital in right side then it should be same for all like

Display Food Categories ( D, F, C .. Capital ) and it same for other options.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check, Updated wording is proper or not.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/221093578-cbc38f67-7b98-4045-93a5-ecfa38a01f4f.png)

Now the words are proper
