### ISSUE TITLE
When click on Menus from admin then it show

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#304]
When click on Menus from admin then it show

<img width="1727" alt="Screenshot 2023-02-19 at 12 11 20" src="https://user-images.githubusercontent.com/15089059/219944286-17eeeb26-1bd3-4c28-b9c2-465807286250.png">

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/220074974-aac7ecc6-ccb8-4487-a3ae-87fe0957e60d.png)
![image](https://user-images.githubusercontent.com/119648390/220075017-e7d8b8b2-ed88-49b5-b9ae-a0ab934e29ec.png)

@ashokdudhat - This also, I think conflicts with wpem. Please see the screenshot of my localhost setup.

**Comment by ashokdudhat** [comment]
Please check it at myeventplatform.com you can get login details from kriny.

**Comment by vry-kvl** [comment]
as per the discussion with @ashokdudhat and @krinaydhanani. This issue is not occurring in version 1.0.2

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/220606400-07281e71-ac60-47d1-b3a4-f1735c0f291c.png)
![image](https://user-images.githubusercontent.com/121149500/220606448-7595bae1-3da9-462c-b975-76ec5add90d5.png)

I am not facing this issue (1.0.2)

**Comment by patel-nimesh** [comment]
I am not facing this issue so I am closing this issue
