### ISSUE TITLE
why this file here wpfm install

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#305]
wpfm-install.php

[wpfm-install.php](https://github.com/wpfoodmanager/wp-food-manager/blob/master/admin/wpfm-install.php)

<img width="1538" alt="Screenshot 2023-02-19 at 16 48 35" src="https://user-images.githubusercontent.com/15089059/219958862-59e6f805-f29a-4843-85e8-a45647ad8195.png">

**Comment by vry-kvl** [comment]
@ashokdudhat - removed from admin.

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
File path is moved to includes
![image](https://user-images.githubusercontent.com/121149500/220252517-5979e89c-ea1b-43bb-aebc-578b031b904e.png)

![image](https://user-images.githubusercontent.com/121149500/220253046-1f4fc4aa-8995-400a-922f-f4737b7f06c7.png)
Checked in 1.0.2 Milestone
