### ISSUE TITLE
Adding food from frontend not working

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#306]
Visitors can add food from frontend but I tried to add food from the frontend but never got it working.

Add food form in the frontend don’t know where the submit button is to add the listing.

**Comment by vry-kvl** [comment]
@ashokdudhat - adding food from the front end is working. Note whether the wpem plugin is installed because wpfm and wpem both conflict with each other.

**Comment by patel-nimesh** [comment]
User can add food by logged in and use Add Foods page
![image](https://user-images.githubusercontent.com/121149500/221750288-85107787-d357-493b-a17e-52b8d48f8d7a.png)

By entering the data into all required fields User need to click on Preview button
![image](https://user-images.githubusercontent.com/121149500/221750489-ae3c290b-7792-4213-8018-0b24aa61f44f.png)

After click on preview button need to click on "Submit Listing" or want to edit then click on "Edit Listing"
![image](https://user-images.githubusercontent.com/121149500/221750578-4e010917-715c-43b8-b3e7-9bec0aec1509.png)

You can see the success message of adding food
![image](https://user-images.githubusercontent.com/121149500/221750722-d028c90b-c042-404a-b74c-b6a0c4c99300.png)

Admin need to approve that food from admin side
![image](https://user-images.githubusercontent.com/121149500/221750793-fd27c956-d963-4c2a-8784-85d5b9173ea5.png)

After approval the food will display on front side as food listing
![image](https://user-images.githubusercontent.com/121149500/221750884-dc48986c-1670-4e48-982a-081ea4d27afd.png)
