### ISSUE TITLE
Class Name problem and need to apply instance properly everywhere

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#307]
We should maintain everywhere same class structure with prefix WPFM

so please rename **class name WPFM_Setup inside admin folder.**

<img width="1370" alt="Screenshot 2023-02-20 at 22 33 34" src="https://user-images.githubusercontent.com/15089059/220201540-3c4fb8d8-dbbd-4605-8fdf-c9e78b47e957.png">

Also please use global variable concept instead of direct calling with object

new WP_Food_Manager_Setup

Use the following so it will not create every time new object because instance method will check if object created then do not create new.

**WPFM_Setup::instance();**

Please see below

/**
	 * Allows for accessing single instance of class. Class should only be constructed once per call.
	 *
	 * @since  2.5
	 * @static
	 * @return self Main instance.
	 */
	public static function instance()
	{
		if (is_null(self::$_instance)) {
			self::$_instance = new self();
		}
		return self::$_instance;
	}

**Comment by vry-kvl** [comment]
@ashokdudhat sir,

I have renamed class names with the prefix WPFM in PHP and JS class files. &
In PHP classes implemented the instance method.

**Comment by krinaydhanani** [comment]
Yes we have fix this issue. we have create **::instance()** for all the class.
