### ISSUE TITLE
 Permalink issues

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#309]
https://www.loom.com/share/1b38ebbf68cd46aa847d45d8d1f4e58a

**Comment by vry-kvl** [comment]
I had tested, and Permalink issues not occurring, @patel-nimesh - please can you verify?

**Comment by patel-nimesh** [comment]
https://user-images.githubusercontent.com/121149500/220533416-952a0280-364a-40bd-9292-adb24523ee23.mp4

Please refer above screencast, In every type of permalink it is working

**Comment by patel-nimesh** [comment]
I have checked with all 5 permalink but not facing issues So I am closing this issue
