### ISSUE TITLE
List of all the Account roles

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#315]
List of all the Account roles and please explained each role in this issue.  (YOU DO NOT NEED TO FIX IN CODE BUT PLEASE LIST HERE AND THEN WE WILL DISCUSS)

I have found some roles duplicates and create problem. please have look in following image.

<img width="819" alt="Screenshot 2023-02-22 at 21 32 53" src="https://user-images.githubusercontent.com/15089059/220752218-9d34c28d-a5b2-43ad-a094-e198992a2203.png">

**Comment by vry-kvl** [comment]
Hello @ashokdudhat sir,
In our wpfm core plugin, We had just add the role name as 'Food Owner' and it is only display. There is nothing use in core plugin., it should be use on online order addon.

**Comment by ashokdudhat** [comment]
We need here two roles 
 

- Food Owner
- Restaurant Owner

**Comment by vry-kvl** [comment]
@ashokdudhat sir, Soo for now we have to change role Restaurant Owner to Food owner. and I did this.

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
1. When we did fresh setup then the default role is " Restaurant Owner"
![image](https://user-images.githubusercontent.com/121149500/223323770-eaea09c7-dd05-43bc-9c3b-9fd62da76ecd.png)

2.Now if any user add any food then his role is " Restaurant Owner"
![image](https://user-images.githubusercontent.com/121149500/223323900-66d64a40-de12-4a8a-81c7-49c27539eb99.png)

So now the default role is changed to " Restaurant Owner"
