### ISSUE TITLE
Single Food listing shortcode is not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#317]
Single Food Listing

If we put single food listing with ID shortcode then it should work

Please refer the event KB

https://wp-eventmanager.com/knowledge-base/the-single-event-listing/

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Add a new page and add a shortcode as [food id="16"] where 16 is the id of the particular food.
Now single food shortcode is working
