### ISSUE TITLE
Topping list showing same like ingredients concept but better way

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#319]
Topping list showing same like ingredients concept but better way. please discuss with krinay.

Need to decide default fields .

https://barn2.com/kb/creating-product-options/

**Taxonomies register**

food_manager_topping

Parent data access level : food_manager_topping
1 level :  Name
1 level :  Options (Array)
               Main Array
                 - Every row will be one array
                 - Every row will be one array

**Comment by patel-nimesh** [comment]
Toppings are added from both front and backend side when food is created and also count is working when add or remove any topping from food

![image](https://user-images.githubusercontent.com/121149500/225868131-9f73b9be-2d69-4469-8374-b9405863914c.png)

**Comment by ashokdudhat** [comment]
DB Side:

topping_name_1
topping_type_1
topping_required_1
topping_description_1

Multiple Rows
topping_options_1

**Comment by ashokdudhat** [comment]
Array
(
    [topping_1] => Array
        (
            [topping_name] => Option 1
            [topping_type] => checkbox
            [topping_required] => no
            [topping_description] => <p>dasdad</p>
            [topping_options] => Array
                (
                    [1] => Array
                        (
                            [option_value_name] => Cheeze 1
                            [option_value_default] => on
                            [option_value_price] => 12
                            [option_value_price_type] => quantity_based
                        )

                    [2] => Array
                        (
                            [option_value_name] => Cheeze 2
                            [option_value_default] => 
                            [option_value_price] => 12
                            [option_value_price_type] => fixed_amount
                        )

                )

        )

**Comment by vry-kvl** [comment]
@ashokdudhat sir,  I changed the array as per our discussion.

Please see : 

`Array
(
    [1] => Array
        (
            [topping_key] => option_1
            [topping_name] => Pepperoni
            [topping_type] => radio
            [topping_required] => yes
            [topping_enable_desc] => 
            [topping_description] => <p>In our top spot, we have pepperoni pizza. For so many Americans, pepperoni is the ultimate pizza topping, and this is primarily because it is a classic.</p>
            [topping_options] => Array
                (
                    [1] => Array
                        (
                            [option_name] => Small
                            [option_default] => 
                            [option_price] => 5
                            [option_price_type] => quantity_based
                        )

                    [2] => Array
                        (
                            [option_name] => Large
                            [option_default] => 
                            [option_price] => 10
                            [option_price_type] => fixed_amount
                        )

                )

        )

)`

**Comment by vry-kvl** [comment]
Also the ingredients storing value is :
meta_key = '_ingredient'
```
Array
(
    [4] => Array
        (
            [id] => 4
            [unit_id] => 22
            [value] => 2
            [term_name] => Cereals and Pulses
            [unit_name] => Gram
        )

    [5] => Array
        (
            [id] => 5
            [unit_id] => 26
            [value] => 4
            [term_name] => Meat
            [unit_name] => Dozen
        )

    [6] => Array
        (
            [id] => 6
            [unit_id] => 25
            [value] => 6
            [term_name] => Seafood
            [unit_name] => KG
        )

)

```

**Comment by vry-kvl** [comment]
Also the nutrition storing value is :
meta_key = '_nutrition'

```
Array
(
    [7] => Array
        (
            [id] => 7
            [unit_id] => 22
            [value] => 3
            [term_name] => Calcium
            [unit_name] => Gram
        )

    [8] => Array
        (
            [id] => 8
            [unit_id] => 23
            [value] => 7
            [term_name] => Potassium
            [unit_name] => MG
        )

    [9] => Array
        (
            [id] => 9
            [unit_id] => 24
            [value] => 9
            [term_name] => Fiber
            [unit_name] => PC
        )

    [10] => Array
        (
            [id] => 10
            [unit_id] => 25
            [value] => 2
            [term_name] => Magnesium
            [unit_name] => KG
        )

)
```

**Comment by vry-kvl** [comment]
@ashokdudhat sir, Here is the final answer for all the meta keys and meta values which is saved to the database.

For Ingredients : 
```
meta_key = _ingredients
meta_value array = Array
(
    [4] => Array
        (
            [id] => 4
            [unit_id] => 22
            [value] => 3
            [ingredient_term_name] => Cereals and Pulses
            [unit_term_name] => Gram
        )

    [5] => Array
        (
            [id] => 5
            [unit_id] => 23
            [value] => 4
            [ingredient_term_name] => Meat
            [unit_term_name] => MG
        )

)
```
------------------------------------------------------
For Nutritions : 
```
meta_key = _nutritions
meta_value array = Array
(
    [7] => Array
        (
            [id] => 7
            [unit_id] => 24
            [value] => 5
            [nutrition_term_name] => Calcium
            [unit_term_name] => PC
        )

    [9] => Array
        (
            [id] => 9
            [unit_id] => 26
            [value] => 2
            [nutrition_term_name] => Fiber
            [unit_term_name] => Dozen
        )

    [10] => Array
        (
            [id] => 10
            [unit_id] => 22
            [value] => 1
            [nutrition_term_name] => Magnesium
            [unit_term_name] => Gram
        )

    [11] => Array
        (
            [id] => 11
            [unit_id] => 25
            [value] => 5
            [nutrition_term_name] => Vitamin A
            [unit_term_name] => KG
        )

)
```

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
For topping refer the below structure

![image](https://user-images.githubusercontent.com/121149500/227194397-c0ce4cf3-e974-4875-a477-c5533c99b201.png)
![image](https://user-images.githubusercontent.com/121149500/227194470-dfbb5b99-df53-4948-8e03-b91d0c734d87.png)

**Comment by patel-nimesh** [comment]
Need to make proper or same structure when add from front and admin side

**Comment by vry-kvl** [comment]
@patel-nimesh - Now, You can see the meta values are same. Please verify and let me know it's work or not.

**Comment by patel-nimesh** [comment]
Now the both side add food structure is proper

![image](https://user-images.githubusercontent.com/121149500/227445019-41d21355-5940-4f62-8930-9d506d0817eb.png)
