### ISSUE TITLE
WP Event Manager notice issue in Food Manager plugin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#32]
Please remove WP Event Manager notice issue in Food Manager plugin.

We have to put WP Food Manager notice.

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/35419531/187241576-e26a7a49-7745-45d5-9415-8f0413cfa629.png">

**Comment by KushangDarji** [comment]
@krinaydhanani,

This notice is arriving from the **Event listing** theme.

**Comment by KushangDarji** [comment]
@krinaydhanani Sir, Please check and close this issue.

**Comment by kaushikpokal** [comment]
Theme path: theme/inc/functions/custom-functions.php 

function event_listing_recommended_plugins()
    {

        $plugins = array(
            array(
                'name' => __('WP Food Manager', 'event-listing'),
                'slug' => 'wp-food-manager',
                'required' => false,
            ),
        );

        tgmpa($plugins);

    }


This is a theme issue 
currenlty we haven't wp food manager theme so now added on event listing theme on above path

**Comment by mistry-jignesh** [comment]
Verified this issue . After adding above code in the the Theme path: theme/inc/functions/custom-functions.php.

WPEM notice is remove . So this issue is working fine.

So I closed the issue.
