### ISSUE TITLE
Need to remove all add ons code from the core.

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#320]
please check wrong code and remove online order code from here.

[wp-food-manager](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2)/[forms](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/forms)/wpfm-form-submit-food.php

<img width="1648" alt="Screenshot 2023-02-24 at 10 51 41" src="https://user-images.githubusercontent.com/15089059/221148496-fad33e1c-b588-4aad-abff-1a3cc7d5d164.png">

**Comment by ashokdudhat** [comment]
1.wp-food-manager\forms\wpfm-form-edit-food.php - Line No.173-292 (Search for wpfm-online-order)
2.wp-food-manager\forms\wpfm-form-submit-food.php - Line No.688-816 (Search for wpfm-online-order)

**Comment by krinaydhanani** [comment]
We have other add-on codes to a particular plugin folder and removed them from here so I am going to close this issue.
