### ISSUE TITLE
need to improve image icons

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#321]
need to improve image icons
<img width="109" alt="Screenshot 2023-02-25 at 12 55 45" src="https://user-images.githubusercontent.com/15089059/221355511-2e6e4b83-443f-4f92-93c3-1678b5a57516.png">

**Comment by patel-nimesh** [comment]
Images are updated

![image](https://user-images.githubusercontent.com/121149500/223339545-341a0527-55a2-4acb-926b-cf612ce229c2.png)
![image](https://user-images.githubusercontent.com/121149500/223339657-be707a93-fe5f-451f-950a-b389cf59842e.png)
