### ISSUE TITLE
Quantity in toppings are not looks proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#322]
In food toppings, the quantity box is added and it is not looks proper

![image](https://user-images.githubusercontent.com/121149500/221483856-eb08ee2f-e21f-4527-8be6-c7dcdaa9ab8c.png)

**Comment by vry-kvl** [comment]
This quantity box is not necessary in the core plugin but Will display when the online order add-on is activated, so I had to remove the code from a core plugin and placed it into the online order add-on.

online order bug no : [#85](https://github.com/wpfoodmanager/wpfm-online-order/issues/85)

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/223351698-72ac55dc-5c6a-43af-81d4-02c129b613ed.png)

Still the quantity is displaying

**Comment by patel-nimesh** [comment]
Please check with other two option as radio box and select box, In this two option still issue arise
