### ISSUE TITLE
Add menu icon list is limited

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#325]
In the admin side if we create a menu then in the menu icon section it is displaying limited icons whereas in older it displays more icons with a scroll

Older
![image](https://user-images.githubusercontent.com/121149500/222064779-1e98a624-2c40-42c2-a9cb-2589941f1fe9.png)

Now
![image](https://user-images.githubusercontent.com/121149500/222064823-5f8e49c6-f274-4574-bb40-8808b38ca1ab.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - I had discussed this with @krinaydhanani And decided that we don't need to load third-party icons like font-awesome, so I have removed third-party icons and just load our custom icons.

**Comment by patel-nimesh** [comment]
As per the discussion only our custom icons will display and we have removed third party icons.

So I am closing this issue
