### ISSUE TITLE
Food Dashboard edit food gives parse error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#327]
When from front side from food dashboard if we edit any food then it is gives parse error

Parse error: syntax error, unexpected token "foreach" in C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\forms\wpfm-form-edit-food.php on line 58

![image](https://user-images.githubusercontent.com/121149500/222094613-c57a14c7-725d-4082-83d5-e9e6b3287bea.png)

**Comment by vry-kvl** [comment]
This issue creates after the code cleaning bug #199. Soo I am fix in this bug.

**Comment by vry-kvl** [comment]
@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
Now from  the food dashboard product is editable

![image](https://user-images.githubusercontent.com/121149500/222628968-31414e50-4fda-4dd9-92cd-12a44dff1b94.png)
