### ISSUE TITLE
change file name

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#33]
wpfm-post-types.php ==> wpfm-custom-post-types.php

wpfm-post-types-taxonomy.php ==> wpfm-custom-taxonomies.php

**Comment by mistry-jignesh** [comment]
Verified this issue. Now file name is changed.

![image](https://user-images.githubusercontent.com/75515088/192273133-13bfc50d-6559-4e37-91c8-a1c4c615a892.png)

So I closed the issue.
