### ISSUE TITLE
Console should be clear

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#330]
In the console it should not display any error. Right now it is displaying a syntaxerror

![image](https://user-images.githubusercontent.com/121149500/222104842-db0f5f48-2799-4e9c-8987-323dd4f6c91b.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - This is allready covered in #199 coding improvement bug. Please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/223329657-ad625799-96d1-4b21-92bc-44b6a46d286e.png)

On food edit page in console display error

**Comment by patel-nimesh** [comment]
Still same issue arise please check again
