### ISSUE TITLE
Multiple Banner image not able to remove

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#331]
In setting enable multiple banner upload and then from front side try to remove image/banner it will not work

![image](https://user-images.githubusercontent.com/121149500/222333059-207ffc02-886e-4b56-8b58-61db9668d8e1.png)

**Comment by vry-kvl** [comment]
This issue occurs due to bug #199.

@patel-nimesh - Soo I have push in that bug.

**Comment by patel-nimesh** [comment]
Now images are able to remove
