### ISSUE TITLE
Front end edit time the new added value remove older one

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#332]
In Front side edit time if we added nutrition's & Ingredients then if add new one it will remove the existing added value

![image](https://user-images.githubusercontent.com/121149500/222407862-6d3a343e-4f3c-42fe-ae8e-563f17b36d2f.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please once, can you save the permalink settings and then you check this issue.

**Comment by patel-nimesh** [comment]
Now on edit time from front end the newly added value is added and previous one not removing

![image](https://user-images.githubusercontent.com/121149500/223326689-511d0b59-6b4b-41b5-a089-314afb9c94ea.png)
