### ISSUE TITLE
Action & Filter Hooks Define Rules

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#333]
We have to make two files for defining action and filter hook inside includes folder. These are following.

wpfm-food-manager-action-hooks.php. (It contains all the action hooks only)
wpfm-food-manager-filter-hooks.php (It contains all the filter hooks only)
"wpfm_" will be always prefix for the action and filter.

**Comment by krinaydhanani** [comment]
We have separate both thing actions and hooks.
