### ISSUE TITLE
Main Post Type for the plugin

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#335]
for adding food , post type  is : **food_manager**

We can also use this post type   **food_listing** but **food_manager** sound can cover listing and manage both.

Currently adding menu  for post type : **food_manager_menu**

**Comment by vry-kvl** [comment]
After discussing with @krinaydhanani sir, food_manager slug for our main CPT is suitable.

So, I am changing this issue's label.

**Comment by krinaydhanani** [comment]
This issue was fixed. I am going to close this issue.
