### ISSUE TITLE
Using dashicons for the menu icons from wordpress

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#338]
Using dashicons for the menu icons from wordpress

<img width="1147" alt="Screenshot 2023-03-03 at 09 16 18" src="https://user-images.githubusercontent.com/15089059/222667984-4b367b41-f96c-483b-a9fe-2a098696ba78.png">

**Comment by vry-kvl** [comment]
We have used WordPress dashicons for the food menu.

@patel-nimesh - Please Verify.

**Comment by patel-nimesh** [comment]
Now more icons are displaying in menu on both menu and using shortcode on page

![image](https://user-images.githubusercontent.com/121149500/224896512-4d1c8f47-e8ed-44dd-8a1e-9e54b049af8e.png)
![image](https://user-images.githubusercontent.com/121149500/224896765-155568bb-56cf-422a-8b79-b09d87bae0a2.png)
