### ISSUE TITLE
Timepicker need to remove or check and use wordpress if need

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#339]
[wp-food-manager](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2)/[assets](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets)/[js](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets/js)/[jquery-timepicker](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets/js/jquery-timepicker)/jquery.timepicker.js

**Comment by vry-kvl** [comment]
Yes, @ashokdudhat sir, We didn't use the time picker in our plugin. Soo I had removed the time picker code from the plugin.

**Comment by krinaydhanani** [comment]
We are using wordpress time picker from now.
