### ISSUE TITLE
Default giving units & Nutritions list 

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#34]
Default giving units & Nutritions list

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue fixed.

Default give units & Nutritions list.

![image](https://user-images.githubusercontent.com/75515088/191961217-14c76ea5-cf86-4674-a4d2-73fc14861baf.png)
![image](https://user-images.githubusercontent.com/75515088/191961288-609bc52c-5e5e-4dd7-a7d3-29199cbe6691.png)

So I closed the issue
