### ISSUE TITLE
Need to check we can use wordpress tooltiip.js or not

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#341]
if we can use it then we can need to remove it

[wp-food-manager](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2)/[assets](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets)/[js](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets/js)/[jquery-tiptip](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets/js/jquery-tiptip)/jquery.tipTip.js /

<img width="1657" alt="Screenshot 2023-03-03 at 09 29 04" src="https://user-images.githubusercontent.com/15089059/222670698-b3e6f0a2-359d-42c2-a315-cd4e7a9090d7.png">

https://jqueryui.com/tooltip/

**Comment by kaushikpokal** [comment]
If you need tooltips for backend then use this class and attribute.
**Class Name** =  wpfm-tooltip
**Attribute** =  wpfm-data-tip

**Comment by vry-kvl** [comment]
Yes @kaushikpokal, I have used our custom tooltip built via css.

Soo Now, We don't need to load tiptip.js and tiptip.min.js, I am removing it and implement our custom tooltip.

@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
In adminside food listing banner tooltip is not displaying, Before it was displaying
Before
![image](https://user-images.githubusercontent.com/121149500/225515807-0ba57444-037c-47a7-8749-3146b38eda33.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - You are right. But Here is not the issue you mentioned. We had just used the tooltip of WordPress. and from the admin side food banner is not need to show the tooltip.

This issue would be verify by @krinaydhanani.

**Comment by krinaydhanani** [comment]
This issue was fixed. I am going to close this issue.
