### ISSUE TITLE
jquery ui folder need to check we can use from wordpress or not

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#342]
[wp-food-manager](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2)/[assets](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets)/[js](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2/assets/js)/jquery-ui/

**Comment by ashokdudhat** [comment]
@vry-kvl can you pls mentioned that which places we are using this ?

**Comment by vry-kvl** [comment]
wp-food-manager/wp-food-manager.php line no : 246 - For frontend use
wp-food-manager/admin/wpfm-admin.php line no : 64 - For Admin use

**Comment by krinaydhanani** [comment]
@vry-kvl Move jquery-ui to css folder.


<img width="871" alt="image" src="https://user-images.githubusercontent.com/35419531/229112580-154e999e-bee2-44d5-ac17-002a3f16160b.png">

**Comment by vry-kvl** [comment]
@krinaydhanani - I have moved **/jquery-ui** to **css** folder.

@patel-nimesh - Please verify it.

**Comment by krinaydhanani** [comment]
We improve the code so I am going to close this issue.
