### ISSUE TITLE
Term taxonomy table displaying same repeated field

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#346]
In database term taxonomy table displaying same repeating field

![image](https://user-images.githubusercontent.com/121149500/223098104-3761b687-ba18-48c1-8005-d699ef9e64ec.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - This is not the repeated field, This is the table that shows that the term => xyz is connected to taxonomy xyz.
In this table, the repeated entry will show the number of terms which is submitted by the user.

This is the use of WordPress.

**Comment by patel-nimesh** [comment]
According to the developer this is not an issue, So I am closing this issue
