### ISSUE TITLE
Multiple banner upload setting is not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#348]
Multiple banner upload setting is not working

![image](https://user-images.githubusercontent.com/121149500/223397673-3a8cc3f7-c2ac-4a88-a451-0038eb38baa1.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - I had double check this issue. I can't get this issue. Please re-verify and let me know.

**Comment by patel-nimesh** [comment]
It is based on field editor to give more freedom to user.From field editor you can manage this so I am closing this issue
