### ISSUE TITLE
Food submission account creation is missing

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#350]
Food submission account creation is missing which not allow to add food which is wrong flow.
Now
![image](https://user-images.githubusercontent.com/121149500/224626907-5631ab8e-b602-4908-a824-937bd3bf98f0.png)

Before
![image](https://user-images.githubusercontent.com/121149500/224626990-95ff6da5-2081-4731-8ed0-db13b5741d59.png)

Front side
![image](https://user-images.githubusercontent.com/121149500/224627027-5175f83a-42ee-4696-9e6a-8c03b776a19a.png)

It should be like
![image](https://user-images.githubusercontent.com/121149500/224627073-938e5f66-cf23-4c1b-a490-0a60575a76a3.png)

**Comment by vry-kvl** [comment]
Yes @patel-nimesh - It Could be done because of code cleaning to remove unused functions.

Please verify it.
Now it is working.

**Comment by patel-nimesh** [comment]
Now the account creation option is displaying and working fine

![image](https://user-images.githubusercontent.com/121149500/225509463-88fd407a-1346-4135-8f19-f4dfc356a8f8.png)
