### ISSUE TITLE
WP Scan 

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#351]
After Installing the Plugin, Go to Food manager option and add an example food.
Now edit the added food and go to Food data -> options / Add ons / Toppings -> Add the following XSS payload in the name field: test"><img src=x onerror=confirm(document.domain)> test"><img src=x onerror=confirm(document.domain)>
Now publish the food, and an alert will trigger. The front-end of the product will also trigger an alert.

As part of our Responsible Vulnerability Disclosure process (that can be found here: https://wpscan.com/vulnerability-disclosure-policy), we expect that you reply to us acknowledging the flaw and provide an estimate of when you believe this fix will be deployed. If we don't hear from you in the next 5 business days we'll contact the Marketplace where your extension is published for appropriate actions.

**Comment by vry-kvl** [comment]
Hello @ashokdudhat sir, I can't get your bug, Please can you re-upload the broken image? To clarify more.

**Comment by ashokdudhat** [comment]
<img width="1399" alt="Screenshot 2023-03-17 at 06 41 41" src="https://user-images.githubusercontent.com/15089059/225822069-609fe968-35bf-4c78-a230-36d1c1a1e0e1.png">

**Comment by patel-nimesh** [comment]
The vulnerability issue is solved in milestone 1.0.4
For example by using this script no popup is displaying on front side
test"><img src=x onerror=confirm(document.domain)>
