### ISSUE TITLE
Food banner is not displaying in admin side

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#352]
If we add/edit food banner from admin side then in food listing the banner is not displaying

![image](https://user-images.githubusercontent.com/121149500/225293867-bd895240-d3fa-4ba0-b4c7-e74339ba67a3.png)

**Comment by patel-nimesh** [comment]
Now this issue is working fine, So I am closing this issue

**Comment by vry-kvl** [comment]
> The issue is happening again please solve the same.

@MahendraShiyal - Please verify again, And let me know this is working or not.
