### ISSUE TITLE
Topping Description Editor is changed

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#354]
Topping add time the topping description editor is changed

Before
![image](https://user-images.githubusercontent.com/121149500/225515492-9513f7a9-f65b-45cb-a2f1-6c7dc14a0937.png)

After
![image](https://user-images.githubusercontent.com/121149500/225515522-269271a1-604b-4c0d-a8ea-36ca358d406d.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now the editor is displaying proper

![image](https://user-images.githubusercontent.com/121149500/225599443-54dc9f47-2323-4bb5-b66c-a4e3e53fa462.png)
