### ISSUE TITLE
Admin side setting and field editor sequence changed

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#355]
Admin side setting and field editor sequence changed

Before
![image](https://user-images.githubusercontent.com/121149500/225515625-e67ff4c7-f4e1-491b-a3f3-1a17b1a9793f.png)

After
![image](https://user-images.githubusercontent.com/121149500/225515660-1aa6e647-1e4f-45b0-bb47-9d3f4d7275d1.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/225561904-30cca3f1-63a0-41da-b2ef-0588392b5cb9.png)

Now the sequence is proper
