### ISSUE TITLE
Display invalid listing message on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#36]
Food Dashboard > Edit any food

Without change .Click on the save changes button.

Here invalid listing message is display on the page.

![image](https://user-images.githubusercontent.com/75515088/191963114-1e9127f5-f4aa-47e0-8e3f-18b89366b415.png)

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

I have checked and verified but I can not regenerate this issue. Can you please Hard refresh the plugin's page at front end. Due to caching issue sometimes it occurred.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed & working fine.

Invalid listing message is not display.

So I closed the issue.
