### ISSUE TITLE
Nutrition is not displaying in add food

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#361]
From frontside if we create food then in nutrition filed it is not displaying nutrition data. Currently displaying category data

![image](https://user-images.githubusercontent.com/121149500/225829458-6c2cf4eb-4d88-4b13-9dc5-8951ea6bae36.png)
![image](https://user-images.githubusercontent.com/121149500/225829553-00233271-eb75-4585-8eb2-47c6f1d95a72.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now the nutrition is displaying properly

![image](https://user-images.githubusercontent.com/121149500/225835634-b91abbd4-2f0b-4031-8163-5f563b88002c.png)
![image](https://user-images.githubusercontent.com/121149500/225835737-b9f890ed-4e8f-436e-a5a0-2efdd07efdcf.png)
