### ISSUE TITLE
Admin side category is autocreate

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#362]
If we create food and add category then in admin side category creating auto as number

![image](https://user-images.githubusercontent.com/121149500/225830495-76082730-b034-4767-a260-dc26d6bc8caa.png)

**Comment by vry-kvl** [comment]
@patel-nimesh -This issue occurs because of issue no: #361.
So that issue is resolved. Also, this is working properly.

please verify.

**Comment by patel-nimesh** [comment]
Now auto category is not create so I am closing this issue
