### ISSUE TITLE
Topping are not displaying in admin side and front side edit food

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#363]
Topping is not displaying in the front side or in admin edit food time.

On food detail toppings are not displaying

**Comment by vry-kvl** [comment]
@patel-nimesh - In this case, options must be filled out by the user, otherwise it will not visible from the front end and backend.

**Comment by patel-nimesh** [comment]
Here need to add all data in toppings.
If options (price) is not added then it will not display So price (options) is mandatory to display this things properly
