### ISSUE TITLE
Spelling mistake in food types

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#364]
In food types spelling mistakes in keywords

![image](https://user-images.githubusercontent.com/121149500/225839585-7654170e-1b1a-430c-a30d-9d41eee64c0d.png)
![image](https://user-images.githubusercontent.com/121149500/225839665-c0f6d060-3bd2-42d1-afe7-64a52ca3e64a.png)

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/225864831-086c34cc-bee1-4a6d-9e6b-44f9f76bc015.png)

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
Now the keywords are proper in food types
