### ISSUE TITLE
Need to change db value and maintain same value for all like Underscore

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#367]
Need to change db value and remove Underscore,

- Ingredient
- Neutrition
- Unit

**Comment by krinaydhanani** [comment]
@vry-kvl Please go with **_repeated_options** column name.

**Comment by vry-kvl** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/119648390/229475381-55ecb0ad-30dd-4059-ad3c-1a4cd73b0697.png">

@krinaydhanani - This is the screenshot after I made changes. Soo here is the total meta per 1 food. Please review it.

And I have replace meta_name **_toppings** into **_food_toppings** and **wpfm_repeated_options** into **_food_repeated_options**

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Still In database the meta filed title is not proper for nutrition and ingredients

![image](https://user-images.githubusercontent.com/121149500/229482438-6a42725c-903c-4287-8e9e-8d68f01b96c2.png)

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/229707444-d04b3957-5aeb-4f39-98c5-1748881a99e7.png)

Term meta need to make proper
![image](https://user-images.githubusercontent.com/121149500/229707650-3b9dc604-e195-499b-a3da-eb8c2f93edf2.png)

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/232680305-aebe4a38-d443-4826-82ef-39eb2095bde7.png)

Also in termmeta, it has been maintained by an underscore ( _ ).

@patel-nimesh - Please Verify it.

**Comment by patel-nimesh** [comment]
As per discussion with @krinaydhanani the view count (_view_count) is okay.

And term meta is also display in database as underscore
![image](https://user-images.githubusercontent.com/121149500/233029111-6c995ae0-203a-4cbd-a904-aa18db1019c0.png)

Please refer to the below Screenshot for the all field save in databse
![image](https://user-images.githubusercontent.com/121149500/233029351-98160211-08da-4191-8c2c-4af02fcd4a77.png)
