### ISSUE TITLE
When making any option from the topping side admin only extra topping front end side gives error

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#373]
When making any option from the topping side admin only 

extra topping from front end side give error 

![Screenshot 2023-03-23 110945](https://user-images.githubusercontent.com/126650948/227113857-bb23418d-a24a-4e60-8ff7-213060319434.png)

**Comment by patel-nimesh** [comment]
Please check with delete the name field for topping.
Warning: Undefined variable $first_key in D:\wamp64\www\wpfm\wp-content\plugins\wp-food-manager\forms\wpfm-form-abstract.php on line 254

![image](https://user-images.githubusercontent.com/121149500/227117647-5c2f1a69-a841-45cb-b97f-082747d0bb30.png)
