### ISSUE TITLE
Remove food units from detail page

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#375]
Remove food units from detail page

![image](https://user-images.githubusercontent.com/121149500/227180789-c0341009-7c30-4d68-9a2b-189794116f3d.png)

**Comment by patel-nimesh** [comment]
Rearrange Food types, Food category and Food tags on food detail page.

Order like:- Food Category, Food Types and Food Tags

![image](https://user-images.githubusercontent.com/121149500/227184602-0b373cc5-8f1a-4809-9257-4d5376049550.png)

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/227199697-40d38d4b-a374-4c8d-8725-121ae3cc8110.png)

@patel-nimesh - please verify.

**Comment by patel-nimesh** [comment]
Now Food Units is removed and Sequence change as per the krinay sir information

![image](https://user-images.githubusercontent.com/121149500/227201308-24706463-1762-42d5-bd63-3e3392a525e5.png)
