### ISSUE TITLE
Food price, View icon style should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#376]
Need proper format for price , view icon etc. Make proper style

![image](https://user-images.githubusercontent.com/121149500/227184996-81168b11-fccf-47c8-a9dc-47a9e2d051a1.png)

**Comment by harsh-dhanani** [comment]
Issue fixed

**Comment by patel-nimesh** [comment]
The food view icon position is changed. Please refer the below screenshot for the latest design

![image](https://user-images.githubusercontent.com/121149500/233323267-812cb275-3058-4f08-92ba-82afc4283144.png)
