### ISSUE TITLE
Front side edit food topping title and description and other data is not displaying

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#377]
If we edit food from frontside then the topping value (title , description, selection type and required ) is not displaying.

![image](https://user-images.githubusercontent.com/121149500/227195350-c72c6b3e-a25d-4ba9-819f-aadfa0191a14.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now the given value in toppings are displaying

![image](https://user-images.githubusercontent.com/121149500/227469748-779b9ac5-4bd5-4d4d-9640-c8f0bc36d951.png)
