### ISSUE TITLE
Admin side add/edit food displaying Fatal error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#378]
From the admin side if add/edit food then it is displaying a fatal error

C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\includes\wpfm-action-hooks.php on line 1011

![image](https://user-images.githubusercontent.com/121149500/227422660-99a791d7-7fc3-4b49-abc0-9c7747eae50d.png)

**Comment by patel-nimesh** [comment]
Also setup time in debug log it is displaying warning in debug log

PHP Warning:  foreach() argument must be of type array|object, null given in C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\includes\wpfm-action-hooks.php on line 2115

PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\includes\wpfm-action-hooks.php:1011

[debug.log](https://github.com/wpfoodmanager/wp-food-manager/files/11058333/debug.log)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now Food are able to add/edit from admin side and no error is displaying
