### ISSUE TITLE
Admin : Improve Food manager pages at page setup.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#380]
Correct menu should be : 

- Foods 
- Add Food 
- Food Dashboard 

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/35419531/227562988-00ba68e0-fb72-45f0-9de9-616553f3fb00.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now the page changed to add food and also order changed for pages

![image](https://user-images.githubusercontent.com/121149500/227853331-94f9e398-aa22-4bab-9a57-39f2a467c6a7.png)
