### ISSUE TITLE
Admin : Default Food Topping missing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#382]
Same as for food type and the category we have to provide food toppings as well. So we have to add the below-listed topping. When user will install Food manage they will get default toppings.

**Food Topping**

- Yellow mustard
- Relish
- Vinegar
- Wasabi
- Hot sauce
- Dijon mustard
- Mayonnaise
- Ketchup
- Barbecue sauce
- Soy sauce

**Comment by vry-kvl** [comment]
@krinaydhanani - Please see the screenshot :
![image](https://user-images.githubusercontent.com/119648390/227847596-0a91f46b-d38c-4cdf-84fb-56f7219273ba.png)

@patel-nimesh - Please verify.

At the time on installing the plugin this default toppings will created by-default.

**Comment by patel-nimesh** [comment]
Yes the default toppings are added but their is no use of this without the other data on front or backend side

![image](https://user-images.githubusercontent.com/121149500/227855063-104e9deb-10ba-4a14-aa0d-fc149369de3f.png)
![image](https://user-images.githubusercontent.com/121149500/227855208-d8120d66-42d1-42c6-b1d2-d5c59d0ec1c6.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Yes, You are right but, Here we can add default toppings that user can get idea which types of toppings does exist and how to use it.

**Comment by patel-nimesh** [comment]
According to the developer topping name just created by default. Other data like topping required, type and description will be entered by the user at add/edit food time
