### ISSUE TITLE
Frontend : Preview label visibility issue. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#383]
Please show the Preview label once the user will add or select an option.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/35419531/227596776-d03d4640-6a76-42ed-a5dd-fd957b3f6732.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now the preview text is display when add value. Also on edit time it will display if their is a value added

![image](https://user-images.githubusercontent.com/121149500/228128810-68528ce9-0ee0-4529-afd3-3cb4f2c204da.png)
![image](https://user-images.githubusercontent.com/121149500/228128930-5522faf4-b752-4620-b28b-04d83421e8bb.png)
![image](https://user-images.githubusercontent.com/121149500/228129014-7a574cee-c82b-4903-9947-eead05bc2539.png)
