### ISSUE TITLE
Fronted : Invalid file type notice text improvement.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#384]
We have to improve the notice text of the Invalid file type. Write it properly with a proper message.

@vry-kvl If you need @Prachetshi1991  help then you can take her help.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/35419531/227732423-09236f37-097a-4a57-806b-6fadcaeee811.png">

**Comment by Prachetshi1991** [comment]
The file type you have mentioned is invalid

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now when upload file type as pdf,zip etc then the message will display as below
![image](https://user-images.githubusercontent.com/121149500/229745676-35776959-c6a6-450c-b211-10de4ffab5fe.png)

If upload webp or other file type then it is displaying message as below
![image](https://user-images.githubusercontent.com/121149500/229745823-d9aea74f-3360-44f6-8277-b4a07adda003.png)
