### ISSUE TITLE
General : WPFM is not allowed .webp file type.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#385]
When I am trying to upload **webp** image I can see the below notice from the addon.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/35419531/227732826-e652c98b-ec51-4443-98cc-6992da3edd48.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify whether WordPress is allowed .webp file type or not, Soo this bug nothing has to changed.

**Comment by rashmipsingh** [comment]
@patel-nimesh I am not able to replicate this issue because it already resolved. Please check and let me know.

**Comment by patel-nimesh** [comment]
Webp file is working from adminside or frontside both side. In both side food creation webp type image working properly
![image](https://github.com/user-attachments/assets/e60a6a46-40a0-465f-9a80-f7101c31adcf)
![image](https://github.com/user-attachments/assets/6ff9b965-159b-4434-b9d9-b43ca3059219)
