### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#386]
### [wp-food-manager](https://github.com/wpfoodmanager/wp-food-manager/tree/1_0_2)
/wp-food-manager-functions.php

found many function with prefix 
```
	function wp_food_manager_  (that is wrong )
        function wpfm_ (this is correct)
```
why some function with below name ?

food_manager_generate_username_from_email
food_manager_user_requires_account
food_manager_user_can_edit_pending_submissions 
food_manager_get_page_id
get_food_manager_currencies
 food_manager_user_can_upload_file_via_ajax
etc...

### wp-food-manager-template.php

Some of functions name not started with prefix with wpfm_

**Please always put @since at down , not at top** 

/**
 * Get and include template files.
 *
 * @ since 1.0.0
 * @param mixed $template_name
 * @param array $args (default: array())
 * @param string $template_path (default: '')
 * @param string $default_path (default: '')
 * @return void
 */
function get_food_manager_template($template_name, $args = array(), $template_path = 'wp-food-manager', $default_path = '') {
	if ($args && is_array($args)) {
		extract($args);
	}
	include(locate_food_manager_template($template_name, $template_path, $default_path));
}

 **@version 1.0.2  will not come.....**  

/**
 * Template Functions
 * Template functions specifically created for food listings and other food related methods.
 *
 * @author WP Food Manager
 * @category Core
 * @version 1.0.2
 */

/**
 * Returns the translated role of the current user. If that user has
 * no role for the current blog, it returns false.
 *
 * @return string The name of the current role
 * @since 1.0.0
 */
function get_food_manager_current_user_role()

### uninstall.php

'food-manager-setup',

Never will come '-'  but always us '_' (underscore)

### WPFM_FilterHooks

**Need to discuss that why some function name with prefix with wpfm_ and why not some name ?**

// Writepanel's filters
        add_filter('manage_food_manager_menu_posts_columns', array($this, 'set_shortcode_copy_columns'));
        add_filter('manage_edit-food_manager_columns', array($this, 'columns'));
        add_filter('manage_food_manager_posts_columns', array($this, 'set_custom_food_columns'));
        add_filter('manage_edit-food_manager_sortable_columns', array($this, 'set_custom_food_sortable_columns'));
        add_filter('post_row_actions', array($this, 'row_actions'));

        // wpfm custom post-types
        add_filter('the_content', array($this, 'food_content'));
        add_filter('the_content', array($this, 'food_menu_content'));
        add_filter('archive_template', array($this, 'food_archive'), 20);
        add_filter('use_block_editor_for_post_type', array($this, 'wpfm_disable_gutenberg'), 10, 2);
        add_filter('wp_insert_post_data', array($this, 'fix_post_name'), 10, 2);

        // wpfm functions
        add_filter('upload_dir', array($this, 'wpfm_upload_dir'));
        add_filter('wp_terms_checklist_args', 'wpfm_term_radio_checklist_for_food_type');
        add_filter('manage_edit-food_manager_type_columns', array($this, 'wpfm_display_custom_taxonomy_image_column_heading_for_food_type'));
        add_filter('manage_edit-food_manager_category_columns', array($this, 'wpfm_display_custom_taxonomy_image_column_heading_for_food_category'));

        // wpfm core file
        add_filter('pre_option_wpfm_enable_categories', '__return_true');
        add_filter('pre_option_wpfm_enable_food_types', '__return_true');

### wpfm-action-hooks.php

Either use $this or  add_action('init', array(__CLASS__, 'add_endpoint'));
      add_action('food_manager_ajax_get_listings', array($this, 'get_listings'));

**Comment by vry-kvl** [comment]
### Before
**Function** name starts with **wp_food_manager_**
### After
**Function** name starts with **wpfm_**

 - Every function in the entire plugin have not to prefix wp_food_manager_

---------------
@Version 1.0.2 will not come
- From every function version is removed.

---------------

Changed this word **'food-manager-setup**' into **'food_manager_setup'**.

---------------

Now using **$this** where we have used **'CLASS'**.

---------------

-Need to discuss that why some function name with prefix with wpfm_ and why not some name ?

For this point :
For this I have make changes like under the class method is used will no need to start prefix with wpfm_
Soo, I had remove wpfm_ from some functions.

---------------

And the @since is at the down of comment.

---------------

@ashokdudhat sir, I have made this changes mentioned above.

**Comment by krinaydhanani** [comment]
We improve the code so I am going to close this issue.
