### ISSUE TITLE
Fronted : Notice text improvement. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#387]
Current notice : Your Food was added successfully in Food Manager. Your listing will be visible once approved by the admin.

Suggest : Your Food was added successfully in WP Food Manager. Your listing will be visible once approved by the admin.

@Prachetshi1991 Please improve the suggested text.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/35419531/227733921-eac4c005-b6a7-4508-b9b7-2bd7cf60cce8.png">

**Comment by Prachetshi1991** [comment]
Your food has been successfully added to WP Event Manager. Your food listing will be visible after the admin's approval.

**Comment by vry-kvl** [comment]
![image](https://user-images.githubusercontent.com/119648390/227850627-bba349a0-6c8b-4754-b463-ed26f7f0702a.png)
-Improved notice text

@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now the notice has been changed

![image](https://user-images.githubusercontent.com/121149500/227851156-90a77719-e06a-4c24-a41c-6cbf23bc2ae1.png)
