### ISSUE TITLE
Admin : Food menu icon UI listing hight issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#390]
We have to fix the menu height for menu icons so it will not go long. 

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/35419531/227775873-b0bf595e-8d22-4d94-aa9c-2b81e15e355c.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now the scroll bar added

![image](https://user-images.githubusercontent.com/121149500/229482138-c299056b-ba8f-4f9d-8ef8-2d0f0fccf8ec.png)
