### ISSUE TITLE
Admin : Food listing type and category selection issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#392]
**Issue :** 

As you can see below screenshot there is no food on the menu but still, it's showing 1 in Vegetarian. 

Show the select box with filter because when user deselect all option above filter shoud be clear.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/35419531/227777758-c6a97613-47e8-41de-982a-251f64ec4565.png">

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
Now if remove all then it will clear the filter. But when we save with the filter then in dropdown the selected filter will not display. It will display as default as per the below Screenshot

![image](https://user-images.githubusercontent.com/121149500/228134360-c2cfe7ac-6084-49c9-b887-2d7cd58d64d5.png)
