### ISSUE TITLE
General : Need to add more default value of the Nutrition

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#394]
Currently we have the following list of vitamin

'food_manager_nutrition' => array(
				'Calcium',
				'Potassium',
				'Fiber',
				'Magnesium',
				'Vitamin A',
				'Vitamin C',
				'Vitamin E',
			),

Need to add this all the following vitamins

<img width="1040" alt="Screenshot 2023-03-26 at 16 54 18" src="https://user-images.githubusercontent.com/15089059/227784206-eeb97f6c-164d-4003-9266-e20b12de5410.png">

Reference link : https://www.nutritionvalue.org/

**Comment by patel-nimesh** [comment]
Now it is displaying total 52 nutrition by default
![image](https://user-images.githubusercontent.com/121149500/228146964-ebb95c6d-3af4-4620-9db7-0c648a163ed4.png)
