### ISSUE TITLE
General : Need to add more default value of the Unit

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#395]
Currently we have the following list of units

food_manager_unit' => array(
				'Gram',
				'MG',
				'PC',
				'KG',
				'Dozen',
			)

**Al letter must be in small letter.**

Need to add this all the following units

<img width="717" alt="Screenshot 2023-03-26 at 17 06 49" src="https://user-images.githubusercontent.com/15089059/227784847-56303102-3391-4458-b889-ded8d7ed2833.png">

<img width="753" alt="Screenshot 2023-03-26 at 17 08 02" src="https://user-images.githubusercontent.com/15089059/227784930-f6a1c05e-ef44-4008-b3f3-bc06570889a6.png">

<img width="738" alt="Screenshot 2023-03-26 at 17 08 26" src="https://user-images.githubusercontent.com/15089059/227784956-ebf5b7ff-bf04-4fee-b2b5-337295e39acd.png">

Reference link : https://opentextbc.ca/basickitchenandfoodservicemanagement/chapter/units-of-measurement/

**Comment by vry-kvl** [comment]
@ashokdudhat sir, I have added :
-----------
- litre
- degrees Celcius
- hg
- dag
- dg
- cg
- mg
- kL
- hL
- daL
- L
- dL
- cL
- mL
-----------
And we have already exist :
-----------
- gram
- kg
- dozen
- pc
- mg
-----------
So, We have total of 19 default units:
-----------
1. litre
2. degrees Celcius
3. hg
4. dag
5. dg
6. cg
7. mg
8. kL
9. hL
10. daL
11. L
12. dL
13. cL
14. mL
15. gram
16. kg
17. dozen
18. pc
19. mg

**Comment by patel-nimesh** [comment]
Now total 15 units default will display

![image](https://user-images.githubusercontent.com/121149500/228149688-ccb4923d-ec6a-486c-83d4-c6c110725ca7.png)
