### ISSUE TITLE
General : file name change submit food to add food

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#397]
Need to change file name

**wpfm-form-submit-food.php.  -->  wpfm-add-food-form.php**
**wpfm-form-edit-food.php.  -->  wpfm-edit-food-form.php**
**wpfm-form-abstract.php.  -->  wpfm-abstract-form.php**

<img width="333" alt="Screenshot 2023-03-26 at 18 24 58" src="https://user-images.githubusercontent.com/15089059/227789696-997284aa-00d6-452a-afe7-ec5c3be26edf.png">

also class name need to change it

class WPFM_Form_Submit_Food extends WPFM_Form 

TO following

**class WPFM_Add_Food_Form extends WPFM_Form** 

also this

class WPFM_Form_Edit_Food extends WPFM_Form_Submit_Food

To

**class WPFM_Edit_Food_Form extends WPFM_Add_Food_Form** 

### For the file name change at admin side

<img width="439" alt="Screenshot 2023-04-03 at 08 04 47" src="https://user-images.githubusercontent.com/15089059/229424478-1b6c2830-ebae-4222-bc4b-afddd274db98.png">

Need to change file name

**wpfm-form-field-editor-field.php  -->  wpfm-field-editor-form-field.php**
**wpfm-form-field-editor-group-field.php -->  wpfm-field-editor-group-form-field.php**
**wpfm-form-field-editor-group-field-row.php -->  wpfm-field-editor-group-form-field-row.php**

**Comment by patel-nimesh** [comment]
Now the add/edit update food from front and backend side is working so I am closing this issue

**Comment by vry-kvl** [comment]
@ashokdudhat sir, According to this
**wpfm-form-field-editor-field.php --> wpfm-field-editor-form-field.php
wpfm-form-field-editor-group-field.php --> wpfm-field-editor-group-form-field.php
wpfm-form-field-editor-group-field-row.php --> wpfm-field-editor-group-form-field-row.php**

File names and where the files are included were changed properly.

@patel-nimesh - Please once verify it.

**Comment by patel-nimesh** [comment]
Now this file has been changed, And I have checked the food with the frontend and backend as Add /Edit/Update/Delete and the functionality is working fine
![image](https://user-images.githubusercontent.com/121149500/233313431-ca0e7cce-b0aa-4793-a73b-36e8f3258dc3.png)

**Comment by patel-nimesh** [comment]
Now the add/edit update food from front and backend side is working so I am closing this issue
