### ISSUE TITLE
Search count shows hidden food which is out of stock

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#399]
When searching food the search count shows hidden food which is out of stock 

![image](https://user-images.githubusercontent.com/126650948/228134204-a07cf72d-a050-470a-bb63-61698ba843e6.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now if we enable out-of-stock and filter on foods then in result the number is displayed as zero (0). It should be display as resulted number

![image](https://user-images.githubusercontent.com/121149500/229035621-9807634f-67c7-4c0a-a4a0-887b8c27ff86.png)
![image](https://user-images.githubusercontent.com/121149500/229035653-91d1e9c4-b039-4483-a232-2568d096014d.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please can you verify it again? and let me know its done or not.
