### ISSUE TITLE
The price is not save, got empty when we Publish or Update the food post.

### ISSUE THREAD

**Issue by KushangDarji** [wpfoodmanager/wp-food-manager#4]
![Screenshot_2](https://user-images.githubusercontent.com/25924876/182298031-8a8eea0f-9f49-4e50-95d2-1b0bb16b3e1e.png)

**The price is not save, got empty when we Publish or Update the food post.**

**Comment by mistry-jignesh** [comment]
Verified this issue. Added the price at backend but not visible at food details page.

![image](https://user-images.githubusercontent.com/75515088/184298256-9a821d20-812e-4536-b04a-768f4f6c3273.png)

![image](https://user-images.githubusercontent.com/75515088/184298542-935ce2eb-1363-410f-8324-acc5c5d7afc0.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

 Added the price from the backend .Now visible at food details page.


![image](https://user-images.githubusercontent.com/75515088/184334105-9334f60f-7dfa-4e1a-abf2-9cf532651dbc.png)

So I closed the issue.
