### ISSUE TITLE
Warning message is display on the details page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#40]
Warning message is display on the details page.

![image](https://user-images.githubusercontent.com/75515088/192196721-73f9c542-c4f6-4056-874a-2a510a36492e.png)

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

I have checked and verified this but I can not regenerate this issue. One suggestion for you, When you open the new page or old page at frontend, Please do hard refresh once. Because sometimes it is coming from the cache may be.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this warnig error message is not face .

So I closed the issue.
