### ISSUE TITLE
Ingredients and Nutritions still displaying on front side if we removed it

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#401]
From front side if we add/edit food and remove nutrition's and ingredients then also it is displaying on the food detail page.

**Comment by vry-kvl** [comment]
@patel-nimesh - I double check this issue, Please can you verify it again and let me know issue still exists or in changes it has been solved.

**Comment by patel-nimesh** [comment]
Now remove nutrition's and ingredients on front side is working properly.
