### ISSUE TITLE
Fields correction & Default Fields

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#405]
in code :   extra_options. -->  toppings 

Entire filed editor need to change it and it must be same like frontend and backedn defualt fields which we have given in form fields code.

Every meta keys will be start with _ (underscore).

We have to keep the following default Fields

**Food Form Fields Default Fields**

- Toppings
- Ingredients
- Nutritions
- Tag
- Category
- Type

**Toppings Form Fields Default Fields**
- Topping Name
- Topping Selection Type
- Topping Required
- Topping Description
- Choices

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/232478868-bff29d05-8e45-46fe-85ec-e3c7ef1e6d90.png)
![image](https://user-images.githubusercontent.com/121149500/232478918-c8d3f82f-1b3f-411e-bf41-8791a3a3d411.png)

**Comment by ashokdudhat** [comment]
Label will be Options instead of Choices for the core plugin and we will think for the online order plugin.

with reference Improvement of the options and toppings #318

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Right now label has change to options 
![image](https://user-images.githubusercontent.com/121149500/233610710-ce2c073a-a651-49de-94ae-1ea7583a82d4.png)
