### ISSUE TITLE
Front side enable/disable Ingredients/Nutrition is not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#407]
Front side enable/disable Ingredients/Nutrition is not working. If we edit any food from frontside and change any switch value then it is not updating.

Also from admin side it is not working
![image](https://user-images.githubusercontent.com/121149500/232444877-80543255-6f0e-47fe-b905-545a2ca656b4.png)

![image](https://user-images.githubusercontent.com/121149500/232444263-c3d6edbc-19de-4972-a124-f619602df064.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now this is working properly

**Comment by patel-nimesh** [comment]
Now still facing issue. Please check @vry-kvl

**Comment by vry-kvl** [comment]
@patel-nimesh - ping me when you test this bug, I had double check this issue and still this is working.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please can you verify again.

**Comment by patel-nimesh** [comment]
Now this setting is working fine
