### ISSUE TITLE
Front side : Food thumbnail not display as food banner

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#409]
Right now if we add food banner from frontside then it is not taking that image as thumbnail 
If we add food from admin side then the banner will consider as thumbnail.

![image](https://user-images.githubusercontent.com/121149500/232445639-fb003793-40d0-4679-bf2f-f6dc210f65be.png)
![image](https://user-images.githubusercontent.com/121149500/232445716-a190b475-2db6-4138-b0bd-1e617f7bc4e7.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please can you verify again? Once you reset the field editor or check the checkbox which is located in
- Settings > Generel > Delete Data On Uninstall.

And Uninstall the plugin and re-install it and then check again.

**Comment by patel-nimesh** [comment]
I have checked in fresh setup as delete all data and create new food from frontside and still facing same issue

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now this is working properly
