### ISSUE TITLE
Frontside Foods page display console error as file 404

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#411]
![image](https://user-images.githubusercontent.com/121149500/232452324-b1743d0e-847c-4c4e-b4fb-807d93c72b29.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please  verify it.

**Comment by patel-nimesh** [comment]
Now no console error is displaying

![image](https://user-images.githubusercontent.com/121149500/232679542-a27dbc34-8696-4216-92b3-cd1dd1444db8.png)
