### ISSUE TITLE
Admin : Field editor regular price tab move remove the saved value

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#413]
From field editor set tab to "Toppings" for regular price
edit any food
Regular price moved to "topping" but the already entered value is not display 

![image](https://user-images.githubusercontent.com/121149500/232457317-794d7366-6824-4e23-89cb-99feadc761bc.png)
![image](https://user-images.githubusercontent.com/121149500/232457712-44c41be6-fd0a-4cc3-8b05-46ff7f5b2df3.png)

**Comment by vry-kvl** [comment]
This is a duplicate issue same as #414, @patel-nimesh - Please verify it and close both issues.

**Comment by patel-nimesh** [comment]
Now this issue is working fine
