### ISSUE TITLE
Admin : Field editor regular price tab move remove the saved value

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#414]
Field editor move regular price to another(Ex :-  "toppings") the price is not able to save or display at edit time

![image](https://user-images.githubusercontent.com/121149500/232458181-12c362fb-5fed-414b-acec-4f226829cf12.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now when move the tab the old price displaying and also edit/update is working
![image](https://user-images.githubusercontent.com/121149500/232668049-ca15ffa0-96a1-4742-ac4c-aadef289f88c.png)
