### ISSUE TITLE
Admin : Editing toppings from  admin side price change and update gives error

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#415]
Admin : when editing toppings from front side and changing price and updating food gives error

Note : this also removes provided option for toppings previously. 
![Screenshot 2023-04-17 160731](https://user-images.githubusercontent.com/126650948/232461287-dff16932-970b-4227-90de-aec3261f5b77.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please verify it.
