### ISSUE TITLE
Field Editor : Type multi select appearance is not working properly in new field

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#417]
In admin side field editor when add a new field in add food and select field type as "type multi select appearance" then bydefault it is display placeholder/options as food category (which food has a already food category)

If we update the food with the category then on food detail page that category is not displaying into extra added field. 

**Means the category or any value in type multi select appearance is not able to save**

![image](https://user-images.githubusercontent.com/121149500/232674451-16088e19-0f74-4bc7-981f-46ac32a547b9.png)
![image](https://user-images.githubusercontent.com/121149500/232674761-5a7331df-8344-4e8e-869a-57d1d3657669.png)
![image](https://user-images.githubusercontent.com/121149500/232674917-f2324846-5d7d-4e9c-ac78-c0890e63c438.png)
![image](https://user-images.githubusercontent.com/121149500/232675066-8681626f-f6e3-48d4-8f3a-6bd54094d871.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - As per the discussion with @krinaydhanani, Term autocomplete and term multi-select appearance is not usable in the field editor for the new fields.

So I disabled these two fields, and a user can't add a field with these 2 types of fields.

Please verify that these 2 fields are not showing in Select.

**Comment by patel-nimesh** [comment]
Term autocomplete and Term multi-select appearance is removed from the field editor for the new field So this issue will not occur

![image](https://user-images.githubusercontent.com/121149500/232964628-e3cc456f-2702-46b9-b2d6-76f514ef8300.png)
