### ISSUE TITLE
General : When input type is selected as checkbox checked box is not showing after saving the input

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#418]
When input type is selected as check box the checked box(input data) us not shown after the data is saved. 
Admin side :
![image](https://user-images.githubusercontent.com/126650948/232675409-e380bd44-2351-4438-a766-fa86f75bcbf6.png)

Frontend side: 

![image](https://user-images.githubusercontent.com/126650948/232675517-a9419ee4-1bd3-46f0-a03d-63c9931aff92.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please verify it.
