### ISSUE TITLE
Footype information not display on the food detail page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#42]
Footype information not display on the food detail page.

![image](https://user-images.githubusercontent.com/75515088/192199787-8178cdcc-2a11-4ce5-8eef-b644d78dcf3c.png)

![image](https://user-images.githubusercontent.com/75515088/192199881-eef80086-b063-4600-b6c1-4dcae34fde5b.png)

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

Please check the below screenshot,
![image](https://user-images.githubusercontent.com/25924876/192212761-5eecddc5-9e1f-4466-8cc3-91fc391eced5.png)

**Comment by mistry-jignesh** [comment]
Here  for food type is display the icon button on details page.

So I closed the issue.
