### ISSUE TITLE
Frontend : on preview to submit food if necessary topping is not selected food submit is not working

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#422]
on preview to submit food if necessary topping is not selected food submit is not working 
shows warning to select a topping

![image](https://user-images.githubusercontent.com/126650948/232687686-47f8b207-8be1-474a-867d-e8ca122e9d40.png)

**Comment by vry-kvl** [comment]
This type of UI has been changed so this issue does not create currently.

Please see bug no : [#427](https://github.com/wpfoodmanager/wp-food-manager/issues/427).
