### ISSUE TITLE
Frontend : if switch is selected as input and is set as required field front end ask switch to be on as input only 

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#424]
Frontend : if switch is selected as input and is set as required field on front end adding food asks switch to be on as input only. if switch is off then validation is raised. 

![Screenshot 2023-04-18 123628](https://user-images.githubusercontent.com/126650948/232701057-7fbe8cdf-d4f4-432f-8e66-5781fa89752b.png)
 
![image](https://user-images.githubusercontent.com/126650948/232701183-64679195-1779-4412-8799-c62cb21a7205.png)

**Comment by vry-kvl** [comment]
As per the discussion with @krinaydhanani - For the field type = switch there will no validation.

@MahendraShiyal - Please verify it.
