### ISSUE TITLE
Toppings : If we create a topping without choices then it will take default values of previous

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#425]
If we do not enter choices for second toppings then it will take the first topping values.

Means if multiple toppings are their and we do not enter the choices value then it will consider the first topping values

![image](https://user-images.githubusercontent.com/121149500/232738545-d241d3b1-d464-4906-a529-9d78863c4319.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify i t.

**Comment by patel-nimesh** [comment]
This issue is working properly.
