### ISSUE TITLE
General : Price value is accepted in minus 

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#428]
Price value is accepted in minus too 

Front end 
![Screenshot 2023-04-18 182820](https://user-images.githubusercontent.com/126650948/232785805-e2313a37-0512-4d9e-b27a-16ba21616cb3.png)

Backend : 
![image](https://user-images.githubusercontent.com/126650948/232785913-164c2ed2-4cb3-4294-854d-6fc209598945.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - This is allready covered in [Field Editor : Toppings extra field meta key is not proper in databse #435](https://github.com/wpfoodmanager/wp-food-manager/issues/435).

Please verify it.
