### ISSUE TITLE
Toppings : Extra field should display when there is a content

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#430]
On the front side in topping if we added an extra field and do not enter a value in that field then it should not display field label and view more button.

It should display when there is content/value in the field

![image](https://user-images.githubusercontent.com/121149500/232968361-989f7e4a-dda6-46a5-8b81-27562b3ce29b.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - This is allready covered in - [Field Editor : Toppings extra field meta key is not proper in databse #435](https://github.com/wpfoodmanager/wp-food-manager/issues/435)

Please verify it.

**Comment by patel-nimesh** [comment]
Still this issue arise

**Comment by vry-kvl** [comment]
@patel-nimesh - Please vierfy it.

**Comment by patel-nimesh** [comment]
Now when you add any content in the extra field then and then it will display on the front side, otherwise it will not display button or content.

![image](https://user-images.githubusercontent.com/121149500/233551454-6892f2ae-a7f2-4fa1-a3b8-b373c5219c94.png)
