### ISSUE TITLE
Field Editor : Multiple banner sync is not working 

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#432]
If we enable multiple file upload from settings then in field editor it is not auto-enable the multiple files

![image](https://user-images.githubusercontent.com/121149500/232984104-7c0b7cf5-652b-4038-9c6b-242b0cf2762f.png)
![image](https://user-images.githubusercontent.com/121149500/232984146-82b17423-e939-417a-ae8e-eee9727c2da3.png)

**Comment by vry-kvl** [comment]
As per discussion with @krinaydhanani. We decided to remove settings - Allow multiple banners. because we have allready provided in field editor soo.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
When checking with enable/disable the multi-image is removed not displaying the previous save image banner from both front and backend side
![image](https://user-images.githubusercontent.com/121149500/233312855-96bc12b2-c58a-4134-8702-74a37a2fe7ed.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify it.

**Comment by patel-nimesh** [comment]
Now this is working fine and the setting is removed. For multiple image you need to manage it from field editor

![image](https://user-images.githubusercontent.com/121149500/233352480-06b7eab4-1804-4f3b-b3fc-3fb0713defb7.png)
