### ISSUE TITLE
Field Editor : Tab group is not working in toppings extra field

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#433]
In admin side filed editor if we add any extra field then the tab group is not working for extra field in toppings

![image](https://user-images.githubusercontent.com/121149500/233002857-ee227987-deb0-4c66-a259-29dc2a1b4893.png)

**Comment by vry-kvl** [comment]
Tab group option is only for the general field editors, for the toppings field editor there will be no any type of tab group.

**Comment by patel-nimesh** [comment]
Tab group field is removed from the topping field editor
![image](https://user-images.githubusercontent.com/121149500/233537193-b65a2391-0e86-405c-a3fc-97527c808ec6.png)
