### ISSUE TITLE
Field Editor : Toppings extra field meta key is not proper in databse

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#435]
In filed editor if we add any extra field in topping form then in database the meta is not saving as underscore (_)

![image](https://user-images.githubusercontent.com/121149500/233033814-abb4dec7-8bdd-48c8-9a72-ab185bd3a0be.png)
![image](https://user-images.githubusercontent.com/121149500/233033872-1ecdff76-3536-453c-8b19-62c86ed78bc1.png)

**Comment by vry-kvl** [comment]
This issue is covered in [Toppings : Choices field meta should be proper in database #434](https://github.com/wpfoodmanager/wp-food-manager/issues/434)

Please verify it - @patel-nimesh.

**Comment by patel-nimesh** [comment]
Now the extra field in toppings meta key display as underscore (_)
![image](https://user-images.githubusercontent.com/121149500/233536814-d66a1590-5559-473f-8e5b-d017e8873c87.png)
