### ISSUE TITLE
Topping required and other fields should be removed

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#439]
![image](https://user-images.githubusercontent.com/121149500/233542315-dfef0754-a6dc-4b65-94da-85d6ef0b0668.png)

**Comment by vry-kvl** [comment]
As per the discussion with @krinaydhanani. These fields are not usable in our core plugin, this will be added in other plugins where we have to sell food and list them with selection types and other requirements.

**Comment by vry-kvl** [comment]
@patel-nimesh - Please verify again.

**Comment by patel-nimesh** [comment]
This fields are removed
![image](https://user-images.githubusercontent.com/121149500/233567562-991af263-90c3-4a53-a7ad-a4ba7457fcb0.png)
