### ISSUE TITLE
Frontend : adding food with toppings options from front end gives warning

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#442]
Create new food from frontend side with topping options gives warning

![image](https://user-images.githubusercontent.com/126650948/235060927-973d52b2-f9ef-47d8-9aef-654aaad21480.png)

![Screenshot 2023-04-28 104639](https://user-images.githubusercontent.com/126650948/235061042-41fd7435-ee2e-4d68-9471-364ecce538e5.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please verify it.

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please can you verify again.
