### ISSUE TITLE
General : When enabling Multiselect in settings for all conditions no food is displayed on output. 

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#446]
When enabling Multiselect in settings for all conditions no food is displayed on output. 

=>Settings <=

![image](https://user-images.githubusercontent.com/126650948/235154752-06c53f43-7396-48d3-802c-fb680c1cd7f7.png)

=> Output foods <= 

![image](https://user-images.githubusercontent.com/126650948/235154919-405e754d-c701-4855-86c1-0078e843bfc0.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please can you verify again after taking the latest pull request.
