### ISSUE TITLE
Food listing page - Food is repeated 2 times

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#45]
Food listing page - Food is repeated 2 times.

![image](https://user-images.githubusercontent.com/75515088/192219447-39f6355f-7f0d-4199-adb1-1d33057e812c.png)

**Dashboard page food is not  repeated.**

![image](https://user-images.githubusercontent.com/75515088/192219684-34bf1ccb-55a0-4973-b470-4e57905a6953.png)

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

I have checked and verified this issue on my end but I can not regenerate it. Can you please check on your end once again and provide steps to regenerate.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine.

Now recored is availabel properly.

So I closed the issue.
