### ISSUE TITLE
Front side : enable/disable Ingredients/Nutrition is not working for preview

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#450]
Front side enable/disable Ingredients/Nutrition is not working for preview. If we enable/disable Ingredients/Nutrition from front end and go for preview  and again for editing the change is not there for any food from frontside. It is saved if we don't go from preview to editing but save. 

==> Before preview <==

![Screenshot 2023-05-05 151349](https://user-images.githubusercontent.com/126650948/236426775-ed4d4ba9-9d74-43aa-9de5-f989a5f2f872.png)

==> After preview and edit again <==

![Screenshot 2023-05-05 151409](https://user-images.githubusercontent.com/126650948/236426852-4d3aaa7e-ed86-4237-9f9c-5a9b1b51bd8f.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please verify it.
