### ISSUE TITLE
General : Topping price is not following currency settings for decimal

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#453]
Topping price is not following the currency rule for decimal. 

==>Decimal rule setting screenshot set to 2 <==

![Screenshot 2023-05-05 155137](https://user-images.githubusercontent.com/126650948/236433875-1f02dfd9-75c2-4946-84bc-80b77d23ed7a.png)

==> Decimal settings is not applied on price on frontend  <==

![Screenshot 2023-05-05 155057](https://user-images.githubusercontent.com/126650948/236434059-7594752f-5efd-48d7-b6ea-3037cc0c3770.png)

**Comment by vry-kvl** [comment]
@hiteshmakvana - Please verify it.
