### ISSUE TITLE
Front end : Img URL is accpeted in Food name and gives img as output

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#457]
Front end side Food name is accepting img url and is giving img as output. 

==> IMG URL in Food Name from frontend <==

![Screenshot 2023-05-10 172329](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/45854327-2d35-45a5-b985-fa09f22b3c5c)

==> IMG shows instead of IMG name on Frontend <==

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/5d7d6be7-8261-48b7-9f7e-db03a974b538)

**Comment by vry-kvl** [comment]
It is depending on the user which type of data he/she inserted because I had checked this with the default WordPress, they also don't escape the title because it will become problematic.

@MahendraShiyal - Please verify it.
