### ISSUE TITLE
Admin : Enable/ Disable Ingredients/Nutritions switch issue

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#460]
On admin side when editing food  In advanced Enable/Disable Ingredients/Nutritions  The switch shows always enabled.

The Function itself is working and is enabling and disabling the food Ingredients/Nutritions.

==> Enable Disable Food Ingredients Video <==

[Enable Disable Ingredients n toppings.webm](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/8eaa0996-ad0c-4245-8d3a-2a83e6529fa6)

**Comment by dhruvikathrotiya** [comment]
Already Solved Add Food Enable Ingredient & Nutrition's is not working #489.

**Comment by patel-nimesh** [comment]
This is already covered in #489
