### ISSUE TITLE
Front end : Issue for matching record count on foods page

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#461]
On front end foods page for search results more than allowed food on one page the count shows only allowed food count

If we have set allowed food count as 10 and out search results contains 11 results the matching count shows only 10 matching record found. 
Also when we click on load more for more food one page the matching record count changes to remaining displayed food count on that page. In our case 1. 

==> Max 10 matching Record count <==

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/09743251-b167-4b8e-bcb8-e2d4c3f32af9)

==> After load more matching record count <==

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/96f510e6-0308-4d53-8b2c-3a36210998b9)

==> Whole issue video <==

[Matching record count issue.webm](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/f6e5f0e5-4608-4f1e-9ea3-779cb7ef53cc)

**Comment by patel-nimesh** [comment]
Now the filter count is working fine

https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/2867db2e-6ef8-4193-a944-81bb4e0493d2
