### ISSUE TITLE
Front end : Imported food Edit issue

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#462]
When Food is imported using Wordpress Import function after importing food editing food from frontend gives Warning 

==> Warning after Food is imported and edited food save issue <==

![Screenshot 2023-05-19 151606](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/876b953f-9c69-4f6f-9a1e-63e41bbb74f5)

**Comment by dhruvikathrotiya** [comment]
@patel-nimesh I have tested this bug, but it does not exist right now please try it again it will reproduce please let me know.

**Comment by patel-nimesh** [comment]
I have verified by importing the foods and editing it from frontside and no error or warning is displaying. So I am going to close this issue.
