### ISSUE TITLE
General : For Imported Food  thumbnail is not imported 

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#463]
For Imported food food thumbnail is not imported 

==>  Thumbnail not imported for imported food <==

![Screenshot 2023-05-19 151949](https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/649cd5cd-3477-4383-946a-86612bd988df)

**Comment by dhruvikathrotiya** [comment]
It’s not possible with WordPress default importer.

**Comment by patel-nimesh** [comment]
According to the developer comment this is not possible with WordPress default importer so I am closing this issue
