### ISSUE TITLE
Front end : RSS only loading upto 10 food 

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#464]
RSS is only loading upto 10 food for search results more than 10.

If search page is loading 10+ food RSS is only creating link of 10.

Please check video for more understanding.

==> RSS issue Video <==

https://github.com/wpfoodmanager/wp-food-manager/assets/126650948/d2224757-5237-4885-a467-58860432db07

**Comment by patel-nimesh** [comment]
I have confirmed this issue in Event Manager and It is also displaying just 10 Events in RSS even Result is having 10+ Events. So need to fix this issue.

**Comment by patel-nimesh** [comment]
Still not working proper. @bikasraj Please check properly when getting 10+ search result found

**Comment by patel-nimesh** [comment]
Now the RSS is displaying for 10+ foods

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/efbebe6f-d146-494d-983e-9aa4255cf92e)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/f674c78f-d8ca-490c-b625-0e970431a156)
