### ISSUE TITLE
Food Topping Description display as <p> tag

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#468]
If from backend enter food topping description then on front side it will display as P tag <p>
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/763ce6dd-0285-4af1-97b4-77f370b83437)
 
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/08eb544a-9c7d-4fcf-9ccf-dc517ac03e0f)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please Check.

**Comment by patel-nimesh** [comment]
Now the description is displaying as proper without p tag
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/21965408-9dcb-43d1-bf36-572f7e37bac7)

**Comment by patel-nimesh** [comment]
Still on frontside the food description is displaying a p tag
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/2d04cf43-9208-42d9-be23-7ab85dea3724)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check.

**Comment by patel-nimesh** [comment]
Now the description is looks proper without p tag
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/ad0a436c-a332-442d-af82-7fe1666648c3)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/e7e11721-3b57-4115-b332-091847802b07)
