### ISSUE TITLE
Frontend : Food Edit time displaying error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#469]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/8b0f8b25-309f-488b-911e-4cea31b396a3)

Warning: foreach() argument must be of type array|object, string given in C:\xampp\htdocs\tester\wp-content\plugins\wp-food-manager\forms\wpfm-edit-food-form.php on line 74

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/9d2f2b9e-8602-4afc-bb8d-aa243ad439b4)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check

**Comment by patel-nimesh** [comment]
Now this issue is resolved but in console error is displaying
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/c9312dd1-8d76-4a50-8a5c-fc4d608c92d5)

**Comment by patel-nimesh** [comment]
Now no error is displaying
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/0c07c9be-d4b0-45b7-af55-65214dc44ba0)
