### ISSUE TITLE
Admin : Advanced setting switch is not works properly

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#470]
For example :- If we disable then it will not display selected as disable

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/471a90ed-c1d9-4983-8acb-397a6b4500ce)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check.

**Comment by patel-nimesh** [comment]
Now the switch is working properly from bothside
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/022d7ec4-88f5-4945-bc8c-de29b33a9b26)
