### ISSUE TITLE
Frontside : unable to add food banner

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#471]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/171c7e30-0266-46d4-a43e-9f44364afa27)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check.

**Comment by patel-nimesh** [comment]
Now food banner is working
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/ae864f1e-3048-443d-87b5-7ce466fdbcda)
