### ISSUE TITLE
Add food page console gives error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#472]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/a4b2c4d5-c7c8-4bf1-9d2e-efb0af6c2df5)

**Comment by vry-kvl** [comment]
<img width="918" alt="image" src="https://github.com/wpfoodmanager/wp-food-manager/assets/119648390/ec2dc2c6-a7a4-4e44-94e9-ef72cea2f43e">

@patel-nimesh - Please can you check again.

**Comment by patel-nimesh** [comment]
Now no error is displaying in console
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/5befdc36-ee9b-47e7-a950-8c537bb65da3)
