### ISSUE TITLE
Food detail page gives warning in console if topping used

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#474]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/5332ffbf-e8d2-447d-96b1-8bea76eb6e9a)

**Comment by vry-kvl** [comment]
<img width="917" alt="image" src="https://github.com/wpfoodmanager/wp-food-manager/assets/119648390/816569ed-36ab-4b84-aacc-f12328842e96">

@patel-nimesh - I had checked but there is no error please can you check and let me know its happen or not.

**Comment by patel-nimesh** [comment]
Still issues are arise and error is displaying in console
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/00dea463-2852-48e9-a4c8-cbe1e114dd7a)

**Comment by dhruvikathrotiya** [comment]
This is not an issue to disturb any functionality of the site.

**Comment by dhruvikathrotiya** [comment]
As I said, this is not an issue to disturb any site functionality.

**Comment by patel-nimesh** [comment]
This warning is not breaking any functionality so I am closing this issue
