### ISSUE TITLE
Frontside : Food dashboard delete food message is not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#476]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/18619258-dcc9-48db-aa17-408f72c8f5c3)

**Comment by vry-kvl** [comment]
@patel-nimesh -  Please Check

**Comment by patel-nimesh** [comment]
Now the delete notice is proper
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/1418da9e-64a8-4d45-ae9d-4d2d7cdbb782)
