### ISSUE TITLE
Frontside : Food dashboard duplicate any food then field value is not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#477]
For ingredients and nutritions the value is not come properly while duplicate a food

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/2efd52a4-54cc-48bc-81cb-b0730b738998)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please Check

**Comment by patel-nimesh** [comment]
Now the ingredient and nutrition is looks proper at duplicate food time
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/2fe50ddc-ad07-426e-8d7a-7a7b86afa1ff)
