### ISSUE TITLE
Food detail page the category, types and tag is not as per the given .

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#479]
The food category, Type, and Title format are different on frontside ..not the same as we gave from the admin side
On front side display a slug not name

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/d4558df6-b47f-43da-8faa-fa5227306c5c)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/4aa84e1d-d62a-4fdb-a1af-70deb59ba52c)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please check.

**Comment by patel-nimesh** [comment]
Now all things are as per the data given
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/f4cce8d9-45fd-4309-a807-1d131a117277)
