### ISSUE TITLE
Food listing - List/box view button is not look proper 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#48]
When I am chaning button from list view to grid view or gird view to list view then at top corner button is not looking proper.

https://user-images.githubusercontent.com/75515088/192267549-37e761c2-5006-4996-9021-0e4b8a823d3a.mp4

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

I have checked and verified this issue from my end. And I can't regenerate it.

**Comment by mistry-jignesh** [comment]
This issue is workig fine . So I closed the issue.
