### ISSUE TITLE
Frontside Multiple file in food banner not able to upload

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#481]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/4239ddd7-15b9-4e4a-a292-e63645df2bdd)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/0ffec79c-6d69-4ff8-841d-7216ffdd4dd9)

**Comment by vry-kvl** [comment]
@patel-nimesh - Please Check.

**Comment by patel-nimesh** [comment]
Now multiple image banner is working fine
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/681a11db-51ea-49ee-9792-935d976ee6cd)
