### ISSUE TITLE
Adminside : Any custom post type if script use then name is not displaying

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#483]
<script\x20type="text/javascript">javascript:alert(1);</script>
above script use in any custom post type as a name in category,type,tag,nutrition,ingredients,units etc. then it will create a post type but name will display as blank

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/609afaf2-7ea4-4cb7-94c8-9deae23dcdfb)

**Comment by vry-kvl** [comment]
@patel-nimesh - If you use the only script as the name on category, type, or tags and it will be null it means the prevention of XSS payload is working properly.

The user must be filled the proper data if there is any other code like script and html tag then it will be blank.

**Comment by patel-nimesh** [comment]
As per the developer comment this is not an issue
