### ISSUE TITLE
Frontside : Add Food Enable Ingredient & Nutrition's is not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#489]
When trying to add food from the frontside and edit the food listing then the given value for enabling nutrition and ingredient is not saved.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/706e054f-118d-4b18-8363-87e5eee86ca1)

After clicking on preview and edit listing the saved value for ingredient and nutrition is not able to save
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/db9782cc-5641-4739-8060-0d2a69108811)

**Comment by patel-nimesh** [comment]
Now it is working properly when editing the listing at add food time.

**Comment by patel-nimesh** [comment]
This issue is fixed in dhruvi branch so please commit and merge it in 1.0.5 @dhruvikathrotiya

**Comment by dhruvikathrotiya** [comment]
#489 Is Merge to 1_0_5 also solved issue #460 Here.

**Comment by patel-nimesh** [comment]
Now the issue is merger into 1.0.5 branch and it is working properly
