### ISSUE TITLE
Right now location field is not using 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#49]
Right now location field is not using .

![image](https://user-images.githubusercontent.com/75515088/192268206-1ffd091c-94ce-4dc1-8070-dc5b645037a4.png)

**Comment by krinaydhanani** [comment]
This is an enhancement we will add a location field in the next version.

**Comment by krinaydhanani** [comment]
When we will develop resturant manager then we will add the fiend in that.

**Comment by patel-nimesh** [comment]
This is fixed
