### ISSUE TITLE
Frontside : Unable to change or edit update category

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#490]
From frontside if we edit food and update category with new value then the category is not able to save or update.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/c5ad92ad-c5fc-4a9d-ac40-2861ea7daf7c)

**Comment by dhruvikathrotiya** [comment]
In my Local Setup, This functionality is working fine. Please Verify with the below video.

https://www.awesomescreenshot.com/video/20012843?key=2f8bbdadbf0deaa685df827d05586358

If you have still an issue then please provide me a bug re-produce step or video.

**Comment by patel-nimesh** [comment]
Yes right now not facing issues and the category is updating properly. 
So I am closing this issue
