### ISSUE TITLE
Settings Disabled is not working and show left side even it disabled.

### ISSUE THREAD

**Issue by KushangDarji** [wpfoodmanager/wp-food-manager#5]
The Food ingredients, Food neutritions and Food units are disabled from the settings, But still is showing at left side.

![Screenshot_3](https://user-images.githubusercontent.com/25924876/182361466-007d38a7-1a15-4627-873f-0fdec56beb83.png)

**The Food ingredients, Food neutritions and Food units are disabled from the settings, But still is showing at left side.**

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Disable setting are working properly. Left side disable option are hide.

So I closed the issue.
