### ISSUE TITLE
Code cleaning : 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#500]
**Correct file names :** 

<img width="416" alt="image" src="https://github.com/wpfoodmanager/wp-food-manager/assets/35419531/d85ac8dd-a679-4fb7-ac35-665acefe7034">

**Correct functions comments in all files :**

<img width="1085" alt="image" src="https://github.com/wpfoodmanager/wp-food-manager/assets/35419531/cec1c621-f539-49dd-9634-e5b9c690b0d5">

**Beautify all HTML Files**

<img width="1499" alt="image" src="https://github.com/wpfoodmanager/wp-food-manager/assets/35419531/d7912f2b-f3e9-4a63-b200-e912f626dd65">

**Comment by dhruvikathrotiya** [comment]
1. Boilerplate rules according to this are not possible.
2. Currently I am working on this.
3. In some places it's required so where need to change I will do it.

**Comment by krinaydhanani** [comment]
This issue is resolved so I am going to close this issue.
