### ISSUE TITLE
youtube channel link missing 

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#502]
youtube channel link missing .. now we have youtube channel

https://www.youtube.com/channel/UC5j54ZQs7DLM8Dcvc2FwpPQ

<img width="1007" alt="Screenshot 2023-10-05 at 20 18 51" src="https://github.com/wpfoodmanager/wp-food-manager/assets/15089059/3c9d5ff6-665d-46ac-a4ca-d353d8034a11">

Also here too

![Uploading Screenshot 2023-10-05 at 20.23.22.png…]()

**Comment by patel-nimesh** [comment]
Now the link has been changed
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/3dc9055d-1c95-401b-9dcd-a6625b08f165)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/fa611397-fc16-48e7-a50f-acf676ef5e36)
