### ISSUE TITLE
We can add the remaining food manager categories.

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#509]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/9f2ce791-5163-4f03-8f69-8099760d9e35)

**Comment by rashmipsingh** [comment]
@patel-nimesh Now the default food manager categories are:
Appetizers/Starters,
  Breakfast,
  Dessert,
  Beverage,
  Main dishes,
  Lunch,
  After Hours,
  Drinks,
  Brunch,
  Dinner

**Comment by patel-nimesh** [comment]
Now the categories added to foods and showing on food detail page
![image](https://github.com/user-attachments/assets/83ff5388-06a6-49d3-ae02-6f0f73e83e92)
![image](https://github.com/user-attachments/assets/20b95472-11e6-4613-8f8b-8572a34c2d0f)
![image](https://github.com/user-attachments/assets/80048ec6-6466-475f-8d27-a0e1706a37ed)
