### ISSUE TITLE
Depenecy changes related to restaurant manager

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#511]
Depenecy changes related to restaurant manager for food manager menu

**Comment by rashmipsingh** [comment]
@ritakikani Its done.

**Comment by patel-nimesh** [comment]
Now the menu is displaying properly.
Restaurant detail page 
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/da73ed26-9c3c-4f2a-91a0-55e48e5d8fb9)
Menu detail page
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/d036bf35-0066-4127-9983-86919af962c3)
Menu shortcode use on page
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/46da3e75-9e78-4bed-908e-313ef02764a3)
