### ISSUE TITLE
Admin Side: Displaying error in Stock Status.

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#514]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/ac5a60d7-540c-45a0-8522-2619c9915b26)

**Comment by patel-nimesh** [comment]
Now no error is displaying
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/c1c0c9e1-33d5-4b3c-a018-34b54d9e5c71)
