### ISSUE TITLE
Admin Side: The menu image field should be displayed on the menu details Page.

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#519]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/8b10d86f-1ac7-463c-ab72-1ff4a5ba6ce5)

The image field should be displayed on the menu details  Page.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/46892409-fcd1-4e89-902f-6c713d138198)

**Comment by patel-nimesh** [comment]
Now the image is displaying but it should be display as small size like thumbnail
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/75e3186a-d069-4f83-bac8-3961738351bc)

same like foods page
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/51398e28-6c0a-4ca0-9fdd-dc92bd1701d3)

**Comment by patel-nimesh** [comment]
Now image looks proper
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/7d08333e-2402-4448-a116-49390f24db1d)
