### ISSUE TITLE
Frontside : Image is not displaying for menu

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#521]
In the menu, if I upload a menu image then on front image is not displayed on the menu detail page.
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/69cb9d71-7788-4f15-9008-0c08a492bc25)

**Comment by patel-nimesh** [comment]
Now the menu image is displaying on menu page but also displaying the error message
If use the shortcode on page then on page it will displaying the error
Warning: Undefined variable $menu_id in D:\wamp64\www\wpfm\wp-content\plugins\wp-food-manager\templates\content-single-food_manager_menu.php on line 20
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/5ed44191-4aca-4ae4-aa54-184169d7f89b)

**Comment by patel-nimesh** [comment]
Now if we use shortcode on page then image looks proper
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/9ddf10ee-3b21-44d3-acdc-8353ac0790b2)
