### ISSUE TITLE
Admin: The Food manager does not delete it by itself. 

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#524]
- During the deletion of a food manager, an error message appears preventing the deletion process, and does not delete by itself.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/05713b08-9d3e-4dd3-a5be-ff8462693016)

**Comment by bikasraj** [comment]
This issue is only in localhost, when I upload the plugin to any server, this issue does not occur.

**Comment by patel-nimesh** [comment]
Also if use git copy then maybe issue arise. If use normal zip file then plugin deleting properly
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/152e698e-aa00-45e8-a8d4-b6f4959976b1)
