### ISSUE TITLE
 Dependency on Addons - Add food menu in a field editor

### ISSUE THREAD

**Issue by rashmipsingh** [wpfoodmanager/wp-food-manager#529]
Need to add a function for food menu post type in a field editor for both the addons i.e. Restaurant Manager and Restaurant Gallery.

**Comment by rashmipsingh** [comment]
Restaurant Mnager https://github.com/wpfoodmanager/wpfm-restaurant-manager/issues/171

**Comment by patel-nimesh** [comment]
Menu functionality is working fine and menu is displaying properly on front and backend
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/2109beb1-85cf-437b-9c60-9f41edcc8370)
