### ISSUE TITLE
Create a feature to add title on the food listing page.

### ISSUE THREAD

**Issue by rashmipsingh** [wpfoodmanager/wp-food-manager#531]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/93907749/245aa637-70d1-413e-971b-67db1d8583c3)
Change this static code to dynamic so that we can add page titles dynamically. Any addon wants to use the core file, they can add the title in the shortcode itself.

**Comment by patel-nimesh** [comment]
Now both page title is different
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/3f1e1865-1757-4837-8d84-5f4870e2d620)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/f7b52e75-3b07-4ffc-9eec-68b45bcfc7c9)
