### ISSUE TITLE
Frontside : Food description the editor options formatting is not displaying on fooddetail page

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#534]

**Comment by patel-nimesh** [comment]
Now the description formatting is displaying
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/830725f1-209d-44d7-9770-82503265cfa7)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/572cd61f-e6fc-42d8-9664-3fe0fdab1478)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/164d9890-9cac-494e-9940-c5072a56c588)
