### ISSUE TITLE
Frontside : Food Listing page need to display category on each food

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#535]
On front side food listing page we need to display food category on each food details

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/e9444689-5c03-4a72-a494-088c4af1e3fc)

**Comment by patel-nimesh** [comment]
Now the category is showing on every food listing .But need to make UI proper same as restaruant category showing
![image](https://github.com/user-attachments/assets/fafa743e-d5ea-4b0b-86e5-5fa377d478bf)
![image](https://github.com/user-attachments/assets/2bc269c1-4eb9-456d-84d2-670a1a40431a)

**Comment by kaushikpokal** [comment]
Fixed
![image](https://github.com/user-attachments/assets/963053bf-516d-48bf-a03e-3960775b76fb)

**Comment by patel-nimesh** [comment]
Now food category looks proper on food listing page
![image](https://github.com/user-attachments/assets/73a5bbe7-3ca7-4b42-9854-990849faea12)
