### ISSUE TITLE
Admin Side: In Field Editor, if we delete an additional field, the field is not deleted the first.

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpfoodmanager/wp-food-manager#536]
- If we delete an additional field in Toppings form fields, it is not deleted the first time. 
- It deletes on the second refresh.
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/136054608/d04759e6-c6fe-44ff-8ab0-dbd6c6c5b714)

**Comment by patel-nimesh** [comment]
Now the field delete is working properly
