### ISSUE TITLE
UI Issue on license page

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#547]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/e6844e39-7414-4da0-ba65-304348ebac19)

**Comment by patel-nimesh** [comment]
This issue occurs when online order addon is deactivated. Now it works proper when addon is active or deactivate
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/60e26649-b069-472a-912d-40786dc2da1d)
