### ISSUE TITLE
Food Dashboard - View count is disply zero

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#55]
Food Dashboard - View count is disply zero.

![image](https://user-images.githubusercontent.com/75515088/192451660-eeebfc67-b72e-43fa-bc4f-8cb00013ad86.png)

**Comment by KushangDarji** [comment]
@mistry-jignesh ,

The View count is already working. Please follow below steps to understand how it's works.

* The Post view count food posts is totally depend upon new fresh browser without any caching.
* So please open any Food posts in new browser or guest mode to view Post count for specific posts.
* If you open Food posts in same browser that open before please clear the cache and session data for that particular browser.

I have checked and verified this issue from my end and it is working fine properly.

**Comment by mistry-jignesh** [comment]
![image](https://user-images.githubusercontent.com/75515088/192968530-7fcec8a7-e85a-4cf1-b094-a08e3fa28c61.png)

Verified this issue. This issue is working fine.

Now View count is working properly.

So I closed the issue.
