### ISSUE TITLE
There is no field to add toppings when add food from frontend-side.

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#556]
I am not getting topping add field at frontside when I am adding food, but shows when I try to Edit the same food. So, we must need to provide "Add Toppings" field on Add Food Form too.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/15938f2d-0067-4e00-927e-c8f4e046266a)

**Comment by Bharat-Kathiriya** [comment]
I've fix this bug can i send code here.!

**Comment by patel-nimesh** [comment]
Not getting any add topping option when adding food from frontside
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/6f1f5d85-9bd2-4c44-96fc-0d0a6c85a2dc)

**Comment by patel-nimesh** [comment]
Now add food shows the add topping on frontside and also in woocommerce product the variation are created
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/3b4effe6-2286-4111-bbbc-3e4be21f5e18)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/3ef4b8af-b01c-4921-8364-799ea975e638)
