### ISSUE TITLE
Food Listing - Click on type and category and other option then not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#56]
Click on type and categories and other option then not working.

![image](https://user-images.githubusercontent.com/75515088/192458187-44f16c69-a7b6-4ee6-b254-07efe3dddb1e.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have setup the archive pages for **Food Type, Food Category and Food Tags**.
It is not possible to set for **Food Ingredients and nutrition**, Because it is different for all specific food's values as per unit and gram.

**Comment by mistry-jignesh** [comment]
Verified this issue . This issue is fixed & working fine with Food Type, Food Category and Food Tags.

As per @kushang-tailor -It is not possible to set for Food Ingredients and nutrition, Because it is different for all specific food's values as per unit and gram.

So I closed the issue.
