### ISSUE TITLE
 Code Review By Rita

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#560]

**Comment by ritakikani** [comment]
Need to change function name and variable name as per our coding standard.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/bf7de4c8-6ae0-4bcb-9451-cfe9db49b2d2)

**Comment by ritakikani** [comment]
This function has to many HTML code so as per my knowledge, we have to put in template file rather then the function file.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/c8199345-08db-4713-9c64-3b20b420743e)

**Comment by ritakikani** [comment]
Class must outside the function, and in separate file.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/bc4a472f-b141-4747-bc77-93fa9635a0e8)

**Comment by ritakikani** [comment]
Variable and function name must be as per our coding standard.


![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/7d7a8ef8-3d8f-4164-8676-2b58bb8491e8)

**Comment by ritakikani** [comment]
These options are not define any where in plugin.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/1cd36354-8977-44b0-9b23-0bca7df22cc5)

**Comment by ritakikani** [comment]
This should be 6.2

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/b998bc49-3638-4f10-b5fc-c2d4c75e7e40)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/08aa30f8-895e-4da0-a7fc-abe7b69e324d)

**Comment by ritakikani** [comment]
Need to localize strings in entire plugin.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/b0f83c6c-0193-437c-aab2-08777da2096a)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/646651f9-f705-4fc2-a49b-b71d37e05e83)

**Comment by ritakikani** [comment]
Esc string

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/70368e32-54fe-47da-8dbd-5510a92c27be)

**Comment by ritakikani** [comment]
Jquery must inside js file

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/4fae8604-c22f-480c-9e72-a12ff8319219)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/907cab1d-d673-407d-93b9-8a53762b1968)

**Comment by ritakikani** [comment]
Remove this commented code

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/b049bd06-77bf-41ca-a490-e971a23fd3e3)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/d6302426-94ad-42cb-a64a-20fc064e51c4)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/7c2cfb60-fb44-4363-8225-cdecd0edf486)

**Comment by ritakikani** [comment]
Variable name need to change

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/76341115-ed03-487c-bf32-765f65dce6d7)

**Comment by ritakikani** [comment]
String localization 

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/30801a73-4e23-4bab-b12f-16df5398dd84)

**Comment by ritakikani** [comment]
All values in array are same in both if and else part, only one value is added in else part so we can remove this code just create one array and assign all value and also define filter, so in next step need to add if condition and in them add(push)N extra element.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/83a7fd7d-33ea-4b89-b848-83f3755d7cbd)

**Comment by ritakikani** [comment]
Group key is not availbale in this addon, so please remove this entire If section.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/6fea8fed-b339-4dd7-915b-996a14b2e519)

**Comment by ritakikani** [comment]
Group field feature is not supported in this plugin so please remove all code releted to group field from entire plugin

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/92170ff3-d7c0-407b-8dd6-a86e2aaaef05)

![Uploading image.png…]()

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/359a575b-a296-4b02-9dca-d3f76d337eb3)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/ac9fb502-7452-4916-8e34-065d46c126e2)

**Comment by ritakikani** [comment]
This is non usable code, please remove this function

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/45b633ea-ab4d-49b9-9b59-d812e8d227fc)

**Comment by ritakikani** [comment]
Without function and class file :   


![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/7f5de50d-e59c-4035-a325-1047dc6225c3)

**Comment by ritakikani** [comment]
Rename the variable :  

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/0b6acf2a-7739-45b5-b831-6b1c7d4d6a35)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/688b5d38-b1af-4249-afc7-b850839cd0b4)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/920a031a-c01b-4475-a15e-debbe612fb57)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/f4b8fb47-95bc-459b-b9e5-1ecea9ca1e7b)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/0d7b35c8-e539-4da5-a5e8-6460df92eaa4)

**Comment by ritakikani** [comment]
NEed to change function name 

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/92330b59-d49e-480e-b226-45dec619bd79)

**Comment by ritakikani** [comment]
Variable name :  

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/ab9c4a6b-240c-43b6-aa30-b9d1ad56fead)

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/e7f25182-6349-40cb-a559-9ed583aed7f9)

**Comment by ritakikani** [comment]
Need WP Query :  


![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/fc205890-79b3-40d1-a348-460830f4ad80)

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/4c4aa39b-7d95-47b1-ae63-03269e37b304)

**Comment by ritakikani** [comment]
This function must in template.php file not in hook file.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/c6e3f4c5-82ca-48ca-adf7-3b650fb47ca1)

**Comment by ritakikani** [comment]
This functions are symple so must inside functions.php and template.php file not in hook.php file.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/529d37a9-eb62-43b6-9ac8-2f421453d988)

**Comment by ritakikani** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/f05719fc-8c98-429a-ba6a-d3cdd736e631)

**Comment by ritakikani** [comment]
add string with text domain

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/ba249c00-be98-4562-9cfd-203bfdf5ee8a)

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/17273d2b-6311-4362-b7f6-fb8ff872234d)

**Comment by ritakikani** [comment]
Need to remove this commented code

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/3ec393f6-3f1a-4cae-a3f2-646560ea2b45)

**Comment by ritakikani** [comment]
Remove this commented code

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/3ea69e8f-7e65-400d-8c7b-d2f12b83e4eb)

**Comment by ritakikani** [comment]
Remove this code as group field is not supported in this plugin.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/b0071bd4-2f45-4bf9-a35d-334bf11268ec)

**Comment by ritakikani** [comment]
Change variable name

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/eb6e73ba-28ac-4fb7-b553-c14b69c0f3d5)

**Comment by ritakikani** [comment]
If not usable this commented code then remove this

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/29787497-2fc2-41a4-ade0-5cfec74bd5f4)

**Comment by ritakikani** [comment]
@patel-nimesh please verify all the functionality of this plugin.

**Comment by patel-nimesh** [comment]
I have test all the functionality for the addon and now it is working fine
