### ISSUE TITLE
Admin : Need Thumbnail use and setting in food menu

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#563]
In admin need to give a setting for display the thumbnail image to left, right and not to show on food menu.

![Screenshot 2024-04-26 at 14 45 19](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/1bd4addd-c55c-4fde-90e0-09b3a576ffd1)

**Comment by rashmipsingh** [comment]
@kaushikpokal I have added the options in the setting page. Please check and fix the UI.
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/93907749/e112ac26-5b0c-457d-b97a-b90fb103e734)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/93907749/30eb4075-fdf6-45b2-943f-c50e2ecd6cc7)

**Comment by patel-nimesh** [comment]
Now the thumbnail of food use setting is given and working fine

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/980c26f9-d95b-4008-bd2b-b84dca4704ed)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/a0570b90-aee5-448f-864f-a6ab9d59bd59)
