### ISSUE TITLE
Menu page add setting for the link.

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#564]
In admin side need to give setting for the food title click that whether need to redirect on food detail page from food menu.

**Comment by patel-nimesh** [comment]
Now the link redirection option is given and it is working fine for the menu food redirection
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/29109b0d-2c5c-4f65-9ff9-111afe32f574)
