### ISSUE TITLE
Admin : Need to give option for Add label and color

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#565]
Admin side need to give option for Add new menu label under food manager menu with the color option.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/79a5eb39-e1c4-410a-abdc-2288386f91f4)

Show here..
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/e6e495c3-af53-4a49-a0c9-a59296046073)

**Comment by patel-nimesh** [comment]
Now the label is displaying
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/555a076f-338f-4a2c-81fe-017afbe07d16)
