### ISSUE TITLE
Function must be in related file

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#567]
In previous code(version), there is all action-hook and filter-hooks are in 1 file only either it's admin related or front-end related, but from now adminpanel related hooks must be in related file only.

ex.

add_action('admin_enqueue_scripts', array($this, 'admin_enqueue_scripts'), 10);
above hook is related to admin-side so do not write this hook in wpfm-restaurant-manager-action-hooks.php but this must be in wpfm-restaurant-manager-admin.php

ex.
add_action('add_meta_boxes', array($this, 'add_meta_boxes'));
above hook is related to write-panel, so it must be inside wpfm-restaurant-manager-writepanels.php file not in wpfm-restaurant-manager-action-hooks.php.

**Comment by ritakikani** [comment]
These files should be in else condition

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/fcb5776d-638f-4bd7-a2b5-7f7243b71582)

**Comment by ritakikani** [comment]
Why this code used ? 

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/738e9d58-0aa6-421b-91f6-18b0a0f8a02a)

**Comment by ritakikani** [comment]
Need indentation : 

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/1cc970f5-a316-443e-a06d-f79709ec9c1b)

**Comment by ritakikani** [comment]
Need to change variable name : 

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/193106b6-b702-4241-8bc7-98fe1617a305)

**Comment by ritakikani** [comment]
This action should be in forms.php file construct function, and the function also should be there in forms.php file.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/d36993e7-cb11-4f2b-abf6-28a21c74e292)

**Comment by ritakikani** [comment]
These 3 action should in cache-helper.php


![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/1a927687-8aa8-46c3-abae-9287d30a651d)

**Comment by ritakikani** [comment]
These all should be in cache-helpers.php class

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/cfaf3f35-061f-4d42-8f14-e7ae779ed77d)

**Comment by ritakikani** [comment]
These must be in post-types.php file.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/ce46c296-15e6-4bbf-a4d1-46ddb64fad4e)

**Comment by ritakikani** [comment]
These should be in ajax.php file 

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/557ebf87-d7b2-42be-9315-a957f5d7cb4b)

**Comment by ritakikani** [comment]
According to me, these action is not used anywhere, so please check if not used then remove it.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/25837982/302483a5-e84b-4718-9f23-b3d99c05ba42)

**Comment by ritakikani** [comment]
@patel-nimesh please verify all the functionality of this plugin

**Comment by Shubham197** [comment]
![image (1)](https://github.com/user-attachments/assets/5ce7bca9-84ad-413a-a7ce-b42ee5b23f03)

@ritakikani ma'am
please fixed asap.

**Comment by Shubham197** [comment]
@ritakikani 
Still show fatal error.

![Screenshot_1](https://github.com/user-attachments/assets/505272f5-80b6-4e02-9d80-af001e75b3d8)

**Comment by patel-nimesh** [comment]
When edit the food from frontside then in topping section it shows the warning
Warning: Undefined variable $topping_item_count3 in D:\wamp64\www\foodmanager\wp-content\plugins\wp-food-manager\templates\food-submit.php on line 80
![image](https://github.com/user-attachments/assets/d8c3d6b9-507f-41dd-a2b9-7062a732aa2e)

**Comment by patel-nimesh** [comment]
If add multiple image then on food detail page it not looks proper
![image](https://github.com/user-attachments/assets/c72fb1a8-277c-4d5c-ac6d-c6124e77a341)
![image](https://github.com/user-attachments/assets/77cb98ec-fe23-4190-8982-65f21f4ba706)

**Comment by patel-nimesh** [comment]
Now the multiple image is working fine on food detail page
![image](https://github.com/user-attachments/assets/028f0eff-aeaa-4b44-a36d-4334adf8a44c)
