### ISSUE TITLE
SEO issue 

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#569]
Unnecessary code coming from all the page.

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/47e762e8-bc49-4b3b-aecd-96c17854f3d4)

**Comment by patel-nimesh** [comment]
Now the form is displaying for the link setting
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/ebe6cae4-4549-4adb-9328-0055515ecf52)
