### ISSUE TITLE
food image left or right side view setting. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#570]
We have to provide the setting if the user want to show food image left or right side.

<img width="1238" alt="image" src="https://github.com/wpfoodmanager/wp-food-manager/assets/35419531/f083e9e1-cc1c-4e9a-8f3f-0f14e519f4e0">

**Comment by patel-nimesh** [comment]
This setting is already covered in #563 So I am closing this issue
