### ISSUE TITLE
SEO issue

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#575]
1. Food Menu Page
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/272f105a-1b4b-4658-a353-ed14a3ab66cc)

**Comment by patel-nimesh** [comment]
Now the tag like p, heading h3 is applied in food title and description

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/7475c56c-d29f-457c-a3f7-132167324518)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/d2d18b75-d791-46f2-a595-35eb453fecb0)
