### ISSUE TITLE
Create WP Food Manager Tax class taxonomy.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#576]
New tax class taxonomie will show under the Food Manager menu. (WP Food Manager Core plugin)

Taxonnomy name should be - Tax Classes ( This code should be in WPFM Core plugin )
We will show dropdown Fix Value or Percentage discount.

**Comment by gandhirk** [comment]
I have created WP Food Manager Tax class taxonomy in the WPFM Invoice plugin. We can move this to WP food manger plugin.

Please refer to this change
https://github.com/wpfoodmanager/wpfm-invoice/commit/8771e2afd0bc2aff3f4a2893570dbc92ac93e5e7

**Comment by ritakikani** [comment]
This feature is removed because we change our flow of tax, can view here https://github.com/wpfoodmanager/wpfm-online-order/issues/427, so I am closing this issue.
