### ISSUE TITLE
SEO issue :  Links are not crawlable

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#577]
Links are not crawlable in menu page

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/496b8a85-bc63-4a77-9edc-5637412357f9)

**Comment by patel-nimesh** [comment]
This issue is fixed on menu page
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/5a01ad56-12ea-4180-ad79-f030ddd890a6)
