### ISSUE TITLE
Provide search option in menu.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#578]
We have to provide 2 options in menu.

1. Menu list should be stuck on top while scroll.
2. We should provide search filter option in menu page.

**Comment by patel-nimesh** [comment]
https://stg-harimokshrestaurant-staging.kinsta.cloud/menu/

Please refer the above link. On menu page if more menu are there then we need to scroll below.
So for that in top need to show all menu and on that menu click it will redirect or scroll to that menu

**Comment by dhruvikathrotiya** [comment]
@harsh-dhanani 
-The menu list should be stuck on top while scrolling.
- Create a proper UI.

**Comment by patel-nimesh** [comment]
@dhruvikathrotiya Please give option for menu sequence. 
Like we have give in restaurant detail page
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/10eff060-d9b2-4b20-8fc8-8faec9f61816)
 
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/ddad0bd0-1f97-4a3d-8cfd-d90a8211a80a)

**Comment by patel-nimesh** [comment]
@dhruvikathrotiya the search is not work properly as same food is not show when we do filter.

Also if result not found then it should be show message like not foods found

**Comment by patel-nimesh** [comment]
@dhruvikathrotiya Right now need to comment or remove this issue code from milestone 1.0.6 and we will consider this issue in next milestone 1.0.7

**Comment by rashmipsingh** [comment]
@kaushikpokal 
Menu list should be stuck on top while scroll.
Please do the needful.

**Comment by patel-nimesh** [comment]
@rashmipsingh If we clear the search then all foods are not showing or loading
![image](https://github.com/user-attachments/assets/5f149b37-2763-4626-91c4-52a1d79b4c24)

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/0f4e95c3-014a-4fe4-94f4-18dfdacf33a8)

**Comment by patel-nimesh** [comment]
@rashmipsingh Please check your issues.
If clear the search then also the all foods are not showing
![image](https://github.com/user-attachments/assets/baa2bff0-2e07-49b2-af1c-70b9ef8ea72c)

If more food search result then UI not shows proper. It should be in two column
![image](https://github.com/user-attachments/assets/9190b179-0578-4c4b-9145-a0edab0642f9)

**Comment by rashmipsingh** [comment]
#665 https://github.com/wpfoodmanager/wp-food-manager/issues/665

**Comment by rashmipsingh** [comment]
#665 

the code pushed here. @patel-nimesh
