### ISSUE TITLE
Action and fiters files not set properly

### ISSUE THREAD

**Issue by Shubham197** [wpfoodmanager/wp-food-manager#583]
In admin panel topping ajax not working

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/35462199/654678e6-258a-4f4b-b11f-122cf846671a)

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/35462199/cddf1bc2-7513-420e-9273-034008516f95)

**Comment by patel-nimesh** [comment]
Now admin side the ajax is working and topping is displaying on frontside

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/6dd0e89b-7319-486b-8d0b-f04543d0fed4)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/dd9490c8-8801-4912-b877-94b0c67b2c65)
