### ISSUE TITLE
Admin/Front : Add food topping creation is not working proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#584]
From admin side if try to create a topping then the field is not working properly

![image](https://github.com/wpfoodmanager/wpfm-online-order/assets/121149500/f74b8c6d-b282-4a0a-9989-9907db3f8f5f)

Also if click on add topping then it will display two options for topping. It should display only one
![image](https://github.com/wpfoodmanager/wpfm-online-order/assets/121149500/48f133dc-02f7-47e7-be0c-133d048d3d1d)

Also frontside topping creation is not working
![image](https://github.com/wpfoodmanager/wpfm-online-order/assets/121149500/b1a37be8-5e39-45d8-be14-cafcee462a15)

**Comment by patel-nimesh** [comment]
Admin side when click on add topping it is showing two field for topping creation

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/ca5fe795-0fb5-463c-94da-2b4304def666)

**Comment by Shubham197** [comment]
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/35462199/c38af290-d03f-416d-91ef-da8be04f5d4f)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/35462199/7d432940-4952-424f-8bb8-d013cd602450)

**Comment by patel-nimesh** [comment]
Now topping add show only one option of topping and single row when add or delete
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/15274efa-55e1-4914-89e4-ea77984fc1f3)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/20f8741b-1c6a-49e9-aea2-ee1489fc4115)
