### ISSUE TITLE
Menu is not look good in restaurant detail page.

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#586]
Menu is not look good in restaurant detail page.
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/83581741/8cd924b3-ee65-4f0c-a92b-3693bcd2238f)

**Comment by patel-nimesh** [comment]
Now on restaruant detail page menu is looks proper
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/6e62d4d8-8249-4676-a23e-284a0bc8c525)
