### ISSUE TITLE
Admin : license tab show multiple

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#588]
In admin side license tab show multiple

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/a1b62335-f282-4b67-a043-220552aca34a)

**Comment by patel-nimesh** [comment]
Also if custom menu is there then also the theme license menu is not showing
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/e83a1f92-eef5-4228-b1d9-a78d0f18d149)
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/4d364b0d-df54-4a23-b520-880699bfd04b)

**Comment by dhruvikathrotiya** [comment]
On the admin side, the license tab shows multiple issues resolved in the Restaurant manager add-on.
https://github.com/wpfoodmanager/wpfm-restaurant-manager/issues/262

**Comment by patel-nimesh** [comment]
Now the license tab is show single and after activating the other food manager addon the theme license is also showing
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/dfda2ab8-3bb2-4487-a71b-029f86b5406d)
