### ISSUE TITLE
Frontside : location availability popup shows warning

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#589]
when open foods page then the delivery availability checker popup shows the warning

![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/092c8a14-8e68-4139-a4e2-5d2a31849329)

**Comment by ritakikani** [comment]
This issue is resolve in this.
https://github.com/wpfoodmanager/wpfm-food-delivery/issues/90

**Comment by ritakikani** [comment]
This issue is resolved in delievry addon.

**Comment by patel-nimesh** [comment]
Now warning is not showing
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/20dae463-c3b3-4a18-846e-2ba178de7a82)
