### ISSUE TITLE
Frontside : On menu page we need to show the count in category

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#595]
On menu or category page we need to show the count of the actual food items

Refer the below reference
![image](https://github.com/wpfoodmanager/wp-food-manager/assets/121149500/cbf18d7e-7920-4f3e-9be5-19c62cd31744)

**Comment by rashmipsingh** [comment]
#617 
#618

**Comment by rashmipsingh** [comment]
![{CEC08A5D-8005-4649-A041-92FC6FD097A5}](https://github.com/user-attachments/assets/d9bcd275-5389-4127-9a9b-807b9cb653b5)
@kaushikpokal please style this list.

**Comment by patel-nimesh** [comment]
Now the count in food menu is working
![image](https://github.com/user-attachments/assets/81791359-c3b6-4a3c-a935-fde9ac7c98ad)
