### ISSUE TITLE
 Image format .webp is not support. 

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#597]
Image format .webp is not support for preview only

![image](https://github.com/wpfoodmanager/wpfm-restaurant-gallery/assets/83581741/80acb25c-3251-4ce6-80a9-a7363c5d9077)

https://github.com/wpfoodmanager/wpfm-restaurant-gallery/issues/88

**Comment by patel-nimesh** [comment]
Now the webp file preview is showing for the image
![image](https://github.com/user-attachments/assets/08f3d1f3-6983-43e5-912f-74bd44ae55ca)
