### ISSUE TITLE
click on photo it show the big photo with adding option to cart same like wolt

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#599]
click on photo it show the big photo with adding option to cart same like wolt

![image](https://github.com/user-attachments/assets/43d99ca8-e3bc-4f26-9aa8-79ff15d177c2)

**Comment by kaushikpokal** [comment]
![image](https://github.com/user-attachments/assets/1d02965a-1878-4157-a67f-279927ddc41c)

**Comment by patel-nimesh** [comment]
Now the popup will be open when click on food image
![image](https://github.com/user-attachments/assets/e1350e90-1c4d-469d-8189-750cd8041361)
![image](https://github.com/user-attachments/assets/27308b76-678a-4591-9a5d-270df68c6bcf)
