### ISSUE TITLE
Food Forms not save the submitted value.

### ISSUE THREAD

**Issue by KushangDarji** [wpfoodmanager/wp-food-manager#6]
**When I fill out the food's details and click on publish or update button, It can not save the details in database, Got empty values. It should save and display all the filling details in database and backend.**

![Screenshot_4](https://user-images.githubusercontent.com/25924876/182373112-c50d64d9-df46-4aa9-a037-45148dae4a30.png)

**Comment by KushangDarji** [comment]
Hello @krinaydhanani Sir,

Please move this bug to next milestone, as we discussed yesterday. Because there is lots of stuff in front end to display all food forms data, So it will take time.

**Comment by mistry-jignesh** [comment]
At backend enable/Disbale button is not working properly.

First enable button.
Now remove text from the box.
Observed that button is disable automatically.

https://user-images.githubusercontent.com/75515088/192197003-1a21f1db-d376-41ed-a988-324b5e39b0ab.mp4

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

Yes, I have managed this. If the textarea is empty, then it's automatically hide. For enter the text in textarea you have to enable again the checkbox. So it is not a bug, It's feature and managed by one type of validation for textarea and checkbox for ignoring unexpected values save in DB.

**Comment by mistry-jignesh** [comment]
But If I want to add new text then I need to remove **default text manually** .
So this is not more user friendly.

**Comment by mistry-jignesh** [comment]
Veriified this issue. Now I am remove text and new text can be add easily.

This issue is working fine.

So I closed the issue.

**Comment by mistry-jignesh** [comment]
Veriified this issue. Now I am remove text and new text can be add easily.

This issue is working fine.

So I closed the issue.
