### ISSUE TITLE
Cron : Licence key check for all addon.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#603]
In the core plugin, we have to check whether all the licence keys will activated or not.

For that, we have to make one cron file and from there, our core plugin will check licence key will work or not.

**Comment by patel-nimesh** [comment]
@ritakikani Please add license deactivate and plugin deactivation in all addon
![image](https://github.com/user-attachments/assets/8e7c134d-b309-4f2e-aad1-9110a7a254eb)
![image](https://github.com/user-attachments/assets/edf48a2e-159d-4aeb-841d-6e05555866a9)
