### ISSUE TITLE
when customer select  this item Palak Paneer oder Tofu then need selection

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#606]
For example from below image, when customer select  this item Palak Paneer oder Tofu then need selection

so restaurant owner know what he selected palak with paneer or with tofu..

<img width="1087" alt="Screenshot 2024-09-22 at 00 24 30" src="https://github.com/user-attachments/assets/9b24ee8a-ea6c-4763-9494-b33f3adcd12e">

**Comment by rashmipsingh** [comment]
#640 

This issue is already created. @patel-nimesh

**Comment by patel-nimesh** [comment]
This is duplicate issue of #640 so it will cover there
