### ISSUE TITLE
Admin : Menu the selected food category and type should be show and field type should be multi-select

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#607]
- If we select the category and type then it should be show the selected value in the dropdown list.

![image](https://github.com/user-attachments/assets/0ab8ddef-48c3-4d4c-a9b8-ceb367163822)

- The input type should be multiselect so user can easily show the selected food category/type and also the multiple options can be show and identify easily
like this
![image](https://github.com/user-attachments/assets/2031cf86-b2b7-460b-8e54-28f708f0ce32)

**Comment by patel-nimesh** [comment]
@rashmipsingh Here bydefault in old created menu it should be show the previous selected value
![image](https://github.com/user-attachments/assets/1a1d52b4-d690-4bbd-bf23-68bdacea7f85)

**Comment by rashmipsingh** [comment]
@patel-nimesh by default it wont be selected on old. you need to verify by the new selection.

**Comment by patel-nimesh** [comment]
@rashmipsingh First based on selected food category/types it will show the foods
![image](https://github.com/user-attachments/assets/51d0a5b7-3867-4150-af8c-e6795d2e7094)

Now if removed all selected value then why all foods are showing? Foods will be show based on the selected value
![image](https://github.com/user-attachments/assets/440a103f-72f4-4f89-806e-04a3e6bd853e)

**Comment by patel-nimesh** [comment]
Now it is working properly with multi select
![image](https://github.com/user-attachments/assets/72a9eb15-d33a-40ab-be14-f3a94861098b)
