### ISSUE TITLE
Admin : Menu creation need to show some message and loader when foods are added

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#609]
In menu created once we select any food category and type then show some loaded and after show message that indicate that foods are added into the menu

![image](https://github.com/user-attachments/assets/ab4af5e0-433b-4546-9391-5ac1261eea9a)

**Comment by dhruvikathrotiya** [comment]
![image](https://github.com/user-attachments/assets/0072e210-c319-4fee-9d15-83ee1b82bf2a)
![image](https://github.com/user-attachments/assets/68558ced-f6e7-4247-bff8-77bff4141ce9)

**Comment by patel-nimesh** [comment]
Now the loader and message is showing when foods are adding
![image](https://github.com/user-attachments/assets/3c2a71b1-ba63-4f79-9154-05c17f1ea898)
