### ISSUE TITLE
Frontside : Menu page need to improve the image size

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#610]
On menu page still the food image is getting cut

![image](https://github.com/user-attachments/assets/e08f9f96-5018-4b3e-84ab-5ccb55838ecd)

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/08c7edaa-52e3-423c-96f2-ac3c6fd3dac4)

**Comment by patel-nimesh** [comment]
Now image looks proper
![image](https://github.com/user-attachments/assets/d6021c0f-db42-4667-b684-3aa594342052)
