### ISSUE TITLE
Need to improve loading speed of menu page in swadishta

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#612]
the loading speed need to improve of the menu page

https://swadishta.de/swadishta-spandau-menu/

https://github.com/user-attachments/assets/87c80cf2-9854-42d5-aaed-40a5090dfbed

**Comment by ritakikani** [comment]
@patel-nimesh these pages are designed with elementor, so will not done by developer.
Solution  : We already developed shortcode for all menu title and for all menu items so please use that.

**Comment by patel-nimesh** [comment]
As per developer comment this is not a issue of addon
