### ISSUE TITLE
Admin : Menu need to set copy icon so on click the shortcode will be copied

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#613]
In food menu shortcode need to set copy icon and it will copy the particular food menu shortcode

![image](https://github.com/user-attachments/assets/50949c45-18cf-4a09-ac62-3010d69dc508)

**Comment by rashmipsingh** [comment]
@kaushikpokal Please fix the UI of this section.
![{59301200-9463-4E39-9A04-FC9233F588E5}](https://github.com/user-attachments/assets/6c6bb960-1beb-4527-b881-4a6daca04b00)

**Comment by patel-nimesh** [comment]
Now the copy icon added and shortcode will be copied
![image](https://github.com/user-attachments/assets/2daa14c4-eed4-4cac-b406-82299bd1367e)
