### ISSUE TITLE
Admin : Menu need to set proper text notice into disable food redirection

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#614]
Menu creation need to set proper text notice into disable food redirection that what is purpose or what it will be do

![image](https://github.com/user-attachments/assets/45fd7256-f7be-400e-bf7c-c95356055361)

**Comment by patel-nimesh** [comment]
The notice is added. But it should be show on hover of icon as it is not looks proper right now
![image](https://github.com/user-attachments/assets/44087c86-19f5-4b58-86eb-a1e8a151a9f1)

**Comment by dhruvikathrotiya** [comment]
![image](https://github.com/user-attachments/assets/2d171fd4-3004-4f54-8d57-4e201642ee78)

**Comment by patel-nimesh** [comment]
Now the notice has been added
![image](https://github.com/user-attachments/assets/72f07f4d-04b4-4fdd-990e-cc7bdd9eb848)
