### ISSUE TITLE
Shortcode for menu according to the restaurant branch vise

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#617]
Need to create a shortcode for the menu according to the restaurant branch vise.

If want to show all food menus according to the restaurant then it should be there.

**Comment by dhruvikathrotiya** [comment]
Shortcode for showing Restaurant branch-wise menu.
[restaurant_food_menu restaurant_id=398]

**Comment by patel-nimesh** [comment]
Now the shortcode is created to show all food menu for the restaurant  

![image](https://github.com/user-attachments/assets/5fa36c0d-b287-4e67-b27a-5c0902b6afab)
![image](https://github.com/user-attachments/assets/1e2057cf-f907-47ca-b065-f4858e82a151)
