### ISSUE TITLE
Shortcode for just show menu title

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#618]
Need to add a shortcode for just list menu list. In this it will just show the menu title of the restaurant

![image](https://github.com/user-attachments/assets/416f0787-df6f-4c85-acd0-74114ecfd09a)

**Comment by dhruvikathrotiya** [comment]
Shortcode for just show menu title
**[restaurant_food_menu_title restaurant_id=398]**

**Comment by patel-nimesh** [comment]
Now the shortcode for only show menu title of the restaurant is added and working
![image](https://github.com/user-attachments/assets/e38d14f5-4762-4be1-a4f1-2d158890fa55)
![image](https://github.com/user-attachments/assets/7a9d2e72-6d9c-4c47-b590-a2e5ee2bc868)
