### ISSUE TITLE
Admin : Add food Need to add or change the notice

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#620]
In food label need to add notice that where it will be show
![image](https://github.com/user-attachments/assets/2489b3eb-9a15-4bce-88d0-be4630a147be)

Reward point and gallery title
![image](https://github.com/user-attachments/assets/da41eb03-1842-41cf-99dc-04a9d3630e30)

Tax class need to add proper notice
![image](https://github.com/user-attachments/assets/03895a7a-94fc-47f2-9c54-8b1903437fca)

Setting food listing section need to improve the text notice content
![image](https://github.com/user-attachments/assets/3ff90405-ac7e-4aad-bf8b-fb8195b20b4b)

In food ingredients need to add notice that how to use it
![image](https://github.com/user-attachments/assets/b6b9ea38-59da-4f22-87d1-5cae90883726)

In food nutrition need to add notice that how to use it
![image](https://github.com/user-attachments/assets/ea02e30f-692d-4bf4-9f3a-b209329264f1)

In Advanced setting need to add proper notice text
![image](https://github.com/user-attachments/assets/94dfaae8-84f1-400a-a568-c381c8f94ed3)

The advance title should be change or set properly
![image](https://github.com/user-attachments/assets/6520c3bc-c56c-4fef-9ce3-294e8aac5289)

**Comment by dhruvikathrotiya** [comment]
@patel-nimesh Please provide updated content for each modification.

**Comment by patel-nimesh** [comment]
Food Label :- Enter food label will be show on Food menu and Food detail page.
Reward Point :- Enter point will be applied when customer order this food.
Gallery title :- The selected category will be show on food detail page.
Tax Class :- Selected tax class will be applied when customer order this food.
Multi-select Food Categories :- If enabled, the Food Category select box will default to a multi select on the food listing page in filter section.
Multi-select Food Types :- If enabled, the Food Type select box will default to a multi select on the food listing page in filter section.
Multi-select Food Menu :- If enabled, the Food Menu select box will default to a multi select on the food listing page in filter section.
Food Thumbnail :- Based on any option selection, it will reflect the thumbnail placement on food menu page.
Food Ingredients :- Please drag and drop the available ingredient and enter the value.
Food Nutritions :- Please drag and drop the available nutritions and enter the value.
Advanced setting :- Based on the given setting the ingredients and nutrition will be show on food detail page.

**Comment by patel-nimesh** [comment]
Now all notice text has been added and updated
