### ISSUE TITLE
Admin : Need to add icon for ingredients and tax class

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#621]
Add food page admin side need to add icon for the ingredients and tax class

![image](https://github.com/user-attachments/assets/543d9245-f65c-4dda-a32b-a5127ef43ba4)

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/ba6efc60-b8b3-40fb-9b4b-44dce1243705)

**Comment by patel-nimesh** [comment]
Now the icons are added
![image](https://github.com/user-attachments/assets/fefe693b-020f-4fb2-aa5b-d43c6f3456bb)
