### ISSUE TITLE
Admin : Add food topping section should show some notice

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#622]
In add food options section need to add notice that here add the options and price for the topping

![image](https://github.com/user-attachments/assets/7e3558ce-805f-4351-ad81-2bccbd6357b5)

The topping name field placeholder text is getting cut
![image](https://github.com/user-attachments/assets/3231890e-4d88-4378-9391-d79d6abd25ba)

Need to add proper placeholder text into options section
![image](https://github.com/user-attachments/assets/c9a1ba99-ae9a-4c2d-aad6-9a337dcf89a5)

Topping section add row button title not suitable please change it to suitable
![image](https://github.com/user-attachments/assets/be10ec60-49d7-46f9-b5ea-968f61f18d39)

**Comment by patel-nimesh** [comment]
@dhruvikathrotiya Still topping field name placeholder text getting cut
![image](https://github.com/user-attachments/assets/421ad3e8-e6d8-466d-9dc0-4481bc343416)

Still the options placeholder and button text is not changed
![image](https://github.com/user-attachments/assets/6fff0306-82a0-4679-bf5d-2920657aa497)

**Comment by rashmipsingh** [comment]
@patel-nimesh **Still the options placeholder and button text is not changed**
![image](https://github.com/user-attachments/assets/693bc1ab-d872-42bf-8f43-5d7e473dfa52)
Now the placeholder and button text is added.

**Comment by rashmipsingh** [comment]
**Still topping field name placeholder text getting cut.**
![image](https://github.com/user-attachments/assets/858cacca-9686-4b49-ba49-e8120e5fec27)
@patel-nimesh this is an UI bug. @kaushikpokal please fix this.

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/cb1c8347-e9d9-466d-b2f8-1971ae45ebdd)

**Comment by patel-nimesh** [comment]
Now it looks proper
![image](https://github.com/user-attachments/assets/68049f9d-c182-4b9f-9c41-b70c29bb1f97)
