### ISSUE TITLE
Admin : Add food page topping button position should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#625]
Add food page topping button position should be proper

![image](https://github.com/user-attachments/assets/0679442e-3442-4490-a998-2cbc85a6067f)

**Comment by rashmipsingh** [comment]
@kaushikpokal I have added this, you need to do close /open like accordion. 
![{A291C93C-170F-48C4-99FF-E5A7214E2433}](https://github.com/user-attachments/assets/d84ed9aa-7fb9-4771-9e18-c2c2e5b5eb46)
![{7B6F90F3-2ED8-4C63-8223-19D09FCF7572}](https://github.com/user-attachments/assets/7ef3fc02-8355-4126-a3ea-ad695b844f1f)

**Comment by ritakikani** [comment]
@rashmipsingh please remove duplicated code from else part, you can not put same code if part in else part, you need to find other way.

**Comment by patel-nimesh** [comment]
The design part is remain for accordian

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/0c6e9fee-d85d-4660-a554-ac9044b4203a)

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/0394b33f-9439-4ceb-926f-575000de812e)

**Comment by patel-nimesh** [comment]
Now admin side topping field looks proper
![image](https://github.com/user-attachments/assets/ba759299-7c1a-492d-beba-f103a0536d11)
