### ISSUE TITLE
Frontside : If food type has no food then shows warning on food type page

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#629]
If the food type has not assign any food then on front side on type page shows warning

Warning: Attempt to read property "post_content" on null in C:\xampp\htdocs\tester\wp-content\plugins\wpfm-restaurant-manager\includes\wpfm-restaurant-manager-action-hooks.php on line 172

![image](https://github.com/user-attachments/assets/aa6d0381-4d58-4c64-8473-717deaf11e03)
![image](https://github.com/user-attachments/assets/781ccf23-2215-47df-bef1-652ff24bcddb)

**Comment by dhruvikathrotiya** [comment]
Currently, no warning messages are displayed.

**Comment by patel-nimesh** [comment]
Now no warning is showing
![image](https://github.com/user-attachments/assets/e642e5cd-75de-437a-a949-38bdb19eecf5)
