### ISSUE TITLE
Frontside : delivery popup will not show on page where use the menu shortcode

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#638]
If use a food menu shortcode on any page then on frontside the delivery availability checker popup will not show while add to cart

![image](https://github.com/user-attachments/assets/539b25f5-5139-4383-a0f1-3681e5459cd5)

**Comment by patel-nimesh** [comment]
Now the popup is showing on a page where the food menu shortcode is used
![image](https://github.com/user-attachments/assets/8a2e983d-57c3-434f-a20a-7c30138b39bb)

**Comment by Shubham197** [comment]
![image](https://github.com/user-attachments/assets/2528ca76-25cd-4782-8b90-012a0b3a8b94)
