### ISSUE TITLE
Frontside : In popup the topping should be show and able to add to cart

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#640]
On food popup the topping should be display and it should be able to add to cart while food ordering

Reference link :- https://wolt.com/en/deu/berlin/restaurant/dosaking-indisches-restaurant/special-fur-2-itemid-50e37d1f0647aa3c05c26709

![image](https://github.com/user-attachments/assets/c9b4aef6-0128-4c75-94cf-64f88774aec2)
![image](https://github.com/user-attachments/assets/7ca7d7f1-d88c-4568-aaec-fc3c3da3653c)

**Comment by rashmipsingh** [comment]
![{03F4BA5D-9B7B-4951-B14D-1B3AA7F2A790}](https://github.com/user-attachments/assets/50e9d8d5-1b2f-40db-9e40-b194356827f7)
Now the toppings are showing with other data on popup.

**Comment by patel-nimesh** [comment]
@kaushikpokal Please make UI proper of the popup
![image](https://github.com/user-attachments/assets/97d4c58f-e0dc-4b9e-bca6-53dac9e6c48d)

**Comment by rashmipsingh** [comment]
#661

**Comment by patel-nimesh** [comment]
Now the popup UI is proper
![image](https://github.com/user-attachments/assets/e048d739-cd97-4dc5-91db-8567c27b5ad6)
