### ISSUE TITLE
Console Error For SEO: Uncaught TypeError: jQuery(...).slick is not a function

### ISSUE THREAD

**Issue by kaushikpokal** [wpfoodmanager/wp-food-manager#644]
![image](https://github.com/user-attachments/assets/61ffc9b2-1088-4892-ba5c-7dd0e1f54889)

**Comment by patel-nimesh** [comment]
Now in console no error is showing
![image](https://github.com/user-attachments/assets/cd05a039-037b-4323-ba69-fa2fdbd49008)
