### ISSUE TITLE
Admin : Add food topping name add auto suggestion is stopped working

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#650]
In admin side add topping auto name filter suggestion and auto take description is stopped working

![image](https://github.com/user-attachments/assets/c53fffa3-1551-4505-883e-974de8c48687)

Also add options is not working
![image](https://github.com/user-attachments/assets/5dba3cae-ae34-4a79-9678-61a7e4a5cd0e)

**Comment by dhruvikathrotiya** [comment]
![image](https://github.com/user-attachments/assets/49bf52ac-7d08-4352-9fda-9699d1035807)

**Comment by patel-nimesh** [comment]
Here two issues are there 

- After the selection of the topping name from list the dropdown should be close
- In description the automatic description of the selected topping is not coming
![image](https://github.com/user-attachments/assets/97298435-534b-496b-a90c-cf5b3e3f287f)

**Comment by patel-nimesh** [comment]
Now it is working
![image](https://github.com/user-attachments/assets/945985d7-637f-4356-87d3-9139447edc34)
