### ISSUE TITLE
Need to add shortcode menu

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#651]
Need to add shortcode menu same like event manager. In that menu need to mention all plugin shortcode based on plugin activation using hooks.

![image](https://github.com/user-attachments/assets/09bc7dfb-9c7c-4f5b-9485-e152e347159b)

**Comment by patel-nimesh** [comment]
@dhruvikathrotiya Please make necessary change for favourite list addon
![image](https://github.com/user-attachments/assets/6a3dbcb4-fa8f-4259-8cb0-c257e6c12650)

**Comment by dhruvikathrotiya** [comment]
This issue resolved in favorites list addon
https://github.com/wpfoodmanager/wpfm-favorites-list/issues/31

**Comment by patel-nimesh** [comment]
Now the shortcode menu is created and all shortcode will be show here
![image](https://github.com/user-attachments/assets/0f9c928a-a17d-411e-b794-42912ab6316f)
![image](https://github.com/user-attachments/assets/94909f3a-dbca-4f20-b972-203fa948917f)
