### ISSUE TITLE
Admin : Add food section the food type shows extra in food data

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#656]
In add food section the food type shows extra need to removed it

![image](https://github.com/user-attachments/assets/abde8382-8083-4cc9-ab11-fa6f73066519)

Tax class position also changed
![image](https://github.com/user-attachments/assets/5c393a2e-ab35-4ce0-bc10-e6cca5fe8404)

**Comment by rashmipsingh** [comment]
@patel-nimesh for this, **Tax class position also changed**

we cannot code this in core plugin,, we need to do it in invoice plugin.

**Comment by patel-nimesh** [comment]
Now food types and tax class show properly

![image](https://github.com/user-attachments/assets/85d9ed4b-0369-4e6e-936e-207b1b0f55b3)
![image](https://github.com/user-attachments/assets/10fe7c09-24e1-487f-993a-e1004b8b56de)
