### ISSUE TITLE
Frontside : In food popup the sale price is not looks proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#657]
In food popup the regular price is not looks proper

![image](https://github.com/user-attachments/assets/63e23a19-61e3-4cb2-818c-5fc5b0bf9e98)

**Comment by rashmipsingh** [comment]
@patel-nimesh this is the Ui issue. I am assigning this to @kaushikpokal

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/90746b15-b2cd-4f67-aab4-a7cc6316bfee)

**Comment by patel-nimesh** [comment]
Now sale price is looks proper
![image](https://github.com/user-attachments/assets/75fa8759-a130-49ef-90d6-7a119b0036a0)
