### ISSUE TITLE
Frontend: Menu page popup doesnot allow to reach close button.

### ISSUE THREAD

**Issue by rashmipsingh** [wpfoodmanager/wp-food-manager#661]
![image](https://github.com/user-attachments/assets/b329e935-2a83-436f-9bac-7e61f9eb6b66)
when there are multiple numbers of toppings, and due to this popup height increased. 
Popup is open but I am not able to find close button.
**Note :** Please check on laptop screens resolutions. 1366 * 1024

Also when I click on any menu, there # string is added in the url, which can be removed.

**Comment by harsh-dhanani** [comment]
![image](https://github.com/user-attachments/assets/20abd441-df08-4015-8d76-212d028e6b8b)

@patel-nimesh issue resoved

**Comment by patel-nimesh** [comment]
Now scroll bar is added so now it is working
![image](https://github.com/user-attachments/assets/1f3e8486-01d5-4a05-8e10-086c558bde5d)
