### ISSUE TITLE
Modify filters and frontend jquery for compatibility with online order features

### ISSUE THREAD

**Issue by RavindraSingh2001** [wpfoodmanager/wp-food-manager#664]
- Trigger a jquery event when the food popup is opened
- Add the food_id variable in the wpfm_food_toppings_form_variation filter

**Comment by patel-nimesh** [comment]
Now the popup is working on click of food image from menu
![image](https://github.com/user-attachments/assets/e971bddc-9f79-462f-8d96-6f520335dfef)
