### ISSUE TITLE
Frontend : In Food details page & menu popup not show checkbox icon

### ISSUE THREAD

**Issue by Shubham197** [wpfoodmanager/wp-food-manager#668]
In food details page 
![image](https://github.com/user-attachments/assets/02c66274-70b1-43a7-a218-fc9b41e1d4c5)

In menu popup
![image](https://github.com/user-attachments/assets/9fd68ed5-a379-46f1-85a2-26259391e6c5)

**Comment by Shubham197** [comment]
Food details page
![image](https://github.com/user-attachments/assets/7be786ae-560e-46d7-b510-bed975f6dbaf)

menu page popup
![image](https://github.com/user-attachments/assets/433156a3-e245-4597-9292-64528f8cbd9e)

**Comment by patel-nimesh** [comment]
Now in food popup and in food detail page topping shows the checkbox
![image](https://github.com/user-attachments/assets/43f79a51-f5c2-4f58-ad9f-db90ee6c171c)
![image](https://github.com/user-attachments/assets/d97cd7f4-7469-49e6-b264-ad40ce2d602a)
