### ISSUE TITLE
Allow custom attributes like data-attribute_name, data-val etc. in the food toppings fields

### ISSUE THREAD

**Issue by RavindraSingh2001** [wpfoodmanager/wp-food-manager#670]
We need to allow custom attributes like data-attribute_name, data-val etc. in the food toppings fields. Currently the these types of custom attributes gets removed when using the function wp_kses() to sanitize the html which breaks the add to cart functionality of topping variations.

**Comment by patel-nimesh** [comment]
Now in cart the toppings are showing
![image](https://github.com/user-attachments/assets/2256c077-859b-4da0-835f-114a23886ba9)
