### ISSUE TITLE
Admin : Shortcode list not looks proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#673]
In fresh setup shortcode list section is not proper. Just activated the WP Food Manager (core plugin)

![image](https://github.com/user-attachments/assets/435f49af-c0c7-4030-b95c-3e312a74bd03)

**Comment by ritakikani** [comment]
@rashmipsingh Also below 3 shortcode should be in restaurant manager not in core plugin so please remove from here and add in restaurant manager.

![image](https://github.com/user-attachments/assets/30788ac8-28e7-4e14-b302-5c24d2eabefd)

**Comment by rashmipsingh** [comment]
@ritakikani code removed. and @patel-nimesh this is the UI bug so I am assigning to @kaushikpokal .

**Comment by kaushikpokal** [comment]
![image](https://github.com/user-attachments/assets/ff0f2856-7fd4-4ce9-9deb-d13d68bb9cbc)

**Comment by patel-nimesh** [comment]
Now this looks proper
![image](https://github.com/user-attachments/assets/afee4dd7-32e3-46bb-9934-96d217536a0b)
