### ISSUE TITLE
Admin: enhance the code for food stock label

### ISSUE THREAD

**Issue by rashmipsingh** [wpfoodmanager/wp-food-manager#675]
![{B17C7192-B7F2-4979-8F4C-36C3647AC0AE}](https://github.com/user-attachments/assets/0b0990ba-013f-40b5-8768-c33fe2ecd4a0)
Here I want to add food stock staus from other addon settings, so for this I have to add here apply_filters property.

**Comment by rashmipsingh** [comment]
After code done.

![{D7130A81-9E1A-4B3F-8C2F-E8FE0D6206B8}](https://github.com/user-attachments/assets/4dc8ac84-e2f7-4f40-94c4-3cf109475fbc)

**Comment by rashmipsingh** [comment]
@ritakikani I am assigning you because this is a code level issue.

**Comment by ritakikani** [comment]
Code is ok so i am closing this issue.
