### ISSUE TITLE
Use pickup word instead of take away.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#677]
We need to use the Pickup Word in the plugin rather than Take away.

**Comment by ritakikani** [comment]
@krinaydhanani this issue is resolved in https://github.com/wpfoodmanager/wpfm-food-delivery/issues/202 , https://github.com/wpfoodmanager/wpfm-online-order/issues/428 , https://github.com/wpfoodmanager/wpfm-restaurant-manager/issues/353

**Comment by patel-nimesh** [comment]
Now in fresh setup it will show Pickup
![image](https://github.com/user-attachments/assets/37105868-d541-4756-a9ed-b017c39221d9)
![image](https://github.com/user-attachments/assets/8c89e483-f2be-406d-a4a8-36ca8b7d72f8)
![image](https://github.com/user-attachments/assets/d55ed48c-f3aa-4e5d-a908-b80bc209d271)
