### ISSUE TITLE
error while try to add new plugin after activate food manager core plugin

### ISSUE THREAD

**Issue by ritakikani** [wpfoodmanager/wp-food-manager#678]
I setup new wordpress v.6.7.1, I install food manager core plugin and then try to add new plugin I got below error

![image (3)](https://github.com/user-attachments/assets/162dc695-4642-4d47-802a-2628e0b91207)

**Comment by patel-nimesh** [comment]
I installed the plugin in fresh setup and did not found any error
![image](https://github.com/user-attachments/assets/104ce59d-ae5d-4d92-968a-672633cf5844)
