### ISSUE TITLE
Backend - Able to change food postion 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#69]
Able to change food postion . This should not be change.

https://user-images.githubusercontent.com/75515088/192772946-8ff3c4b0-f19d-4f38-83f1-d7b8c5e0c6f5.mp4

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

This functionality is already added and working fine. Please check the food listing page at backend and try to change the food position using drag.

**Comment by mistry-jignesh** [comment]
As per @KushangDarji - This functionality is already added and working fine. At backend food position change using drag option. So I closed issue.
