### ISSUE TITLE
Readme.txt

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#7]
Need to update readme.txt according to keyword ranking compare to competitors.

Please check readme.txt file of wp event manager and talk with krinay and you will get more idea.

**Comment by krinaydhanani** [comment]
Duplicate issue - https://github.com/wpfoodmanager/wp-food-manager/issues/2

**Comment by krinaydhanani** [comment]
https://docs.google.com/document/d/1ZKDuBYdXdm5713EtS_GxfHRaiecuCg_HbE2E8X_FFBs/edit

**Comment by krinaydhanani** [comment]
Still we have to improve this file so I am going to move this enhancement in next milestone.

**Comment by krinaydhanani** [comment]
Yes readme file updated so I am going to close this issue.
