### ISSUE TITLE
Food Data Section V2

### ISSUE THREAD

**Issue by kushang-tailor** [wpfoodmanager/wp-food-manager#72]
Want to discuss with below sheet's plugins and make compatible with WooCommerce.
https://docs.google.com/spreadsheets/d/10g1QwQgDfwfR0FnBuOpjrvk0uRZ_k3_JX_sEZG7rWIY/edit#gid=1344416069

**Comment by mistry-jignesh** [comment]
Verified Food data section from backend & frontend. Now this section is working .

As per @kushang-tailor :   **WooCommerce compatibility,** There is one issue already open in this milestone. 
Here is the reference issue ID https://github.com/wpfoodmanager/wp-food-manager/issues/60

So I closed the issue.
