### ISSUE TITLE
Food Menu - Food icon is not availabel

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#75]
Food Menu - Food icon is not availabel.

![image](https://user-images.githubusercontent.com/75515088/193543429-c720be59-838e-4e98-af50-9539ed5a296a.png)

**Comment by kaushikpokal** [comment]
[wp-food-manager-v1.0.zip](https://github.com/wpfoodmanager/wp-food-manager/files/10073262/wp-food-manager-v1.0.zip)

**Comment by mistry-jignesh** [comment]
Now Food Menu - Food related icon is availabel in list.

So I closed the issue.
