### ISSUE TITLE
Food Menu V2

### ISSUE THREAD

**Issue by kushang-tailor** [wpfoodmanager/wp-food-manager#76]
**Reference Issue Number #11** 

Need to discuss and Add new features after discussion,

![image](https://user-images.githubusercontent.com/25924876/193563512-2fd67d13-f432-4c0b-b7c2-5703fd0c5c7d.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

User will select category then according category food is added .

Here category has possibility image is remaining. For this create new issue.

Issue no is - https://github.com/wpfoodmanager/wp-food-manager/issues/131

So I closed the issue.
