### ISSUE TITLE
Orderby is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#82]
Orderby is not working. Need to check it.

![image](https://user-images.githubusercontent.com/75515088/194310700-c6718338-b3bd-46e3-9662-bc0729924071.png)

**Comment by mistry-jignesh** [comment]
Verified this issue facing issue with Foot Type & Foot Category - **(Order by - ASC/DESC)**

![image](https://user-images.githubusercontent.com/75515088/195772717-58da35b5-b616-4504-988d-56e033d00784.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

Due to Multi Selection value, I have removed the **Food category** and **Food type** from the filter options.

**Comment by mistry-jignesh** [comment]
Verified this issue. Food title is workig fine (ASC/DESC).

As  per @kushang-tailor - Due to Multi Selection value, I have removed the Food category and Food type from the filter options.
