### ISSUE TITLE
Text improvement for installation stapes and settings.

### ISSUE THREAD

**Issue by krinaydhanani** [wpfoodmanager/wp-food-manager#84]
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/35419531/194377251-ee2129cb-08eb-428f-97fe-91ea614f4483.png">

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/35419531/194377302-94b43c24-0318-44bc-ace2-9f23c1e48a72.png">

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/35419531/194377463-a1e40ffb-8529-4cf8-8990-019e2782522c.png">

**Comment by vry-kvl** [comment]
This issue is allready resolve.

@patel-nimesh - Please Verify.

**Comment by patel-nimesh** [comment]
![image](https://user-images.githubusercontent.com/121149500/211724164-3c63cde4-2648-40f7-b41a-8f510616e02e.png)

now only three page will create ...
