### ISSUE TITLE
Backend -Menu should chanage according selecting category

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#89]
Backend - Menu should change according selecting category.

Currently it is static.

![image](https://user-images.githubusercontent.com/75515088/195067522-b09f1686-83b5-4e0e-b36d-ff1a5735c35f.png)

**Comment by ashokdudhat** [comment]
yes but once you will add food by pressing add food button then it wil add right ?

**Comment by mistry-jignesh** [comment]
This issue is alreday fixed and working fine.

According changed category ,Now selected food menu.

So here I closed the issue.
