### ISSUE TITLE
After click on the view page buttont then display message  page not found message is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#9]
- 1.Add new food at backend.
- 2.Click on the view page button.
- 3.Here page not found message is display.

![image](https://user-images.githubusercontent.com/75515088/182525419-4c830c05-90be-4bdf-ab4f-54f912a4ed9a.png)

**Comment by KushangDarji** [comment]
Hello @mistry-jignesh ,

For this, you need to save the permalink from the settings at backend. Please review the attach screenshot....
Step:1:  Dashboard > Settings > Permalink > Save.

If not working with step 1,
Step:2: Dashboard > Settings > Permalink > Select **Plain** radio button from the common settings > Save.

![image](https://user-images.githubusercontent.com/25924876/182525955-004e79ec-1298-46f7-9c77-0d01b7159bd4.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this is fixed and working.

Follow step2 & performed setting .

Now 404 error message issue is fixed .

So I closed the issue.
