### ISSUE TITLE
General Settings : Text need to improve

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#98]
Need to improve proper text for the following settings.

<img width="1180" alt="Screenshot 2022-10-13 at 23 11 29" src="https://user-images.githubusercontent.com/15089059/195711480-dfa7e128-00a6-44b0-bd98-7e98d5554053.png">

**Comment by kushang-tailor** [comment]
Hello @krinaydhanani Sir,

I have added the small description for mentioned settings. So, Can you please check on your end!

**Comment by mistry-jignesh** [comment]
I have verified this issue.  Now description availabel for the General Settings tab option.

@krinaydhanani - Please check at your end . Need any improvement .Please suggest it.

Need to add text below mentions points.

![image](https://user-images.githubusercontent.com/75515088/198277044-67bcd2c1-2ed5-4667-9671-121be73e553b.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now description is updated availabel in the the General Settings tab option.

@krinaydhanani - Please check at your end . Need any improvement . Please suggest it.

So we can add further changes in the text description.

**Comment by mistry-jignesh** [comment]
Description is updated availabel in the the General Settings tab option.
So I closed the issue .
